import { BranchingChapter } from '../types';

/**
 * CHAPTER 7: THE GATHERING - 5 Stages, full branching
 * The conspiracy goes deeper. "The Board" is revealed.
 * PERSPECTIVE: Detective Marcus Cole races against time.
 * Ashford was just the public face. The real power is still out there.
 * NO DEATH NODES - Investigation/infiltration chapter
 */
export const CHAPTER_7: BranchingChapter = {
  id: 7,
  title: "CHAPTER 7",
  subtitle: "The Gathering",
  startNode: "7-s1",
  nodes: {
    // ========== STAGE 1: THE DISCOVERY ==========
    "7-s1": {
      id: "7-s1",
      type: "choice",
      text: "Ashford's hidden safe contained more than trophies. Encrypted drives. Coded ledgers. And references to something called 'The Board' - seven individuals whose names appear only as symbols. A crown. A sword. A scale. A serpent. A tower. A key. A mirror. These aren't criminals hiding from the law. They ARE the law. Industry. Government. Media. Ashford answers to them. And in three weeks, they're meeting on American soil for 'The Gathering.'",
      question: "STAGE 1/5 — How do you begin investigating The Board?",
      timerSeconds: 20,
      choices: [
        { id: 'a', text: "Decrypt Ashford's files for more information", nextNode: "7-s1-decrypt", consequence: "Digital breadcrumbs..." },
        { id: 'b', text: "Interrogate Ashford directly", nextNode: "7-s1-interrogate", consequence: "He might talk..." },
        { id: 'c', text: "Cross-reference the symbols with known figures", nextNode: "7-s1-symbols", consequence: "Who are they?" },
        { id: 'd', text: "Find the location of The Gathering", nextNode: "7-s1-location", consequence: "Where are they meeting?" },
      ],
    },
    "7-s1-decrypt": {
      id: "7-s1-decrypt",
      type: "choice",
      text: "The FBI's best cryptographers work on Ashford's drives for 72 hours straight. What they find chills you to the bone. Meeting minutes going back thirty years. The Board has influenced elections, crashed economies, started wars. All to maintain their network of exploitation. And The Gathering isn't just a meeting - it's an auction.",
      question: "What does the auction involve?",
      timerSeconds: 20,
      choices: [
        { id: 'a', text: "New victims being sold", nextNode: "7-s1-decrypt-victims", consequence: "The horror continues..." },
        { id: 'b', text: "Political favors and influence", nextNode: "7-s1-decrypt-influence", consequence: "Power for sale..." },
        { id: 'c', text: "Blackmail material on world leaders", nextNode: "7-s1-decrypt-blackmail", consequence: "Leverage..." },
        { id: 'd', text: "All of the above", nextNode: "7-s1-decrypt-all", consequence: "Everything is for sale..." },
      ],
    },
    "7-s1-decrypt-victims": { id: "7-s1-decrypt-victims", type: "narrative", text: "Twenty-three people are scheduled to be 'presented' at The Gathering. Ages, descriptions, origins - all catalogued like merchandise. Some are already missing. Others don't know they've been selected. You have three weeks to find them before the auction.", nextNode: "7-s2", document: { title: "AUCTION_MANIFEST.pdf", preview: "23 potential victims identified. Locations being traced...", pdfUrl: "/documents/auction-manifest.pdf" } },
    "7-s1-decrypt-influence": { id: "7-s1-decrypt-influence", type: "narrative", text: "Cabinet positions. Judicial appointments. Legislative votes. All available to the highest bidder. The Board doesn't just break laws - they write them. Decades of policy shaped to protect their interests and expand their reach.", nextNode: "7-s2" },
    "7-s1-decrypt-blackmail": { id: "7-s1-decrypt-blackmail", type: "narrative", text: "Recordings. Photographs. Documents. The Board has compromising material on hundreds of powerful people worldwide. That's how they maintain control - not through loyalty, but through fear. Anyone who steps out of line gets destroyed.", nextNode: "7-s2", document: { title: "BLACKMAIL_INDEX.pdf", preview: "Hundreds of compromised officials identified...", pdfUrl: "/documents/blackmail-index.pdf" } },
    "7-s1-decrypt-all": { id: "7-s1-decrypt-all", type: "narrative", text: "The Gathering is a marketplace for evil. Victims. Influence. Leverage. Everything has a price, and The Board takes a percentage of every transaction. They've built a parallel economy of human misery - and it's been operating in plain sight for decades.", nextNode: "7-s2" },
    "7-s1-interrogate": {
      id: "7-s1-interrogate",
      type: "choice",
      text: "Ashford sits in a federal holding facility, awaiting trial. His lawyers have advised him to say nothing. But when you enter the room, he smiles. 'Detective Cole. I wondered if you'd visit.' 'Tell me about The Board.' His smile fades. 'You don't know what you're asking.'",
      question: "How do you approach Ashford?",
      timerSeconds: 20,
      choices: [
        { id: 'a', text: "Offer a deal - reduced sentence for information", nextNode: "7-s1-interrogate-deal", consequence: "Everyone has a price..." },
        { id: 'b', text: "Appeal to any remaining humanity", nextNode: "7-s1-interrogate-humanity", consequence: "Is there anything left?" },
        { id: 'c', text: "Threaten exposure of everything", nextNode: "7-s1-interrogate-threat", consequence: "His legacy destroyed..." },
        { id: 'd', text: "Tell him The Board will silence him anyway", nextNode: "7-s1-interrogate-fear", consequence: "He's not safe..." },
      ],
    },
    "7-s1-interrogate-deal": { id: "7-s1-interrogate-deal", type: "narrative", text: "'A deal?' Ashford laughs. 'Detective, I'm facing life in prison. What could you possibly offer?' 'Protective custody. Your own cell block. No accidents in the shower.' The laugh dies. He knows what happens to people who fail The Board. 'I'll give you one name. The Crown. She runs everything.'", nextNode: "7-s2", document: { title: "ASHFORD_DEBRIEF.pdf", preview: "Partial cooperation. 'The Crown' identified as leader...", pdfUrl: "/documents/ashford-debrief.pdf" } },
    "7-s1-interrogate-humanity": { id: "7-s1-interrogate-humanity", type: "narrative", text: "'Humanity?' He stares at you. 'I built hospitals. Schools. My foundation helped thousands.' 'While trafficking hundreds.' Long silence. 'The Board selected me when I was twenty-three. Groomed me. Funded me. By the time I understood what they really were... I was already one of them.' A confession, of sorts.", nextNode: "7-s2" },
    "7-s1-interrogate-threat": { id: "7-s1-interrogate-threat", type: "narrative", text: "'Your foundation is being investigated. Your donors exposed. Every charity gala, every awards ceremony, every handshake with a world leader - all tainted.' Ashford's composure cracks. 'My legacy...' 'Will be human trafficking. Unless you help us stop The Gathering.'", nextNode: "7-s2" },
    "7-s1-interrogate-fear": { id: "7-s1-interrogate-fear", type: "narrative", text: "'You think you're safe in federal custody? The Board has people everywhere. Judges. Guards. Prosecutors. If they decide you're a liability...' Ashford goes pale. 'You can't protect me.' 'No. But I can give you a chance to take them down first.'", nextNode: "7-s2", document: { title: "WITNESS_PROTECTION.pdf", preview: "Ashford requests protection. Willing to cooperate...", pdfUrl: "/documents/ashford-protection.pdf" } },
    "7-s1-symbols": {
      id: "7-s1-symbols",
      type: "choice",
      text: "Seven symbols. Seven Board members. You spread the evidence across Chen's conference room, looking for patterns. The Crown appears on documents from European banks. The Sword on military contracts. The Scale on legal proceedings. Each symbol represents a sphere of influence.",
      question: "Which symbol do you investigate first?",
      timerSeconds: 20,
      choices: [
        { id: 'a', text: "The Crown - apparent leader", nextNode: "7-s1-symbols-crown", consequence: "The head of the snake..." },
        { id: 'b', text: "The Sword - military connections", nextNode: "7-s1-symbols-sword", consequence: "Armed and dangerous..." },
        { id: 'c', text: "The Key - seems to control access", nextNode: "7-s1-symbols-key", consequence: "Gatekeeper..." },
        { id: 'd', text: "The Mirror - intelligence/surveillance", nextNode: "7-s1-symbols-mirror", consequence: "They see everything..." },
      ],
    },
    "7-s1-symbols-crown": { id: "7-s1-symbols-crown", type: "narrative", text: "The Crown's signature appears on the oldest documents - predating even the island. Financial transfers through old European banking families. Connections to royalty, old money, generational wealth. Whoever The Crown is, their family has been doing this for centuries.", nextNode: "7-s2", document: { title: "CROWN_ANALYSIS.pdf", preview: "Generational conspiracy. European banking connections...", pdfUrl: "/documents/crown-analysis.pdf" } },
    "7-s1-symbols-sword": { id: "7-s1-symbols-sword", type: "narrative", text: "The Sword controls the security apparatus. Private military contractors. Intelligence assets. The guards on the island were just the visible layer - beneath them, a network of ex-special forces from a dozen countries. The Sword can project force anywhere in the world within 48 hours.", nextNode: "7-s2" },
    "7-s1-symbols-key": { id: "7-s1-symbols-key", type: "narrative", text: "The Key manages access to everything. Properties. Accounts. People. Every new member of The Board's network is vetted by The Key. Every transaction approved. They're the gatekeeper - nothing happens without their knowledge.", nextNode: "7-s2" },
    "7-s1-symbols-mirror": { id: "7-s1-symbols-mirror", type: "narrative", text: "The Mirror runs intelligence. They know everything about everyone. Corporate espionage. Government surveillance. Social media manipulation. If The Board has blackmail material, The Mirror collected it. They've been watching you since the island raid.", nextNode: "7-s2", document: { title: "MIRROR_INTEL.pdf", preview: "Surveillance network identified. Extensive reach...", pdfUrl: "/documents/mirror-intel.pdf" } },
    "7-s1-location": {
      id: "7-s1-location",
      type: "choice",
      text: "The Gathering happens in eighteen days. Location encrypted in Ashford's files. Chen's team works the cipher while you chase other leads. Finally, a breakthrough: coordinates pointing to a private island - not overseas, but in the Chesapeake Bay. Three hours from Washington. Hidden in plain sight.",
      question: "What do you learn about the location?",
      timerSeconds: 20,
      choices: [
        { id: 'a', text: "Ownership records", nextNode: "7-s1-location-ownership", consequence: "Who owns it?" },
        { id: 'b', text: "Security arrangements", nextNode: "7-s1-location-security", consequence: "How is it protected?" },
        { id: 'c', text: "Historical usage", nextNode: "7-s1-location-history", consequence: "What's happened there before?" },
        { id: 'd', text: "Access points", nextNode: "7-s1-location-access", consequence: "How do we get in?" },
      ],
    },
    "7-s1-location-ownership": { id: "7-s1-location-ownership", type: "narrative", text: "The island is owned by a trust dating back to 1952. The trust is managed by a law firm that no longer exists. Every trail leads to dead ends and shell companies. But satellite imagery shows recent construction - a compound built within the last five years. Someone is using it.", nextNode: "7-s2", document: { title: "PROPERTY_RECORDS.pdf", preview: "Ownership obscured. Recent construction identified...", pdfUrl: "/documents/property-records.pdf" } },
    "7-s1-location-security": { id: "7-s1-location-security", type: "narrative", text: "Thermal imaging shows a security presence year-round. Motion sensors. Cameras. Patrol boats. During The Gathering, security will triple. Getting in without an invitation will be nearly impossible. But 'nearly impossible' isn't 'impossible.'", nextNode: "7-s2" },
    "7-s1-location-history": { id: "7-s1-location-history", type: "narrative", text: "Coast Guard records show unusual boat traffic around the island every August for the past thirty years. Always the same week. Always private vessels. Local fishermen call it 'the rich people's party.' They have no idea what really happens there.", nextNode: "7-s2" },
    "7-s1-location-access": { id: "7-s1-location-access", type: "narrative", text: "One dock. One helipad. One access road to the mainland via a private bridge. Three points of entry, all heavily monitored. But the island has caves - natural formations along the eastern shore. Not on any map. Potentially unguarded.", nextNode: "7-s2", document: { title: "ISLAND_SURVEY.pdf", preview: "Access points identified. Cave system noted...", pdfUrl: "/documents/island-survey.pdf" } },

    // ========== STAGE 2: THE PLAN ==========
    "7-s2": {
      id: "7-s2",
      type: "choice",
      text: "Sixteen days until The Gathering. You have a location, but not enough evidence for warrants - the judges who would sign them might be compromised. Chen assembles the Clean Hands team. 'We can't go in officially. But we can't let this happen either.' The room is silent. Everyone knows what she's suggesting.",
      question: "STAGE 2/5 — What's the plan?",
      timerSeconds: 20,
      choices: [
        { id: 'a', text: "Infiltrate The Gathering undercover", nextNode: "7-s2-infiltrate", consequence: "Get inside..." },
        { id: 'b', text: "Plant surveillance and gather evidence", nextNode: "7-s2-surveillance", consequence: "Document everything..." },
        { id: 'c', text: "Identify and flip an attendee", nextNode: "7-s2-flip", consequence: "Inside help..." },
        { id: 'd', text: "Coordinate a raid despite the risks", nextNode: "7-s2-raid", consequence: "Direct action..." },
      ],
    },
    "7-s2-infiltrate": {
      id: "7-s2-infiltrate",
      type: "choice",
      text: "'We need someone inside.' Chen pulls up files. 'Ashford's arrest created a vacancy. The Board needs a new American representative. If we can insert someone...' 'They'll be walking into a room full of monsters with no backup.' 'Yes. They will.'",
      question: "Who goes undercover?",
      timerSeconds: 20,
      choices: [
        { id: 'a', text: "An FBI agent with undercover experience", nextNode: "7-s2-infiltrate-agent", consequence: "Trained professional..." },
        { id: 'b', text: "The whistleblower - she knows the world", nextNode: "7-s2-infiltrate-kane", consequence: "She can blend in..." },
        { id: 'c', text: "You volunteer yourself", nextNode: "7-s2-infiltrate-cole", consequence: "You've come this far..." },
        { id: 'd', text: "Create a fictional persona from scratch", nextNode: "7-s2-infiltrate-fiction", consequence: "Build a legend..." },
      ],
    },
    "7-s2-infiltrate-agent": { id: "7-s2-infiltrate-agent", type: "narrative", text: "Agent Sarah Torres. Ten years undercover with cartels and organized crime. 'I've played worse roles,' she says, reviewing the files. 'Rich sociopath isn't a stretch.' She'll need a cover story, financial backing, and an introduction. You have two weeks to build her a new identity.", nextNode: "7-s3", document: { title: "TORRES_LEGEND.pdf", preview: "Undercover identity established. Cover story built...", pdfUrl: "/documents/torres-legend.pdf" } },
    "7-s2-infiltrate-kane": { id: "7-s2-infiltrate-kane", type: "narrative", text: "Elizabeth Kane already knows how they think, how they talk, how they operate. 'I spent three years in their world. I can get back in.' 'It's dangerous.' 'So is letting them continue.' She's right. And she's motivated. You start building her cover story.", nextNode: "7-s3" },
    "7-s2-infiltrate-cole": { id: "7-s2-infiltrate-cole", type: "narrative", text: "'I'll go.' Chen stares at you. 'Cole, you're a cop. They'll make you in five minutes.' 'Not if I go as something else. A corrupt cop looking to profit. They've tried to buy me before.' It's insane. It might work. Chen slowly nods.", nextNode: "7-s3" },
    "7-s2-infiltrate-fiction": { id: "7-s2-infiltrate-fiction", type: "narrative", text: "You build a person from scratch. Heir to a tech fortune. Discrete tastes. Known to certain circles but never photographed. Bank accounts established, social media backstopped, references planted. In two weeks, 'Alexander Crane' will exist - complete with a disturbing reputation that will intrigue The Board.", nextNode: "7-s3", document: { title: "CRANE_IDENTITY.pdf", preview: "Fictional identity created. Digital footprint established...", pdfUrl: "/documents/crane-identity.pdf" } },
    "7-s2-surveillance": {
      id: "7-s2-surveillance",
      type: "choice",
      text: "'If we can't go in, we watch from outside. Drones. Parabolic microphones. Thermal imaging. We document everyone who arrives, everything we can capture.' Chen spreads satellite photos across the table. 'It's not enough to stop them, but it might be enough to identify them.'",
      question: "What surveillance do you prioritize?",
      timerSeconds: 20,
      choices: [
        { id: 'a', text: "Facial recognition on arrivals", nextNode: "7-s2-surveillance-faces", consequence: "Name them all..." },
        { id: 'b', text: "Communication intercepts", nextNode: "7-s2-surveillance-comms", consequence: "Hear what they say..." },
        { id: 'c', text: "Financial tracking on all attendees", nextNode: "7-s2-surveillance-money", consequence: "Follow their money..." },
        { id: 'd', text: "Plant devices in advance", nextNode: "7-s2-surveillance-plant", consequence: "Eyes inside..." },
      ],
    },
    "7-s2-surveillance-faces": { id: "7-s2-surveillance-faces", type: "narrative", text: "High-resolution cameras positioned on the mainland, aimed at the dock and helipad. Every face that arrives will be captured, run through databases worldwide. By the time The Gathering ends, you'll know exactly who The Board really is.", nextNode: "7-s3" },
    "7-s2-surveillance-comms": { id: "7-s2-surveillance-comms", type: "narrative", text: "The island has its own cell tower - they don't trust public networks. But you can intercept the signal with the right equipment. 'We'll hear everything,' the tech specialist promises. 'Every call, every message.' Evidence that can bring them all down.", nextNode: "7-s3", document: { title: "COMMS_INTERCEPT.pdf", preview: "Communication monitoring established...", pdfUrl: "/documents/comms-intercept.pdf" } },
    "7-s2-surveillance-money": { id: "7-s2-surveillance-money", type: "narrative", text: "Every attendee will have financial records. Bank accounts, wire transfers, cryptocurrency wallets. You coordinate with international partners to track money movement during The Gathering. When they make transactions, you'll see them in real time.", nextNode: "7-s3" },
    "7-s2-surveillance-plant": { id: "7-s2-surveillance-plant", type: "narrative", text: "A week before The Gathering, a 'maintenance crew' visits the island to check the generators. They're actually Clean Hands agents. They plant listening devices, hidden cameras, GPS trackers. When The Board meets, you'll be in the room with them - virtually.", nextNode: "7-s3", document: { title: "DEVICE_PLACEMENT.pdf", preview: "Surveillance devices planted. Coverage confirmed...", pdfUrl: "/documents/device-placement.pdf" } },
    "7-s2-flip": {
      id: "7-s2-flip",
      type: "choice",
      text: "'Someone on the guest list might be willing to help.' Chen pulls up profiles. 'We've identified forty-seven likely attendees. Most are true believers. But some might be coerced. Blackmailed into participation. If we can find them...'",
      question: "Who do you approach?",
      timerSeconds: 20,
      choices: [
        { id: 'a', text: "A tech CEO with a troubled conscience", nextNode: "7-s2-flip-ceo", consequence: "He's been quiet lately..." },
        { id: 'b', text: "A diplomat being blackmailed", nextNode: "7-s2-flip-diplomat", consequence: "They have leverage on him..." },
        { id: 'c', text: "A security contractor who knows too much", nextNode: "7-s2-flip-contractor", consequence: "He's seen everything..." },
        { id: 'd', text: "A family member of a Board member", nextNode: "7-s2-flip-family", consequence: "Blood might not be thicker..." },
      ],
    },
    "7-s2-flip-ceo": { id: "7-s2-flip-ceo", type: "narrative", text: "Marcus Webb. Tech billionaire. Attended three previous Gatherings. But his behavior changed after the last one - donated to trafficking charities, quietly funded survivor organizations. Something broke in him. Maybe he's looking for a way out.", nextNode: "7-s3", document: { title: "WEBB_PROFILE.pdf", preview: "Potential ally identified. Approach strategy developed...", pdfUrl: "/documents/webb-profile.pdf" } },
    "7-s2-flip-diplomat": { id: "7-s2-flip-diplomat", type: "narrative", text: "Ambassador Reginald Cross. The Board has photos of him from a Gathering five years ago. He's been their puppet ever since - blocking investigations, providing diplomatic cover. But he's terrified, not devoted. Offer him protection, and he might flip.", nextNode: "7-s3" },
    "7-s2-flip-contractor": { id: "7-s2-flip-contractor", type: "narrative", text: "James Mercer - Ashford's former head of security, now working directly for The Board. He knows the island layout, security protocols, emergency procedures. If you can turn him, you'll have a blueprint for taking them down.", nextNode: "7-s3" },
    "7-s2-flip-family": { id: "7-s2-flip-family", type: "narrative", text: "Eleanor Ashford. Victor's daughter. She testified against her own father. 'I won't let the family name be synonymous with monsters.' She doesn't know about The Board - but she has access to her father's remaining contacts. And she wants to help.", nextNode: "7-s3", document: { title: "ELEANOR_CONTACT.pdf", preview: "Ashford daughter willing to assist...", pdfUrl: "/documents/eleanor-contact.pdf" } },
    "7-s2-raid": {
      id: "7-s2-raid",
      type: "choice",
      text: "'We go in during The Gathering. All of them in one place. We hit them with everything.' It's risky. Legally questionable. Potentially career-ending for everyone involved. But if it works, you take down the entire conspiracy in one night.",
      question: "How do you plan the raid?",
      timerSeconds: 20,
      choices: [
        { id: 'a', text: "Coordinate with military assets", nextNode: "7-s2-raid-military", consequence: "Overwhelming force..." },
        { id: 'b', text: "Small team, surgical strike", nextNode: "7-s2-raid-surgical", consequence: "Speed and precision..." },
        { id: 'c', text: "Wait for them to commit crimes, then move", nextNode: "7-s2-raid-wait", consequence: "Catch them in the act..." },
        { id: 'd', text: "Create a diversion to draw out security", nextNode: "7-s2-raid-diversion", consequence: "Divide and conquer..." },
      ],
    },
    "7-s2-raid-military": { id: "7-s2-raid-military", type: "narrative", text: "You reach out to contacts at JSOC. Off the books. 'If we can prove national security implications...' 'Trafficking of US citizens. Corruption of government officials. Compromise of intelligence assets.' 'That might be enough.' Helicopters, operators, the works. This ends with a bang.", nextNode: "7-s3", document: { title: "MILITARY_COORDINATION.pdf", preview: "Special operations support confirmed...", pdfUrl: "/documents/military-coordination.pdf" } },
    "7-s2-raid-surgical": { id: "7-s2-raid-surgical", type: "narrative", text: "Twelve agents. Three boats. One chance. You'll hit the island from the caves on the eastern shore, move through the compound, secure evidence, and extract before security can respond. It's dangerous. It's necessary.", nextNode: "7-s3" },
    "7-s2-raid-wait": { id: "7-s2-raid-wait", type: "narrative", text: "Position teams nearby. Watch and wait. The moment they begin the auction - the moment money changes hands and people are sold - you move. Caught in the act. No lawyers can explain that away. The evidence will be undeniable.", nextNode: "7-s3" },
    "7-s2-raid-diversion": { id: "7-s2-raid-diversion", type: "narrative", text: "A fire on the mainland. Coast Guard emergency. Something to draw the patrol boats away from the island. While security responds, your team goes in the back door. By the time they realize it's a diversion, you'll already have The Board in custody.", nextNode: "7-s3", document: { title: "DIVERSION_PLAN.pdf", preview: "Multi-stage operation planned...", pdfUrl: "/documents/diversion-plan.pdf" } },

    // ========== STAGE 3: THE APPROACH ==========
    "7-s3": {
      id: "7-s3",
      type: "choice",
      text: "Seven days until The Gathering. Your plan is in motion. Teams are positioned. Surveillance is active. But The Mirror - The Board's intelligence arm - is watching too. You get a message on your personal phone, from a blocked number: 'We know what you're planning. Walk away now. This is your only warning.'",
      question: "STAGE 3/5 — How do you respond to the threat?",
      timerSeconds: 20,
      choices: [
        { id: 'a', text: "Ignore it - stay the course", nextNode: "7-s3-ignore", consequence: "Don't show weakness..." },
        { id: 'b', text: "Trace the message source", nextNode: "7-s3-trace", consequence: "Find them first..." },
        { id: 'c', text: "Use it as evidence of conspiracy", nextNode: "7-s3-evidence", consequence: "They've made a mistake..." },
        { id: 'd', text: "Send a message back", nextNode: "7-s3-reply", consequence: "Let them know you're coming..." },
      ],
    },
    "7-s3-ignore": {
      id: "7-s3-ignore",
      type: "choice",
      text: "You delete the message. Tell no one. Fear is their weapon - you won't give them the satisfaction. But you do tighten security on your team, vary your routines, check for surveillance more carefully. They're watching. Now you're watching back.",
      question: "What security measures do you take?",
      timerSeconds: 20,
      choices: [
        { id: 'a', text: "Move to a secure location", nextNode: "7-s3-ignore-move", consequence: "New base of operations..." },
        { id: 'b', text: "Sweep for bugs and tracking", nextNode: "7-s3-ignore-sweep", consequence: "Make sure you're clean..." },
        { id: 'c', text: "Set up counter-surveillance", nextNode: "7-s3-ignore-counter", consequence: "Watch the watchers..." },
        { id: 'd', text: "Accelerate the timeline", nextNode: "7-s3-ignore-accelerate", consequence: "Move before they can react..." },
      ],
    },
    "7-s3-ignore-move": { id: "7-s3-ignore-move", type: "narrative", text: "You relocate to a Clean Hands safe house - an abandoned warehouse converted to a command center. New phones. New vehicles. Complete communication blackout with official channels. From now until The Gathering, you're ghosts.", nextNode: "7-s4" },
    "7-s3-ignore-sweep": { id: "7-s3-ignore-sweep", type: "narrative", text: "A full sweep of every team member's home, vehicle, and phone. You find three tracking devices and one listening bug. They've been monitoring you for weeks. Now they're deaf and blind to your movements.", nextNode: "7-s4", document: { title: "SWEEP_RESULTS.pdf", preview: "Multiple surveillance devices found and disabled...", pdfUrl: "/documents/sweep-results.pdf" } },
    "7-s3-ignore-counter": { id: "7-s3-ignore-counter", type: "narrative", text: "If they're watching you, you can watch them watching you. Track the surveillance teams back to their handlers. Identify The Mirror's local assets. By the time of The Gathering, you'll know exactly how they operate - and how to blind them.", nextNode: "7-s4" },
    "7-s3-ignore-accelerate": { id: "7-s3-ignore-accelerate", type: "narrative", text: "They expect you to wait for The Gathering. So you don't. You move the timeline up by 48 hours - hit them while they're still preparing. They'll have security, but not full security. It's a risk. But surprise is worth more than numbers.", nextNode: "7-s4" },
    "7-s3-trace": {
      id: "7-s3-trace",
      type: "choice",
      text: "You forward the message to your tech specialists. 'Find them.' Two hours later, they have a partial trace - the message bounced through six countries, but originated from a server in Northern Virginia. Close. Very close.",
      question: "What do you do with this information?",
      timerSeconds: 20,
      choices: [
        { id: 'a', text: "Raid the server location", nextNode: "7-s3-trace-raid", consequence: "Direct action..." },
        { id: 'b', text: "Set up surveillance on the site", nextNode: "7-s3-trace-watch", consequence: "See who visits..." },
        { id: 'c', text: "Feed them false information", nextNode: "7-s3-trace-false", consequence: "Misdirection..." },
        { id: 'd', text: "Use it to identify The Mirror", nextNode: "7-s3-trace-mirror", consequence: "Unmask the watcher..." },
      ],
    },
    "7-s3-trace-raid": { id: "7-s3-trace-raid", type: "narrative", text: "You hit the server farm at 3 AM. Private security - corporate, not Board - doesn't resist when FBI badges come out. Inside, you find a monitoring station with feeds from dozens of locations. They've been watching law enforcement nationwide. And now you have their entire network mapped.", nextNode: "7-s4", document: { title: "SERVER_SEIZURE.pdf", preview: "Surveillance network exposed. Monitoring assets identified...", pdfUrl: "/documents/server-seizure.pdf" } },
    "7-s3-trace-watch": { id: "7-s3-trace-watch", type: "narrative", text: "A team sets up across the street. Within 24 hours, you've photographed six individuals accessing the building - three you recognize from Ashford's files. The Mirror isn't just watching you. They're coordinating all of The Board's intelligence operations from this site.", nextNode: "7-s4" },
    "7-s3-trace-false": { id: "7-s3-trace-false", type: "narrative", text: "You let them intercept 'plans' showing a raid two days after The Gathering actually begins. False coordinates. Wrong team assignments. When they prepare for a threat that isn't coming, you'll hit them where they don't expect.", nextNode: "7-s4" },
    "7-s3-trace-mirror": { id: "7-s3-trace-mirror", type: "narrative", text: "The server is registered to a shell company owned by a shell company owned by... a former NSA deputy director. Theodore Marsh. Retired in 2015 after 30 years in signals intelligence. The Mirror has a name. And a home address.", nextNode: "7-s4", document: { title: "MIRROR_IDENTIFIED.pdf", preview: "The Mirror unmasked. Theodore Marsh, former NSA...", pdfUrl: "/documents/mirror-identified.pdf" } },
    "7-s3-evidence": {
      id: "7-s3-evidence",
      type: "choice",
      text: "'They just admitted they're conspiring against a federal investigation.' Chen's eyes light up. 'That's obstruction. Maybe witness intimidation. We can use this.' The message is leverage - proof that The Board knows you're coming and is trying to stop you.",
      question: "How do you use this evidence?",
      timerSeconds: 20,
      choices: [
        { id: 'a', text: "Take it to a trusted judge for warrants", nextNode: "7-s3-evidence-judge", consequence: "Legal ammunition..." },
        { id: 'b', text: "Share it with international partners", nextNode: "7-s3-evidence-international", consequence: "Build the coalition..." },
        { id: 'c', text: "Leak it to the press as insurance", nextNode: "7-s3-evidence-press", consequence: "Public exposure..." },
        { id: 'd', text: "Add it to the case file and continue", nextNode: "7-s3-evidence-file", consequence: "More evidence for trial..." },
      ],
    },
    "7-s3-evidence-judge": { id: "7-s3-evidence-judge", type: "narrative", text: "Judge Patricia Reyes. Twenty years on the federal bench. Incorruptible - you've checked. She reviews the message, the trace data, the connection to ongoing investigations. 'This is sufficient for surveillance warrants. Possibly search warrants depending on what you find.' The legal path just opened up.", nextNode: "7-s4", document: { title: "WARRANT_APPROVAL.pdf", preview: "Judicial authorization obtained. Operations approved...", pdfUrl: "/documents/warrant-approval.pdf" } },
    "7-s3-evidence-international": { id: "7-s3-evidence-international", type: "narrative", text: "Interpol. MI6. BKA. DGSI. Each receives a copy of the threat and your response. 'This is bigger than one country. We need coordinated action.' They agree. When The Gathering happens, law enforcement from five nations will be ready to move.", nextNode: "7-s4" },
    "7-s3-evidence-press": { id: "7-s3-evidence-press", type: "narrative", text: "Three journalists receive encrypted copies of everything - the threat, the trace, the connection to the investigation. 'If something happens to us, publish everything.' It's insurance. The Board can silence individuals. They can't silence a coordinated media release.", nextNode: "7-s4" },
    "7-s3-evidence-file": { id: "7-s3-evidence-file", type: "narrative", text: "You log the threat, document the trace, and add it to the growing case file. Another piece of evidence. Another nail in the coffin. By the time this reaches trial, the conspiracy will be undeniable.", nextNode: "7-s4" },
    "7-s3-reply": {
      id: "7-s3-reply",
      type: "choice",
      text: "You type a response: 'I'm coming for all of you.' Send. Let them know you're not afraid. Let them prepare. It won't matter. Within minutes, a reply: 'Then you'll die with them.'",
      question: "How do you interpret this response?",
      timerSeconds: 20,
      choices: [
        { id: 'a', text: "They're planning to destroy evidence", nextNode: "7-s3-reply-destroy", consequence: "Scorched earth..." },
        { id: 'b', text: "They'll sacrifice The Board to escape", nextNode: "7-s3-reply-sacrifice", consequence: "Someone higher..." },
        { id: 'c', text: "It's a trap at The Gathering", nextNode: "7-s3-reply-trap", consequence: "They're waiting for you..." },
        { id: 'd', text: "They're threatening your team", nextNode: "7-s3-reply-threat", consequence: "Protect your people..." },
      ],
    },
    "7-s3-reply-destroy": { id: "7-s3-reply-destroy", type: "narrative", text: "'Die with them.' They'll burn it all before they let you win. The island. The evidence. Maybe even The Board members themselves. You need to move faster than their destruction protocols. Get there before they can erase everything.", nextNode: "7-s4" },
    "7-s3-reply-sacrifice": { id: "7-s3-reply-sacrifice", type: "narrative", text: "There's someone above The Board. Someone willing to sacrifice seven powerful people to protect themselves. The conspiracy goes even deeper than you thought. The Gathering isn't the end - it's another layer to peel back.", nextNode: "7-s4", document: { title: "HIERARCHY_ANALYSIS.pdf", preview: "Evidence of additional authority above The Board...", pdfUrl: "/documents/hierarchy-analysis.pdf" } },
    "7-s3-reply-trap": { id: "7-s3-reply-trap", type: "narrative", text: "They know you're coming. They're preparing for you. The Gathering might be bait - draw in law enforcement, then eliminate them. You'll need to be smarter. Hit them where they don't expect, when they don't expect.", nextNode: "7-s4" },
    "7-s3-reply-threat": { id: "7-s3-reply-threat", type: "narrative", text: "'Die with them.' A threat against your team. You immediately order enhanced security on everyone - families too. If The Board can't stop the investigation, they'll try to stop the investigators. You won't let them.", nextNode: "7-s4", document: { title: "TEAM_SECURITY.pdf", preview: "Enhanced protection protocols activated...", pdfUrl: "/documents/team-security.pdf" } },

    // ========== STAGE 4: THE EXECUTION ==========
    "7-s4": {
      id: "7-s4",
      type: "choice",
      text: "The night of The Gathering. Private jets have been landing all day. Yachts dot the water. Security patrols have tripled. Inside the compound, forty-seven of the world's most powerful criminals are preparing for an evening of unimaginable depravity. Your teams are in position. Everything you've worked for comes down to the next few hours.",
      question: "STAGE 4/5 — How do you begin the operation?",
      timerSeconds: 20,
      choices: [
        { id: 'a', text: "Wait for the auction to begin", nextNode: "7-s4-wait", consequence: "Catch them in the act..." },
        { id: 'b', text: "Move now while they're arriving", nextNode: "7-s4-now", consequence: "Chaos is opportunity..." },
        { id: 'c', text: "Disable communications first", nextNode: "7-s4-comms", consequence: "Isolate them..." },
        { id: 'd', text: "Strike from multiple directions simultaneously", nextNode: "7-s4-multi", consequence: "Overwhelming force..." },
      ],
    },
    "7-s4-wait": {
      id: "7-s4-wait",
      type: "choice",
      text: "You wait. Watch the feeds from the planted devices. The guests mingle. Drinks. Small talk. Then The Crown calls them to order. The auction begins. First item: a teenage girl from Eastern Europe. Bidding starts at $500,000.",
      question: "When do you move?",
      timerSeconds: 20,
      choices: [
        { id: 'a', text: "Now - you've seen enough", nextNode: "7-s4-wait-now", consequence: "Stop this..." },
        { id: 'b', text: "Wait for the transaction to complete", nextNode: "7-s4-wait-complete", consequence: "Undeniable evidence..." },
        { id: 'c', text: "Record everything first", nextNode: "7-s4-wait-record", consequence: "Documentation..." },
        { id: 'd', text: "Identify the buyers before moving", nextNode: "7-s4-wait-buyers", consequence: "Get them all..." },
      ],
    },
    "7-s4-wait-now": { id: "7-s4-wait-now", type: "narrative", text: "'All teams, move.' The raid begins. Boats hit the dock. Agents pour through the caves. Helicopters appear overhead. Inside the compound, screams and chaos as the most powerful people in the world realize they're trapped. The Gathering is over.", nextNode: "7-s5" },
    "7-s4-wait-complete": { id: "7-s4-wait-complete", type: "narrative", text: "You watch, sick to your stomach, as $2.3 million changes hands for a human being. But now you have it - recorded, documented, undeniable. 'All teams, move.' The raid captures not just attendees, but evidence of completed transactions.", nextNode: "7-s5", document: { title: "TRANSACTION_RECORD.pdf", preview: "Auction documented. Multiple transactions recorded...", pdfUrl: "/documents/transaction-record.pdf" } },
    "7-s4-wait-record": { id: "7-s4-wait-record", type: "narrative", text: "Ten minutes of recording. Forty-seven faces clearly visible. Bids placed. Hands raised. Every person in that room is complicit, and you have the proof. Then you give the order. 'Move.'", nextNode: "7-s5" },
    "7-s4-wait-buyers": { id: "7-s4-wait-buyers", type: "narrative", text: "You identify every bidder. Match them to faces, to financial records, to the network you've been building. When the raid happens, you don't just arrest the attendees - you know exactly what each one was there to buy.", nextNode: "7-s5" },
    "7-s4-now": {
      id: "7-s4-now",
      type: "choice",
      text: "No waiting. You hit them during arrivals, when security is spread thin and guests are unprepared. Boats converge from three directions. Helicopters cut off air escape. The panic is immediate.",
      question: "What's your first priority?",
      timerSeconds: 20,
      choices: [
        { id: 'a', text: "Secure The Board members", nextNode: "7-s4-now-board", consequence: "Get the leaders..." },
        { id: 'b', text: "Find and protect the victims", nextNode: "7-s4-now-victims", consequence: "Save them..." },
        { id: 'c', text: "Seize evidence before destruction", nextNode: "7-s4-now-evidence", consequence: "Preserve the proof..." },
        { id: 'd', text: "Lock down all exits", nextNode: "7-s4-now-exits", consequence: "No one escapes..." },
      ],
    },
    "7-s4-now-board": { id: "7-s4-now-board", type: "narrative", text: "You have photos of each Board member. Crown, Sword, Scale, Serpent, Tower, Key, Mirror. Teams are assigned to each one. Within twenty minutes, six of seven are in custody. The Mirror - Theodore Marsh - is found in a panic room. He surrenders without a fight.", nextNode: "7-s5", document: { title: "BOARD_CUSTODY.pdf", preview: "All seven Board members secured...", pdfUrl: "/documents/board-custody.pdf" } },
    "7-s4-now-victims": { id: "7-s4-now-victims", type: "narrative", text: "The victims are held in a underground section of the compound. Twenty-three people, sedated and prepared for auction. Your team reaches them before any harm can come. They're scared, confused, but alive. You keep your promise.", nextNode: "7-s5" },
    "7-s4-now-evidence": { id: "7-s4-now-evidence", type: "narrative", text: "Tech teams secure the servers before the kill switch can be triggered. Physical documents are preserved. Recording devices capture everything. The evidence is overwhelming - thirty years of conspiracy, documented and protected.", nextNode: "7-s5" },
    "7-s4-now-exits": { id: "7-s4-now-exits", type: "narrative", text: "Coast Guard blocks the water. Helicopters control the air. The bridge to the mainland is barricaded. For the first time in their lives, the most powerful people in the world have nowhere to run. Tonight, they answer for their crimes.", nextNode: "7-s5" },
    "7-s4-comms": {
      id: "7-s4-comms",
      type: "choice",
      text: "You hit their communications first. Jammers activate. Cell tower disabled. Satellite links cut. The island goes dark. No calls for help. No warnings to allies. For the next hour, these people are alone.",
      question: "How do they react to the blackout?",
      timerSeconds: 20,
      choices: [
        { id: 'a', text: "Panic and confusion", nextNode: "7-s4-comms-panic", consequence: "They're afraid..." },
        { id: 'b', text: "Security protocols activate", nextNode: "7-s4-comms-security", consequence: "They're prepared..." },
        { id: 'c', text: "Attempt to flee immediately", nextNode: "7-s4-comms-flee", consequence: "Rats leaving..." },
        { id: 'd', text: "Evidence destruction begins", nextNode: "7-s4-comms-destroy", consequence: "Burning it all..." },
      ],
    },
    "7-s4-comms-panic": { id: "7-s4-comms-panic", type: "narrative", text: "They've never been cut off before. Never been vulnerable. The panic spreads fast - guests demanding explanations, security scrambling, Board members retreating to safe rooms. Into this chaos, your teams move like ghosts.", nextNode: "7-s5" },
    "7-s4-comms-security": { id: "7-s4-comms-security", type: "narrative", text: "Professional. Protocols for exactly this scenario. But your undercover asset fed you those protocols weeks ago. Every move they make, you anticipated. When security retreats to defensive positions, they find your people already waiting.", nextNode: "7-s5", document: { title: "SECURITY_OVERRIDE.pdf", preview: "Protocols countered. Security neutralized...", pdfUrl: "/documents/security-override.pdf" } },
    "7-s4-comms-flee": { id: "7-s4-comms-flee", type: "narrative", text: "Boats start their engines. Helicopters spin up. But the water is full of Coast Guard cutters, and F-16s are orbiting overhead. Nobody leaves. For once, wealth and power don't provide an escape route.", nextNode: "7-s5" },
    "7-s4-comms-destroy": { id: "7-s4-comms-destroy", type: "narrative", text: "Fires start in the document room. Servers begin wiping. But your tech team prepared for this - remote access established days ago. They lock down the systems before destruction can complete. The evidence survives.", nextNode: "7-s5" },
    "7-s4-multi": {
      id: "7-s4-multi",
      type: "choice",
      text: "Simultaneous strikes from land, sea, and air. Three teams, three entry points, one objective. The compound is overwhelmed before anyone can organize resistance. It's surgical. It's decisive. It's over in fifteen minutes.",
      question: "What do you find inside?",
      timerSeconds: 20,
      choices: [
        { id: 'a', text: "The Board in session", nextNode: "7-s4-multi-session", consequence: "All together..." },
        { id: 'b', text: "Evidence rooms full of documentation", nextNode: "7-s4-multi-docs", consequence: "Everything they kept..." },
        { id: 'c', text: "Victims prepared for auction", nextNode: "7-s4-multi-victims", consequence: "They're still here..." },
        { id: 'd', text: "All of the above", nextNode: "7-s4-multi-all", consequence: "Complete success..." },
      ],
    },
    "7-s4-multi-session": { id: "7-s4-multi-session", type: "narrative", text: "The Board sits around a circular table - seven chairs, seven symbols. When your team bursts in, they don't run. The Crown - an elderly woman with cold eyes - simply says, 'You have no idea what you've done.' You have some idea. And you don't care.", nextNode: "7-s5", document: { title: "BOARD_CAPTURE.pdf", preview: "Board meeting interrupted. All members secured...", pdfUrl: "/documents/board-capture.pdf" } },
    "7-s4-multi-docs": { id: "7-s4-multi-docs", type: "narrative", text: "Thirty years of records. Financial transactions. Member lists. Meeting minutes. Photographs. Videos. They kept everything - arrogance or insurance, you're not sure. But now it's evidence. Enough to bring down hundreds of people worldwide.", nextNode: "7-s5" },
    "7-s4-multi-victims": { id: "7-s4-multi-victims", type: "narrative", text: "They're in cells beneath the main building. Twenty-three people who were about to be sold. Your teams reach them first. Medical personnel standing by. Trauma counselors ready. They're going home. All of them.", nextNode: "7-s5" },
    "7-s4-multi-all": { id: "7-s4-multi-all", type: "narrative", text: "Everything. Everyone. The Board in custody. The victims rescued. The evidence preserved. It's the most successful operation in FBI history - and almost no one will ever know the full scope of what was stopped tonight.", nextNode: "7-s5" },

    // ========== STAGE 5: THE AFTERMATH ==========
    "7-s5": {
      id: "7-s5",
      type: "choice",
      text: "Dawn breaks over the Chesapeake. Forty-seven arrests. Twenty-three victims recovered. The Board of the most powerful criminal conspiracy in modern history sits in federal custody. But as you process the scene, Chen approaches with a grim expression. 'Cole. We found something. You need to see this.'",
      question: "STAGE 5/5 — What did they find?",
      timerSeconds: 20,
      choices: [
        { id: 'a', text: "Evidence of government involvement at the highest level", nextNode: "7-s5-government", consequence: "How high does this go?" },
        { id: 'b', text: "A list of future targets - more victims planned", nextNode: "7-s5-targets", consequence: "It's not over..." },
        { id: 'c', text: "Records connecting to operations worldwide", nextNode: "7-s5-worldwide", consequence: "Global network..." },
        { id: 'd', text: "A message specifically for you", nextNode: "7-s5-message", consequence: "They expected you..." },
      ],
    },
    "7-s5-government": { id: "7-s5-government", type: "narrative", text: "Documents with White House letterhead. Communications from the intelligence community. 'The protection wasn't just from judges and cops,' Chen says quietly. 'This goes to the very top.' You stare at the papers. Some battles can't be won with arrests.", nextNode: "7-complete" },
    "7-s5-targets": { id: "7-s5-targets", type: "narrative", text: "A list of names. Addresses. Photographs. Dozens of people selected as future victims - some already under surveillance. 'They were planning years ahead,' Chen says. 'We stopped one auction. This list shows they never intended to stop.'", nextNode: "7-complete", document: { title: "FUTURE_TARGETS.pdf", preview: "Victim pipeline identified. Prevention operations needed...", pdfUrl: "/documents/future-targets.pdf" } },
    "7-s5-worldwide": { id: "7-s5-worldwide", type: "narrative", text: "The Board was just the American chapter. Similar organizations in Europe, Asia, South America. They share resources, trade victims, protect each other. 'We took down one head,' Chen says. 'The hydra has others.'", nextNode: "7-complete" },
    "7-s5-message": { id: "7-s5-message", type: "narrative", text: "A sealed envelope with your name on it. Inside, a single photograph - you, years ago, at your daughter's school play. A message written on the back: 'We've always known where to find what you love. Remember that.' The threat is clear. The war isn't over.", nextNode: "7-complete", document: { title: "PERSONAL_THREAT.pdf", preview: "Direct threat documented. Family protection priority...", pdfUrl: "/documents/personal-threat.pdf" } },

    // ========== CHAPTER 7 COMPLETE ==========
    "7-complete": {
      id: "7-complete",
      type: "chapter-end",
      text: "The Gathering is stopped. The Board is in custody. Forty-seven of the world's most powerful criminals will face justice. Twenty-three victims are free, beginning the long road to recovery. But as the sun rises over the Chesapeake, you understand: this was a battle, not the war. The conspiracy runs deeper than one organization, wider than one country. For every head you cut off, more remain. The trials will take years. The political fallout will reshape governments. And somewhere out there, the survivors of your raid are already planning their revenge. But today - today you won. Today, monsters face consequences. Today, victims are free. It's not enough. It's never enough. But it's something. You look at the sunrise and allow yourself one moment of satisfaction. Tomorrow, the work continues.",
      chapterComplete: {
        chapter: 7,
        nextChapter: 8,
        summary: "The Gathering is stopped. The Board is captured. But the conspiracy reveals connections to the highest levels of government and networks spanning the globe. The final chapter awaits."
      },
    },
  },
};