import { BranchingChapter } from '../types';

/**
 * CHAPTER 6: THE AFTERMATH - 5 Stages, full branching
 * CONTINUATION: After Morrison's conviction, the investigation expands.
 * PERSPECTIVE: Detective Marcus Cole follows the conspiracy deeper.
 * Harrison's testimony named names. The network is larger than anyone knew.
 * NO DEATH NODES - This is an investigation/revelation chapter
 */
export const CHAPTER_6: BranchingChapter = {
  id: 6,
  title: "CHAPTER 6",
  subtitle: "The Aftermath",
  startNode: "6-s1",
  nodes: {
    // ========== STAGE 1: THE EXPANSION ==========
    "6-s1": {
      id: "6-s1",
      type: "choice",
      text: "Three days since the verdict. Morrison is in federal custody awaiting sentencing - life, most likely. The media calls it justice. But you know the truth: Morrison was middle management. Harrison's testimony named twelve more names. Politicians. Business leaders. A retired general. Your captain wants you to take a break. 'You've earned it, Cole.' But Agent Chen calls. 'We need to talk. Somewhere private.'",
      question: "STAGE 1/5 — Where do you meet Agent Chen?",
      timerSeconds: 20,
      choices: [
        { id: 'a', text: "A coffee shop away from the office", nextNode: "6-s1-coffee", consequence: "Public but anonymous..." },
        { id: 'b', text: "Her car in a parking garage", nextNode: "6-s1-car", consequence: "Private conversation..." },
        { id: 'c', text: "A park bench - open air", nextNode: "6-s1-park", consequence: "No walls have ears..." },
        { id: 'd', text: "The FBI field office - official", nextNode: "6-s1-office", consequence: "On the record..." },
      ],
    },
    "6-s1-coffee": {
      id: "6-s1-coffee",
      type: "choice",
      text: "A diner in Northeast. Plastic booths, burnt coffee, no one who would recognize either of you. Chen slides a folder across the table. 'Harrison's been talking. Really talking. The names he gave us... we verified three already. Two are cooperating. One lawyered up.'",
      question: "What does Chen reveal?",
      timerSeconds: 20,
      choices: [
        { id: 'a', text: "The scope is international", nextNode: "6-s1-coffee-international", consequence: "Bigger than US..." },
        { id: 'b', text: "There are other locations", nextNode: "6-s1-coffee-locations", consequence: "More than one island..." },
        { id: 'c', text: "Someone high up is protecting them", nextNode: "6-s1-coffee-protection", consequence: "Powerful friends..." },
        { id: 'd', text: "They have a source inside the investigation", nextNode: "6-s1-coffee-source", consequence: "We're compromised..." },
      ],
    },
    "6-s1-coffee-international": { id: "6-s1-coffee-international", type: "narrative", text: "'The money flows through Cyprus, Caymans, and Singapore. But the clients - they came from everywhere. European politicians. Asian tech executives. Middle Eastern royalty.' She lowers her voice. 'This isn't an American problem. It's a global network.'", nextNode: "6-s2", document: { title: "INTERNATIONAL_SCOPE.pdf", preview: "Global network identified. Clients from 12+ countries...", pdfUrl: "/documents/international-scope.pdf" } },
    "6-s1-coffee-locations": { id: "6-s1-coffee-locations", type: "narrative", text: "'The island wasn't unique. Harrison mentioned at least two other locations. One in Southeast Asia. One in the Caribbean. Same operation, different geography. When we shut one down, they had backups.'", nextNode: "6-s2" },
    "6-s1-coffee-protection": { id: "6-s1-coffee-protection", type: "narrative", text: "'Someone at DOJ has been burying cases for years. Cases that got close to these names. Evidence that went missing. Witnesses who stopped cooperating.' She slides a name across the table. Deputy Attorney General Williams. 'We can't trust official channels.'", nextNode: "6-s2", document: { title: "DOJ_CORRUPTION.pdf", preview: "Internal DOJ protection. Deputy AG Williams flagged...", pdfUrl: "/documents/doj-corruption.pdf" } },
    "6-s1-coffee-source": { id: "6-s1-coffee-source", type: "narrative", text: "'Someone on the task force is feeding them information. Three operations we planned - all compromised. Targets moved before we arrived. Evidence destroyed before we got warrants.' She meets your eyes. 'We need to work off-book. Just us.'", nextNode: "6-s2" },
    "6-s1-car": {
      id: "6-s1-car",
      type: "choice",
      text: "Third level of a parking garage. Engine off, windows up. Chen's face is grim in the dashboard glow. 'Harrison gave us names. But more importantly, he gave us structure. This thing... it's not a criminal organization. It's a membership club. For people who think they're above the law.'",
      question: "What kind of structure?",
      timerSeconds: 20,
      choices: [
        { id: 'a', text: "Financial structure - how money moved", nextNode: "6-s1-car-financial", consequence: "Follow the money..." },
        { id: 'b', text: "Operational structure - how it ran", nextNode: "6-s1-car-operational", consequence: "The machine..." },
        { id: 'c', text: "Protection structure - how they stayed hidden", nextNode: "6-s1-car-protection", consequence: "The shield..." },
        { id: 'd', text: "Recruitment structure - how they found clients", nextNode: "6-s1-car-recruitment", consequence: "The network..." },
      ],
    },
    "6-s1-car-financial": { id: "6-s1-car-financial", type: "narrative", text: "'Shell companies nested inside shell companies. Payments disguised as consulting fees, charitable donations, art purchases. The accountants who set this up were good. But Harrison knew where to look.' She hands you a flash drive. 'Account numbers. Transaction records. Enough to trace $200 million.'", nextNode: "6-s2", document: { title: "FINANCIAL_STRUCTURE.pdf", preview: "$200M traced through shell companies. Complete transaction map...", pdfUrl: "/documents/financial-structure.pdf" } },
    "6-s1-car-operational": { id: "6-s1-car-operational", type: "narrative", text: "'The island had a management team. Security. Logistics. Medical staff. All compartmentalized - most of them didn't know the full picture. But Harrison did. He knew who gave the orders, who handled the money, who cleaned up problems.'", nextNode: "6-s2" },
    "6-s1-car-protection": { id: "6-s1-car-protection", type: "narrative", text: "'They had people everywhere. Law enforcement. Media. Politics. When investigations got close, they'd get shut down. Witnesses would recant. Evidence would disappear. Morrison wasn't the protection - he was just one customer. The real protectors are still in place.'", nextNode: "6-s2" },
    "6-s1-car-recruitment": { id: "6-s1-car-recruitment", type: "narrative", text: "'Private events. Charity galas. Business conferences. That's where they found clients. Wealthy, powerful people with certain... interests. Introduced carefully. Vetted thoroughly. By the time someone got an invitation to the island, they'd been evaluated for months.'", nextNode: "6-s2", document: { title: "RECRUITMENT_PATTERN.pdf", preview: "Client recruitment network. Event-based introduction system...", pdfUrl: "/documents/recruitment-pattern.pdf" } },
    "6-s1-park": {
      id: "6-s1-park",
      type: "choice",
      text: "Autumn leaves on the path. Joggers passing. Normal life continuing while you discuss monsters. 'I'm being watched,' Chen says, not looking at you. 'My emails flagged. My phone calls logged. Someone doesn't want this investigation to continue.'",
      question: "How do you respond?",
      timerSeconds: 20,
      choices: [
        { id: 'a', text: "We need to go public", nextNode: "6-s1-park-public", consequence: "Sunlight is disinfectant..." },
        { id: 'b', text: "We need to go underground", nextNode: "6-s1-park-underground", consequence: "Work in shadows..." },
        { id: 'c', text: "We need allies we can trust", nextNode: "6-s1-park-allies", consequence: "Find the clean ones..." },
        { id: 'd', text: "We need to accelerate", nextNode: "6-s1-park-accelerate", consequence: "Move before they do..." },
      ],
    },
    "6-s1-park-public": { id: "6-s1-park-public", type: "narrative", text: "'I know a journalist. Pulitzer winner. She's been tracking trafficking networks for years. If we give her enough to publish, they can't shut it down without looking guilty.' Chen nods slowly. 'Insurance policy. If something happens to us, the story gets told anyway.'", nextNode: "6-s2" },
    "6-s1-park-underground": { id: "6-s1-park-underground", type: "narrative", text: "'Burner phones. Cash only. Unofficial meetings. We work this like we're investigating the mob - because that's what this is. A mob with law degrees and political connections.' You've done this before, during the organized crime years. Time to remember those skills.", nextNode: "6-s2" },
    "6-s1-park-allies": { id: "6-s1-park-allies", type: "narrative", text: "'There's a group of us,' Chen says quietly. 'FBI agents who've seen too much get buried. We call ourselves the Clean Hands. Unofficial. Off the record. We share information, watch each other's backs.' She pauses. 'We've been waiting for a case like this.'", nextNode: "6-s2", document: { title: "CLEAN_HANDS.pdf", preview: "Internal FBI resistance network. Trusted agents identified...", pdfUrl: "/documents/clean-hands.pdf" } },
    "6-s1-park-accelerate": { id: "6-s1-park-accelerate", type: "narrative", text: "'If they're watching you, they know we're getting close. We need to move faster than they can react. What's our next target?' Chen pulls out a name. Tech billionaire Marcus Webb. 'Harrison says he was a regular. And unlike Morrison, he's not lawyered up yet.'", nextNode: "6-s2" },
    "6-s1-office": {
      id: "6-s1-office",
      type: "choice",
      text: "The FBI field office. Official. Recorded. Maybe that's the point. Chen leads you to a conference room where two other agents wait. 'Detective Cole, meet the task force. The real one. Not the version that's been compromised.'",
      question: "What's the task force's focus?",
      timerSeconds: 20,
      choices: [
        { id: 'a', text: "Identifying additional victims", nextNode: "6-s1-office-victims", consequence: "They deserve to be found..." },
        { id: 'b', text: "Building cases against named conspirators", nextNode: "6-s1-office-cases", consequence: "One by one..." },
        { id: 'c', text: "Mapping the complete network", nextNode: "6-s1-office-network", consequence: "See the whole picture..." },
        { id: 'd', text: "Protecting witnesses and evidence", nextNode: "6-s1-office-protection", consequence: "Secure what we have..." },
      ],
    },
    "6-s1-office-victims": { id: "6-s1-office-victims", type: "narrative", text: "'Harrison's records suggest at least sixty more victims we haven't identified. Families still wondering what happened to their daughters, their sisters. We're working with international agencies to track them.' One agent slides over a file. 'We found three more last week. Alive.'", nextNode: "6-s2", document: { title: "VICTIM_RECOVERY.pdf", preview: "60+ potential victims identified. Recovery operations ongoing...", pdfUrl: "/documents/victim-recovery.pdf" } },
    "6-s1-office-cases": { id: "6-s1-office-cases", type: "narrative", text: "'We're building files on each name Harrison gave us. Evidence packages ready for prosecution. When we move, we move on all of them at once. No warning. No time for them to run or destroy evidence.'", nextNode: "6-s2" },
    "6-s1-office-network": { id: "6-s1-office-network", type: "narrative", text: "A wall of photos, connected by red string. The old-fashioned way. 'Financial connections. Personal relationships. Business partnerships. Political alliances. When you step back, you see it.' Chen gestures. 'A parallel power structure. Operating for decades.'", nextNode: "6-s2" },
    "6-s1-office-protection": { id: "6-s1-office-protection", type: "narrative", text: "'Three witnesses have already been approached. Threats. Bribes. One had a break-in - nothing taken, just a message.' Chen's jaw tightens. 'We've moved everyone to secure locations. But they're scrambling. That means we're close.'", nextNode: "6-s2", document: { title: "WITNESS_PROTECTION.pdf", preview: "Witness threats documented. Enhanced security protocols...", pdfUrl: "/documents/witness-protection.pdf" } },

    // ========== STAGE 2: THE WHISTLEBLOWER ==========
    "6-s2": {
      id: "6-s2",
      type: "choice",
      text: "A week later. Your burner phone buzzes. Unknown number. 'Detective Cole? My name doesn't matter. What matters is I worked for the people you're investigating. I have documents. Internal communications. Client lists. I want to come forward. But I need guarantees.'",
      question: "STAGE 2/5 — How do you handle this potential whistleblower?",
      timerSeconds: 20,
      choices: [
        { id: 'a', text: "Arrange a secure meeting", nextNode: "6-s2-meeting", consequence: "Face to face..." },
        { id: 'b', text: "Ask for proof first", nextNode: "6-s2-proof", consequence: "Verify before trusting..." },
        { id: 'c', text: "Loop in Agent Chen immediately", nextNode: "6-s2-chen", consequence: "Don't work alone..." },
        { id: 'd', text: "Establish their credibility", nextNode: "6-s2-credibility", consequence: "Who are you?" },
      ],
    },
    "6-s2-meeting": {
      id: "6-s2-meeting",
      type: "choice",
      text: "A hotel lobby. Public enough for safety, private enough to talk. The whistleblower is a woman in her 40s - professional dress, nervous hands. 'I was their corporate attorney. I handled 'special accounts.' For three years, I told myself it was just unusual business practices. Then I saw an invoice that listed human beings as line items.'",
      question: "What does she have?",
      timerSeconds: 20,
      choices: [
        { id: 'a', text: "Internal communications", nextNode: "6-s2-meeting-comms", consequence: "What they said to each other..." },
        { id: 'b', text: "Financial records", nextNode: "6-s2-meeting-financial", consequence: "Where the money went..." },
        { id: 'c', text: "Client records", nextNode: "6-s2-meeting-clients", consequence: "Who participated..." },
        { id: 'd', text: "Operational documents", nextNode: "6-s2-meeting-operational", consequence: "How they ran it..." },
      ],
    },
    "6-s2-meeting-comms": { id: "6-s2-meeting-comms", type: "narrative", text: "She slides a flash drive across the table. 'Encrypted emails. Group chats. They discussed victims like inventory. Complained about quality. Made jokes.' Her voice catches. 'I read them. I can't unread them. But now you have them too.'", nextNode: "6-s3", document: { title: "INTERNAL_COMMS.pdf", preview: "Executive communications. Victims discussed as merchandise...", pdfUrl: "/documents/internal-comms.pdf" } },
    "6-s2-meeting-financial": { id: "6-s2-meeting-financial", type: "narrative", text: "'Transaction records going back five years. Every payment, every transfer, every shell company. I was the one who set up the structure. I know where the money goes.' She pauses. 'And who receives it. Names you'll recognize from the news.'", nextNode: "6-s3" },
    "6-s2-meeting-clients": { id: "6-s2-meeting-clients", type: "narrative", text: "'I have a list. Forty-seven names. Dates they visited. What they... requested.' She can barely say the words. 'Some are already in your files. Some will shock you. One is a sitting Supreme Court justice.'", nextNode: "6-s3", document: { title: "CLIENT_LIST.pdf", preview: "47 confirmed participants. High-profile names included...", pdfUrl: "/documents/client-list.pdf" } },
    "6-s2-meeting-operational": { id: "6-s2-meeting-operational", type: "narrative", text: "'Organizational charts. Security protocols. Staff lists with real names. They kept records of everything because they never thought they'd be caught. The arrogance of it...' She shakes her head. 'Now that arrogance is their weakness.'", nextNode: "6-s3" },
    "6-s2-proof": {
      id: "6-s2-proof",
      type: "choice",
      text: "'Send me something first. Something I can verify.' Thirty minutes later, your secure email has an encrypted attachment. You open it. Bank records showing transfers from a Fortune 500 CEO to an account in the Caymans. An account you've already traced to the island operation.",
      question: "It checks out. What next?",
      timerSeconds: 20,
      choices: [
        { id: 'a', text: "Arrange the meeting", nextNode: "6-s2-proof-meet", consequence: "You're legitimate..." },
        { id: 'b', text: "Ask for more before committing", nextNode: "6-s2-proof-more", consequence: "What else do you have?" },
        { id: 'c', text: "Bring Chen in before proceeding", nextNode: "6-s2-proof-chen", consequence: "Need backup..." },
        { id: 'd', text: "Research the whistleblower's background", nextNode: "6-s2-proof-research", consequence: "Who is this person?" },
      ],
    },
    "6-s2-proof-meet": { id: "6-s2-proof-meet", type: "narrative", text: "The meeting happens the next night. A lawyer who's been carrying guilt for three years, waiting for someone to listen. Someone who couldn't be bought or threatened. She found you. Now you have everything you need to bring down the network.", nextNode: "6-s3" },
    "6-s2-proof-more": { id: "6-s2-proof-more", type: "narrative", text: "More documents arrive. A board meeting memo discussing 'risk management' after the island raid. Names of people who voted to destroy evidence. A timeline of obstruction. The more she sends, the worse it gets - and the more valuable she becomes.", nextNode: "6-s3", document: { title: "BOARD_MEMO.pdf", preview: "Evidence destruction orders. Names of participants...", pdfUrl: "/documents/board-memo.pdf" } },
    "6-s2-proof-chen": { id: "6-s2-proof-chen", type: "narrative", text: "Chen verifies the documents independently. 'This is real, Cole. This person had access to everything. If we can protect them, they can bring down the whole structure.' You make the call. The whistleblower agrees to meet - with FBI protection in place.", nextNode: "6-s3" },
    "6-s2-proof-research": { id: "6-s2-proof-research", type: "narrative", text: "Elizabeth Kane. Corporate attorney. Resigned from her firm six months ago citing 'personal reasons.' Her exit was sudden. Her severance was $3 million with an NDA. An NDA she's about to violate spectacularly. But she's real. And she's ready to talk.", nextNode: "6-s3" },
    "6-s2-chen": {
      id: "6-s2-chen",
      type: "choice",
      text: "Chen listens to the recording. Her face goes through several emotions - skepticism, interest, excitement. 'If this is real... Cole, this could be the break we need. But we have to be careful. If they find out about a whistleblower, they'll move fast.'",
      question: "How do you proceed together?",
      timerSeconds: 20,
      choices: [
        { id: 'a', text: "Set up a secure extraction", nextNode: "6-s2-chen-extraction", consequence: "Get them safe first..." },
        { id: 'b', text: "Verify their information before contact", nextNode: "6-s2-chen-verify", consequence: "Check the story..." },
        { id: 'c', text: "Use Clean Hands resources", nextNode: "6-s2-chen-cleanhand", consequence: "Trusted network..." },
        { id: 'd', text: "Move immediately before word spreads", nextNode: "6-s2-chen-immediate", consequence: "Speed is safety..." },
      ],
    },
    "6-s2-chen-extraction": { id: "6-s2-chen-extraction", type: "narrative", text: "Chen's team moves the whistleblower within 24 hours. New location. New phones. Security in place. Only then do you sit down for the real conversation. What she knows is enough to end careers, topple companies, and send powerful people to prison.", nextNode: "6-s3", document: { title: "EXTRACTION_PROTOCOL.pdf", preview: "Whistleblower secured. Debriefing scheduled...", pdfUrl: "/documents/extraction-protocol.pdf" } },
    "6-s2-chen-verify": { id: "6-s2-chen-verify", type: "narrative", text: "Background check. Employment verification. Financial records. Everything checks out. Elizabeth Kane worked at the center of the conspiracy and kept meticulous records. 'My insurance policy,' she calls it. 'In case they ever turned on me.'", nextNode: "6-s3" },
    "6-s2-chen-cleanhand": { id: "6-s2-chen-cleanhand", type: "narrative", text: "The Clean Hands network activates. Trusted agents create a protection bubble around the whistleblower. Secure communications. Safe houses. A lawyer who can't be bought. By the time anyone realizes what's happening, she's already untouchable.", nextNode: "6-s3" },
    "6-s2-chen-immediate": { id: "6-s2-chen-immediate", type: "narrative", text: "No time for elaborate planning. You meet the whistleblower that night, take her documents, and get her into FBI protection by morning. It's messy, rushed, risky - but you have the evidence before anyone can destroy it.", nextNode: "6-s3" },
    "6-s2-credibility": {
      id: "6-s2-credibility",
      type: "choice",
      text: "'Before we go further - who are you? How did you get access to this information?' A long pause. 'I was their lawyer. I set up the shell companies. I handled the payments. I'm complicit in everything you're investigating. And I can't live with it anymore.'",
      question: "How do you respond?",
      timerSeconds: 20,
      choices: [
        { id: 'a', text: "Immunity will be discussed", nextNode: "6-s2-credibility-immunity", consequence: "We can make a deal..." },
        { id: 'b', text: "Your testimony is what matters", nextNode: "6-s2-credibility-testimony", consequence: "What can you prove?" },
        { id: 'c', text: "Why come forward now?", nextNode: "6-s2-credibility-why", consequence: "Understand the motivation..." },
        { id: 'd', text: "What do you want in return?", nextNode: "6-s2-credibility-want", consequence: "Everyone wants something..." },
      ],
    },
    "6-s2-credibility-immunity": { id: "6-s2-credibility-immunity", type: "narrative", text: "'Immunity for full cooperation. It's been done before.' The voice is steadier now. 'I'm not looking to escape consequences. I'm looking to make sure the people above me don't escape either. The people who made the real decisions. I was just... infrastructure.'", nextNode: "6-s3" },
    "6-s2-credibility-testimony": { id: "6-s2-credibility-testimony", type: "narrative", text: "'I can prove everything. I have documents going back five years. Board meetings. Financial transfers. Communications. I know who paid, who visited, who covered it up.' The weight of it hits you. This person could bring down an empire.", nextNode: "6-s3", document: { title: "TESTIMONY_PREVIEW.pdf", preview: "Five years of documentation. Multiple conspiracy counts provable...", pdfUrl: "/documents/testimony-preview.pdf" } },
    "6-s2-credibility-why": { id: "6-s2-credibility-why", type: "narrative", text: "'Morrison's conviction. Seeing him actually face consequences. I realized... maybe the system works sometimes. Maybe if I came forward, it would matter.' A pause. 'And I'm tired. Tired of knowing what I know and doing nothing.'", nextNode: "6-s3" },
    "6-s2-credibility-want": { id: "6-s2-credibility-want", type: "narrative", text: "'I want to stop being afraid. I want to sleep without nightmares. I want to tell my daughter someday that I tried to make it right.' The voice breaks. 'That's what I want. Can you help me with that, Detective?'", nextNode: "6-s3" },

    // ========== STAGE 3: THE NETWORK ==========
    "6-s3": {
      id: "6-s3",
      type: "choice",
      text: "The whistleblower's documents are everything promised and more. Names, dates, amounts. But one name keeps appearing at the top of every organizational chart: Victor Ashford. Tech billionaire. Philanthropist. Known as the 'Conscience of Silicon Valley.' His foundation fights human trafficking. The irony makes you sick.",
      question: "STAGE 3/5 — How do you approach Ashford?",
      timerSeconds: 20,
      choices: [
        { id: 'a', text: "Build the case methodically", nextNode: "6-s3-methodical", consequence: "Every detail locked down..." },
        { id: 'b', text: "Find someone in his circle who will flip", nextNode: "6-s3-flip", consequence: "Inside information..." },
        { id: 'c', text: "Investigate his foundation", nextNode: "6-s3-foundation", consequence: "The cover story..." },
        { id: 'd', text: "Coordinate with international partners", nextNode: "6-s3-international", consequence: "He operates globally..." },
      ],
    },
    "6-s3-methodical": {
      id: "6-s3-methodical",
      type: "choice",
      text: "You build the case piece by piece. Financial analysis. Witness interviews. Document verification. Chen's team works around the clock. After three weeks, you have a file on Ashford six inches thick. Every transaction traced. Every connection mapped.",
      question: "What's the strongest evidence?",
      timerSeconds: 20,
      choices: [
        { id: 'a', text: "Financial records showing payments", nextNode: "6-s3-methodical-financial", consequence: "Follow the money..." },
        { id: 'b', text: "Communications referencing the operation", nextNode: "6-s3-methodical-comms", consequence: "His own words..." },
        { id: 'c', text: "Witness testimony placing him on the island", nextNode: "6-s3-methodical-witness", consequence: "People who saw him..." },
        { id: 'd', text: "Documents with his signature", nextNode: "6-s3-methodical-signature", consequence: "Can't deny his hand..." },
      ],
    },
    "6-s3-methodical-financial": { id: "6-s3-methodical-financial", type: "narrative", text: "Ashford's 'charitable donations' to shell companies trace directly to the island's operating budget. $15 million over five years. His accountants tried to hide it, but money always leaves a trail if you look hard enough.", nextNode: "6-s4", document: { title: "ASHFORD_FINANCIAL.pdf", preview: "$15M traced from Ashford to island operations...", pdfUrl: "/documents/ashford-financial.pdf" } },
    "6-s3-methodical-comms": { id: "6-s3-methodical-comms", type: "narrative", text: "Encrypted messages from Ashford's personal phone, recovered by forensic analysis. Messages that discuss 'new inventory' and 'client satisfaction.' Messages that only make sense in one horrifying context.", nextNode: "6-s4" },
    "6-s3-methodical-witness": { id: "6-s3-methodical-witness", type: "narrative", text: "Three survivors identify Ashford from photo arrays. A former security guard confirms he visited at least monthly. A helicopter pilot describes flying him to the island twenty-three times. Witnesses who will testify.", nextNode: "6-s4", document: { title: "ASHFORD_WITNESSES.pdf", preview: "Multiple witnesses. 23 documented visits...", pdfUrl: "/documents/ashford-witnesses.pdf" } },
    "6-s3-methodical-signature": { id: "6-s3-methodical-signature", type: "narrative", text: "Board meeting minutes with Ashford's signature. Approving 'operational expenditures.' Authorizing 'security protocols.' Corporate language for criminal enterprise. His lawyers will try to explain it away. The jury won't believe them.", nextNode: "6-s4" },
    "6-s3-flip": {
      id: "6-s3-flip",
      type: "choice",
      text: "Ashford's inner circle is small. His head of security, James Mercer. His personal assistant, Diana Reeves. His pilot, Tom Bradley. His foundation director, Katherine Shaw. One of them knows everything. One of them might talk.",
      question: "Who do you approach?",
      timerSeconds: 20,
      choices: [
        { id: 'a', text: "Mercer - security knows everything", nextNode: "6-s3-flip-mercer", consequence: "He's seen things..." },
        { id: 'b', text: "Reeves - she manages his life", nextNode: "6-s3-flip-reeves", consequence: "She knows the schedule..." },
        { id: 'c', text: "Bradley - pilots hear conversations", nextNode: "6-s3-flip-bradley", consequence: "He knows where they went..." },
        { id: 'd', text: "Shaw - she might have a conscience", nextNode: "6-s3-flip-shaw", consequence: "Foundation director..." },
      ],
    },
    "6-s3-flip-mercer": { id: "6-s3-flip-mercer", type: "narrative", text: "Mercer won't flip - he's too implicated. But his ex-wife will talk. Divorced after learning 'what he did for work.' She doesn't have evidence, but she has stories. Enough stories to help you know where to dig.", nextNode: "6-s4" },
    "6-s3-flip-reeves": { id: "6-s3-flip-reeves", type: "narrative", text: "Diana Reeves is dying. Cancer, terminal. She reaches out before you can approach her. 'I've worked for a monster for fifteen years. I want to make it right before I go.' She has calendars, notes, recordings. Insurance she kept against the day it might matter.", nextNode: "6-s4", document: { title: "REEVES_RECORDS.pdf", preview: "Personal assistant's documentation. 15 years of records...", pdfUrl: "/documents/reeves-records.pdf" } },
    "6-s3-flip-bradley": { id: "6-s3-flip-bradley", type: "narrative", text: "Bradley is drinking himself to death with guilt. You find him at a dive bar at noon. 'I flew people who never flew back out,' he says. 'Asked once what happened to them. Ashford smiled. Said they found peace.' He agrees to testify. He's got nothing left to lose.", nextNode: "6-s4" },
    "6-s3-flip-shaw": { id: "6-s3-flip-shaw", type: "narrative", text: "Katherine Shaw genuinely didn't know. When you show her the evidence, she breaks down. 'I thought the foundation was real. I thought we were helping.' Then the horror turns to anger. 'Tell me what you need. I'll help you destroy him.'", nextNode: "6-s4" },
    "6-s3-foundation": {
      id: "6-s3-foundation",
      type: "choice",
      text: "Ashford's anti-trafficking foundation has received praise from world leaders. It's also received $50 million in donations from companies connected to the trafficking network. Money laundering disguised as philanthropy. The foundation was the cover story all along.",
      question: "What does the foundation investigation reveal?",
      timerSeconds: 20,
      choices: [
        { id: 'a', text: "Donor records showing network connections", nextNode: "6-s3-foundation-donors", consequence: "Who gave money..." },
        { id: 'b', text: "Programs that were never real", nextNode: "6-s3-foundation-fake", consequence: "Phantom charity..." },
        { id: 'c', text: "Staff who suspect something wrong", nextNode: "6-s3-foundation-staff", consequence: "Whistleblowers within..." },
        { id: 'd', text: "Financial irregularities", nextNode: "6-s3-foundation-financial", consequence: "Where the money really went..." },
      ],
    },
    "6-s3-foundation-donors": { id: "6-s3-foundation-donors", type: "narrative", text: "The donor list reads like a client list. Every major contributor has connections to the network. They weren't donating to fight trafficking - they were paying membership dues. The foundation was the billing department for a criminal enterprise.", nextNode: "6-s4", document: { title: "FOUNDATION_DONORS.pdf", preview: "Donor list matches client list. $50M in 'donations'...", pdfUrl: "/documents/foundation-donors.pdf" } },
    "6-s3-foundation-fake": { id: "6-s3-foundation-fake", type: "narrative", text: "'Anti-trafficking education programs' that never educated anyone. 'Survivor services' that served no survivors. Photo ops and press releases, but no actual work. The foundation was a shell - a PR operation to make Ashford look like a saint.", nextNode: "6-s4" },
    "6-s3-foundation-staff": { id: "6-s3-foundation-staff", type: "narrative", text: "A program coordinator who asked too many questions. She noticed the discrepancies - money allocated for programs that didn't exist. She was 'let go' for 'budget reasons.' Now she's ready to testify about what she saw and what she was told to ignore.", nextNode: "6-s4" },
    "6-s3-foundation-financial": { id: "6-s3-foundation-financial", type: "narrative", text: "Foundation money flowed to accounts in Cyprus, then to the Caymans, then to operations we've already connected to the island. Millions of dollars in 'charitable' contributions funding human trafficking. The IRS will be very interested.", nextNode: "6-s4", document: { title: "FOUNDATION_FINANCIAL.pdf", preview: "Money flow from foundation to trafficking operations...", pdfUrl: "/documents/foundation-financial.pdf" } },
    "6-s3-international": {
      id: "6-s3-international",
      type: "choice",
      text: "Ashford's reach extends beyond US borders. Properties in six countries. Bank accounts in a dozen more. If you're going to take him down, you need international cooperation. Chen reaches out to trusted contacts at Interpol.",
      question: "What do international partners contribute?",
      timerSeconds: 20,
      choices: [
        { id: 'a', text: "Evidence from European investigations", nextNode: "6-s3-international-europe", consequence: "They've seen him too..." },
        { id: 'b', text: "Financial intelligence from banking centers", nextNode: "6-s3-international-banking", consequence: "Follow the money globally..." },
        { id: 'c', text: "Victim testimony from other countries", nextNode: "6-s3-international-victims", consequence: "More survivors..." },
        { id: 'd', text: "Surveillance of Ashford's overseas properties", nextNode: "6-s3-international-properties", consequence: "Other locations..." },
      ],
    },
    "6-s3-international-europe": { id: "6-s3-international-europe", type: "narrative", text: "German BKA has been investigating Ashford for two years. Never enough to prosecute. But combined with your evidence, their files fill gaps in the timeline. French DGSI adds three more witnesses. The case goes from strong to overwhelming.", nextNode: "6-s4", document: { title: "EUROPEAN_INTEL.pdf", preview: "German and French investigation files. Combined evidence package...", pdfUrl: "/documents/european-intel.pdf" } },
    "6-s3-international-banking": { id: "6-s3-international-banking", type: "narrative", text: "Swiss financial intelligence identifies accounts they've been monitoring. Singapore traces shell companies. The Caymans - after significant pressure - provide transaction records. The global money trail leads to one place: Ashford.", nextNode: "6-s4" },
    "6-s3-international-victims": { id: "6-s3-international-victims", type: "narrative", text: "Survivors in Thailand, Eastern Europe, and South America - all with similar stories. All describing the same operation. All identifying Ashford from photos. The scope of it... he did this for decades, across continents.", nextNode: "6-s4", document: { title: "INTERNATIONAL_VICTIMS.pdf", preview: "Survivor testimony from multiple countries. Pattern confirmed...", pdfUrl: "/documents/international-victims.pdf" } },
    "6-s3-international-properties": { id: "6-s3-international-properties", type: "narrative", text: "A compound in Fiji. A villa in the Maldives. A 'retreat' in the Philippines. All remote. All with unusual security. All showing the same thermal signatures as the island. Ashford didn't run one location. He ran a network of locations.", nextNode: "6-s4" },

    // ========== STAGE 4: THE ARREST ==========
    "6-s4": {
      id: "6-s4",
      type: "choice",
      text: "The case is ready. Warrants signed by a federal judge outside the compromised network. Sixteen simultaneous raids planned for 4 AM tomorrow: Ashford's residence, his foundation headquarters, the homes of twelve other conspirators. Chen's Clean Hands team will execute. This is the moment everything has built toward.",
      question: "STAGE 4/5 — The night before the raids. How do you prepare?",
      timerSeconds: 20,
      choices: [
        { id: 'a', text: "Review the tactical plans one more time", nextNode: "6-s4-tactical", consequence: "Nothing can go wrong..." },
        { id: 'b', text: "Secure backup copies of all evidence", nextNode: "6-s4-backup", consequence: "Insurance policy..." },
        { id: 'c', text: "Check on the protected witnesses", nextNode: "6-s4-witnesses", consequence: "They're still targets..." },
        { id: 'd', text: "Try to get some rest", nextNode: "6-s4-rest", consequence: "You'll need your strength..." },
      ],
    },
    "6-s4-tactical": {
      id: "6-s4-tactical",
      type: "choice",
      text: "Chen walks you through the operation. Sixteen locations. Sixty agents. Local SWAT support. Coordinated timing to prevent anyone from alerting others. Communications on a closed channel. If this works, they'll all be in custody before breakfast.",
      question: "What concerns you most?",
      timerSeconds: 20,
      choices: [
        { id: 'a', text: "Ashford's personal security", nextNode: "6-s4-tactical-security", consequence: "Ex-military, well-armed..." },
        { id: 'b', text: "Potential evidence destruction", nextNode: "6-s4-tactical-evidence", consequence: "They might burn it all..." },
        { id: 'c', text: "The possibility of a leak", nextNode: "6-s4-tactical-leak", consequence: "Someone might warn them..." },
        { id: 'd', text: "Coordinating simultaneous entry", nextNode: "6-s4-tactical-timing", consequence: "Timing is everything..." },
      ],
    },
    "6-s4-tactical-security": { id: "6-s4-tactical-security", type: "narrative", text: "Ashford's security team is eight people, all ex-special forces. But they're not expecting a federal raid at 4 AM. Element of surprise matters. And SWAT has dealt with worse. 'Overwhelming force, minimal warning,' Chen says. 'They won't have time to react.'", nextNode: "6-s5" },
    "6-s4-tactical-evidence": { id: "6-s4-tactical-evidence", type: "narrative", text: "First teams through the door will secure computers and file storage. Ashford's IT systems have a 15-minute auto-destruct if triggered. Your tech team will have 10 minutes to prevent it. It'll be close. But the key evidence is already secured from the whistleblower.", nextNode: "6-s5", document: { title: "EVIDENCE_PROTOCOL.pdf", preview: "Server seizure protocols. 10-minute window...", pdfUrl: "/documents/evidence-protocol.pdf" } },
    "6-s4-tactical-leak": { id: "6-s4-tactical-leak", type: "narrative", text: "Only Clean Hands agents know the full picture. Everyone else gets their assignment one hour before execution. If there's a leak, it would have to come from inside your trusted circle. You look at each face around the table. You trust them. You have to.", nextNode: "6-s5" },
    "6-s4-tactical-timing": { id: "6-s4-tactical-timing", type: "narrative", text: "Synchronized watches. Dedicated communication channel. Every team enters within a 30-second window. One person gets a warning call, they all get warned. But if it works, sixteen targets in custody before any of them can call their lawyers.", nextNode: "6-s5" },
    "6-s4-backup": {
      id: "6-s4-backup",
      type: "choice",
      text: "You've learned from experience: evidence disappears, witnesses recant, cases fall apart. If something goes wrong tomorrow, you need insurance. Multiple copies of everything, stored in places they can't reach.",
      question: "Where do you secure the evidence?",
      timerSeconds: 20,
      choices: [
        { id: 'a', text: "Encrypted cloud storage in multiple countries", nextNode: "6-s4-backup-cloud", consequence: "Digital immortality..." },
        { id: 'b', text: "Physical copies with trusted journalists", nextNode: "6-s4-backup-press", consequence: "Story gets told either way..." },
        { id: 'c', text: "Lawyer's safe deposit box", nextNode: "6-s4-backup-lawyer", consequence: "Dead man's switch..." },
        { id: 'd', text: "All of the above", nextNode: "6-s4-backup-all", consequence: "Maximum redundancy..." },
      ],
    },
    "6-s4-backup-cloud": { id: "6-s4-backup-cloud", type: "narrative", text: "Servers in Iceland, Switzerland, and Singapore. Encrypted with keys only you know. Set to auto-release to journalists and law enforcement if you don't check in every 48 hours. They can bury you, but they can't bury the data.", nextNode: "6-s5" },
    "6-s4-backup-press": { id: "6-s4-backup-press", type: "narrative", text: "Three journalists at three different outlets. Each has a portion of the evidence - enough to publish if something goes wrong. One at the Times, one at the Guardian, one at a podcast that's broken major stories before. The truth has multiple guardians now.", nextNode: "6-s5", document: { title: "PRESS_PACKAGE.pdf", preview: "Evidence distributed to journalists. Dead man's switch active...", pdfUrl: "/documents/press-package.pdf" } },
    "6-s4-backup-lawyer": { id: "6-s4-backup-lawyer", type: "narrative", text: "Your attorney has instructions: if you die, disappear, or get arrested on obviously fabricated charges, the box opens. Flash drives. Bank records. A notarized statement naming names. Your final testimony, just in case.", nextNode: "6-s5" },
    "6-s4-backup-all": { id: "6-s4-backup-all", type: "narrative", text: "Redundancy is paranoia. Paranoia is survival. Cloud storage, press copies, lawyer backup - an ecosystem of evidence that can survive your death or disappearance. Twenty years of police work taught you: hope for the best, plan for your funeral.", nextNode: "6-s5" },
    "6-s4-witnesses": {
      id: "6-s4-witnesses",
      type: "choice",
      text: "The whistleblower. The survivors who identified Ashford. The pilot who agreed to testify. They're all in protection, but protection isn't perfect. One phone call could change everything.",
      question: "Who do you check on personally?",
      timerSeconds: 20,
      choices: [
        { id: 'a', text: "Elizabeth Kane, the whistleblower", nextNode: "6-s4-witnesses-kane", consequence: "She's the key..." },
        { id: 'b', text: "The survivor from the original trial", nextNode: "6-s4-witnesses-survivor", consequence: "She started all this..." },
        { id: 'c', text: "Tom Bradley, the pilot", nextNode: "6-s4-witnesses-bradley", consequence: "Fragile witness..." },
        { id: 'd', text: "All protected witnesses via status check", nextNode: "6-s4-witnesses-all", consequence: "Everyone matters..." },
      ],
    },
    "6-s4-witnesses-kane": { id: "6-s4-witnesses-kane", type: "narrative", text: "Kane is calm. Calmer than you expected. 'I've been waiting for this,' she says. 'Three years of carrying what I knew. Tomorrow, it's over.' You promise her: after tomorrow, she gets a new life. New name. New start. She earned it.", nextNode: "6-s5" },
    "6-s4-witnesses-survivor": { id: "6-s4-witnesses-survivor", type: "narrative", text: "The survivor watches news of Morrison's sentencing on a small TV. Life in prison, no parole. 'It's not enough,' she says quietly. 'But it's something.' You tell her about tomorrow. About Ashford. Her eyes harden. 'Get him.'", nextNode: "6-s5", document: { title: "SURVIVOR_UPDATE.pdf", preview: "Original survivor briefed. Stable and determined...", pdfUrl: "/documents/survivor-update.pdf" } },
    "6-s4-witnesses-bradley": { id: "6-s4-witnesses-bradley", type: "narrative", text: "Bradley is sober. First time you've seen him clear-eyed. 'I stopped drinking when you told me I could help,' he says. 'Turns out I needed a reason.' Tomorrow he'll testify about flying Ashford to the island twenty-three times. He's ready.", nextNode: "6-s5" },
    "6-s4-witnesses-all": { id: "6-s4-witnesses-all", type: "narrative", text: "Status checks across all protected witnesses. Everyone accounted for. Everyone secure. Chen's team has done excellent work. Tomorrow, these people will tell their stories in court. Tonight, they're safe. That's what matters.", nextNode: "6-s5" },
    "6-s4-rest": {
      id: "6-s4-rest",
      type: "choice",
      text: "You go home. Try to sleep. Stare at the ceiling instead. Twenty years of cases, and this is the biggest. Tomorrow changes everything - or it doesn't, and you spent your career chasing ghosts. The clock reads 2:37 AM when you finally drift off.",
      question: "In your last quiet moments, what do you think about?",
      timerSeconds: 20,
      choices: [
        { id: 'a', text: "The victims who deserve justice", nextNode: "6-s4-rest-victims", consequence: "For them..." },
        { id: 'b', text: "The career you've dedicated to this", nextNode: "6-s4-rest-career", consequence: "Was it worth it?" },
        { id: 'c', text: "What tomorrow will look like", nextNode: "6-s4-rest-tomorrow", consequence: "Visualize success..." },
        { id: 'd', text: "Nothing - clear your mind", nextNode: "6-s4-rest-clear", consequence: "Focus..." },
      ],
    },
    "6-s4-rest-victims": { id: "6-s4-rest-victims", type: "narrative", text: "Faces you've memorized from case files. Names of people who didn't survive. Survivors who testified through tears. Tomorrow isn't about career advancement or headlines. It's about them. It's always been about them.", nextNode: "6-s5" },
    "6-s4-rest-career": { id: "6-s4-rest-career", type: "narrative", text: "Twenty years. Commendations and complaints. Cases won and cases lost. Moments you're proud of and moments you regret. All of it leading here. Whatever happens tomorrow, you did the work. You followed the evidence. You told the truth.", nextNode: "6-s5" },
    "6-s4-rest-tomorrow": { id: "6-s4-rest-tomorrow", type: "narrative", text: "You picture it: 4 AM entry. Ashford in handcuffs. His servers seized. His network dismantled. The press conference. The indictments. The trial. The conviction. You've visualized successful operations before. Tomorrow will be one of them.", nextNode: "6-s5", document: { title: "OPERATION_PLAN.pdf", preview: "Final operation timeline. All contingencies mapped...", pdfUrl: "/documents/operation-plan.pdf" } },
    "6-s4-rest-clear": { id: "6-s4-rest-clear", type: "narrative", text: "No sentiment. No philosophy. Just the mission. You run through the plan one more time in your head, then let it go. Tomorrow requires a clear mind. You breathe. You rest. You wait for the alarm.", nextNode: "6-s5" },

    // ========== STAGE 5: THE TRUTH ==========
    "6-s5": {
      id: "6-s5",
      type: "choice",
      text: "4:00 AM. Sixteen simultaneous raids. You're with the team hitting Ashford's estate. The gates come down. Agents swarm. Inside, you find Ashford awake - sitting in his study, dressed in a suit, a glass of scotch in his hand. Like he was expecting you. 'Detective Cole,' he says calmly. 'I wondered how long it would take.'",
      question: "STAGE 5/5 — How do you handle this moment?",
      timerSeconds: 20,
      choices: [
        { id: 'a', text: "Read him his rights - by the book", nextNode: "6-s5-rights", consequence: "Professional to the end..." },
        { id: 'b', text: "Let him see the scope of the operation", nextNode: "6-s5-scope", consequence: "Show him it's over..." },
        { id: 'c', text: "Ask him why he did it", nextNode: "6-s5-why", consequence: "Understand the monster..." },
        { id: 'd', text: "Secure the evidence while he's distracted", nextNode: "6-s5-evidence", consequence: "The case matters most..." },
      ],
    },
    "6-s5-rights": {
      id: "6-s5-rights",
      type: "narrative",
      text: "'Victor Ashford, you're under arrest for human trafficking, conspiracy, money laundering, and obstruction of justice. You have the right to remain silent. Anything you say can and will be used against you in a court of law.' He smiles as the cuffs go on. 'Do you know how many lawyers I have, Detective?' You meet his eyes. 'Not enough.'",
      nextNode: "6-complete"
    },
    "6-s5-scope": {
      id: "6-s5-scope",
      type: "narrative",
      text: "'Right now, fourteen other locations are being raided. Everyone you worked with. Everyone who protected you. Everyone who used your services.' You watch his face as the information lands. For the first time, his composure cracks. 'You can't... this isn't...' 'It's over, Mr. Ashford. All of it.'",
      nextNode: "6-complete",
      document: { title: "RAID_SUMMARY.pdf", preview: "16 simultaneous raids. 14 arrests. All targets secured...", pdfUrl: "/documents/raid-summary.pdf" }
    },
    "6-s5-why": {
      id: "6-s5-why",
      type: "narrative",
      text: "'I have one question. Why? You had everything. Money. Fame. Power. Why do this?' Ashford sips his scotch. 'Because I could. Because no one stopped me. Because real power means doing whatever you want and watching the world pretend it didn't happen.' He sets down the glass. 'Until you.'",
      nextNode: "6-complete"
    },
    "6-s5-evidence": {
      id: "6-s5-evidence",
      type: "narrative",
      text: "While agents secure Ashford, you move to his private office. Hidden room behind the bookshelf. Inside: servers still running, documents they didn't have time to destroy, and a wall of photographs. Trophies. Victims. Evidence that will ensure he never sees freedom again.",
      nextNode: "6-complete",
      document: { title: "TROPHY_ROOM.pdf", preview: "Hidden room discovered. Physical evidence secured...", pdfUrl: "/documents/trophy-room.pdf" }
    },

    // ========== CHAPTER 6 COMPLETE - CONTINUES TO CHAPTER 7 ==========
    "6-complete": {
      id: "6-complete",
      type: "chapter-end",
      text: "The raids are successful. Victor Ashford sits in federal custody along with fifteen other conspirators. Servers seized. Documents secured. The headlines run for days. But as you process the evidence from Ashford's hidden room, you find something unexpected: references to 'The Board' - a group above even Ashford. Names redacted. Locations coded. This wasn't the top of the pyramid. There's more. Chen calls you at midnight. 'Cole, you need to see this. We found a list. Dates and locations for something called 'The Gathering.' It's happening in three weeks. And the location...' She pauses. 'It's on US soil.'",
      chapterComplete: {
        chapter: 6,
        nextChapter: 7,
        summary: "Ashford and his network are in custody, but the investigation reveals a deeper conspiracy. 'The Board' - a shadow organization above Ashford - is planning something called 'The Gathering.' The hunt continues."
      },
    },
  },
};