import { BranchingChapter } from '../types';

/**
 * CHAPTER 5: THE TRIAL - 5 Stages, full branching
 * PERSPECTIVE SHIFT: You are Detective Marcus Cole, lead investigator.
 * 20 years on the force. You've seen the worst of humanity. But this case... this is different.
 */
export const CHAPTER_5: BranchingChapter = {
  id: 5,
  title: "CHAPTER 5",
  subtitle: "The Trial",
  startNode: "5-s1",
  nodes: {
    // ========== STAGE 1: THE DETECTIVE ==========
    "5-s1": {
      id: "5-s1",
      type: "choice",
      text: "Detective Marcus Cole. Twenty years on the force, fifteen in major crimes. You've worked homicides, kidnappings, organized crime. But when the FBI called you in as local liaison for 'the island case,' you didn't know it would consume your life. Now you're sitting in the courthouse hallway, waiting to testify. The survivor just finished - three days of devastating testimony. Your turn next.",
      question: "STAGE 1/5 — How do you prepare for your testimony?",
      timerSeconds: 20,
      choices: [
        { id: 'a', text: "Review your case notes one more time", nextNode: "5-s1-notes", consequence: "Every detail matters..." },
        { id: 'b', text: "Talk to the prosecutor about strategy", nextNode: "5-s1-prosecutor", consequence: "Coordinate approach..." },
        { id: 'c', text: "Check on the survivor witness", nextNode: "5-s1-survivor", consequence: "She's been through hell..." },
        { id: 'd', text: "Confront Senator Morrison's lawyer", nextNode: "5-s1-death", consequence: "Set the tone..." },
      ],
    },
    "5-s1-death": { id: "5-s1-death", type: "death", text: "You corner Morrison's lawyer in the hallway. 'We both know he's guilty.' The lawyer smiles, pulls out his phone, starts recording. 'Detective Cole, are you attempting to intimidate defense counsel?' Your words will be played in court. Witness tampering. Case compromised. You're removed from the trial.", deathMessage: "Never confront defense lawyers off the record." },
    "5-s1-notes": {
      id: "5-s1-notes",
      type: "choice",
      text: "Your case file is three inches thick. Witness statements. Forensic reports. Financial records. The timeline you built piece by piece over six months. Something's been nagging at you - a connection you haven't quite made.",
      question: "What do you focus on in your notes?",
      timerSeconds: 20,
      choices: [
        { id: 'a', text: "The financial trail", nextNode: "5-s1-notes-money", consequence: "Follow the money..." },
        { id: 'b', text: "Witness testimony inconsistencies", nextNode: "5-s1-notes-witnesses", consequence: "Small details..." },
        { id: 'c', text: "The timeline of events", nextNode: "5-s1-notes-timeline", consequence: "When things happened..." },
        { id: 'd', text: "Evidence chain of custody", nextNode: "5-s1-notes-custody", consequence: "Airtight case..." },
      ],
    },
    "5-s1-notes-money": { id: "5-s1-notes-money", type: "narrative", text: "There. A shell company - Meridian Holdings - appears in Morrison's finances AND the island's operating budget. You'd flagged it before but... now you see it also connects to Judge Harrison. The judge who was supposed to hear this case before recusing himself. That's not coincidence.", nextNode: "5-s2", document: { title: "FINANCIAL_CONNECTION.pdf", preview: "Meridian Holdings links Morrison, island, and Judge Harrison...", pdfUrl: "/documents/financial-connection.pdf" } },
    "5-s1-notes-witnesses": { id: "5-s1-notes-witnesses", type: "narrative", text: "Guard Torres said the helicopter was grounded for maintenance on March 15th. But pilot logs show a flight that night. Someone's lying. If you can prove which one, you can flip them against Morrison.", nextNode: "5-s2" },
    "5-s1-notes-timeline": { id: "5-s1-notes-timeline", type: "narrative", text: "The survivor escaped at 0347. Morrison's phone pinged the island at 0342 - five minutes before. He was there. He saw her escape. And he didn't alert security. Why? Unless he wanted chaos. A distraction from something else happening that night.", nextNode: "5-s2", document: { title: "TIMELINE_ANOMALY.pdf", preview: "Morrison present during escape. No alert triggered. Why?", pdfUrl: "/documents/timeline.pdf" } },
    "5-s1-notes-custody": { id: "5-s1-notes-custody", type: "narrative", text: "Every piece of evidence properly logged. Every transfer documented. Defense will try to claim tampering - they always do. But your chain is airtight. Six months of meticulous work. They won't break it.", nextNode: "5-s2" },
    "5-s1-prosecutor": {
      id: "5-s1-prosecutor",
      type: "choice",
      text: "ADA Sarah Chen - no relation to the FBI agent - has been preparing this case for months. She looks exhausted but determined. 'Detective. How are you feeling?' 'Ready,' you lie. 'Good. Because Morrison's team is going to come at you hard.'",
      question: "What do you discuss with the prosecutor?",
      timerSeconds: 20,
      choices: [
        { id: 'a', text: "Defense strategy predictions", nextNode: "5-s1-prosecutor-defense", consequence: "Know the enemy..." },
        { id: 'b', text: "Key evidence to emphasize", nextNode: "5-s1-prosecutor-evidence", consequence: "Hit them hard..." },
        { id: 'c', text: "Potential weaknesses in the case", nextNode: "5-s1-prosecutor-weak", consequence: "Shore up holes..." },
        { id: 'd', text: "Your concerns about jury tampering", nextNode: "5-s1-prosecutor-jury", consequence: "Something feels off..." },
      ],
    },
    "5-s1-prosecutor-defense": { id: "5-s1-prosecutor-defense", type: "narrative", text: "'They'll attack your methods. Claim you had a vendetta against Morrison. They've dug into your past cases - looking for anything.' She pauses. 'The Martinez case.' Your stomach drops. A case from eight years ago. Suspect walked on a technicality. 'I followed procedure.' 'I know. Just be ready.'", nextNode: "5-s2" },
    "5-s1-prosecutor-evidence": { id: "5-s1-prosecutor-evidence", type: "narrative", text: "'The surveillance footage is our strongest piece. Morrison on camera, on the island, with victims visible in frame. His lawyers will claim deepfake, editing, anything. You need to explain chain of custody like you're talking to children.' You nod. Simple. Clear. Devastating.", nextNode: "5-s2", document: { title: "KEY_EVIDENCE.pdf", preview: "Surveillance footage strategy. Unimpeachable chain...", pdfUrl: "/documents/key-evidence.pdf" } },
    "5-s1-prosecutor-weak": { id: "5-s1-prosecutor-weak", type: "narrative", text: "'The weak point is the gap. Three hours on March 12th where Morrison's whereabouts are unaccounted for - but so is anyone else's. Defense will argue he wasn't on the island then.' 'But the phone records-' 'Are circumstantial. We need you to sell the totality.'", nextNode: "5-s2" },
    "5-s1-prosecutor-jury": { id: "5-s1-prosecutor-jury", type: "narrative", text: "'Juror 7. He's been watching Morrison's lawyer, not the witnesses.' Chen frowns. 'We noticed too. Background check came up clean, but...' 'But Morrison has resources.' 'We're monitoring. If he makes a move, we'll catch it.'", nextNode: "5-s2", document: { title: "JUROR_CONCERN.pdf", preview: "Juror 7 flagged. Surveillance authorized...", pdfUrl: "/documents/juror.pdf" } },
    "5-s1-survivor": {
      id: "5-s1-survivor",
      type: "choice",
      text: "She's in the witness room, FBI agents at the door. Exhausted. Pale. But when she sees you, she manages a small smile. 'Detective Cole.' 'How are you holding up?' Stupid question. You know it as soon as you ask.",
      question: "How do you support the survivor?",
      timerSeconds: 20,
      choices: [
        { id: 'a', text: "Offer practical reassurance", nextNode: "5-s1-survivor-practical", consequence: "Facts help..." },
        { id: 'b', text: "Share your own experience with difficult cases", nextNode: "5-s1-survivor-share", consequence: "You're not alone..." },
        { id: 'c', text: "Just sit with her in silence", nextNode: "5-s1-survivor-silence", consequence: "Presence matters..." },
        { id: 'd', text: "Promise Morrison will pay", nextNode: "5-s1-survivor-promise", consequence: "Justice is coming..." },
      ],
    },
    "5-s1-survivor-practical": { id: "5-s1-survivor-practical", type: "narrative", text: "'Your testimony was solid. Defense couldn't shake you. The jury was paying attention - the right kind of attention.' She nods slowly. 'I just kept thinking about the others. The ones who didn't make it out.' 'That's why we're here. For them too.'", nextNode: "5-s2" },
    "5-s1-survivor-share": { id: "5-s1-survivor-share", type: "narrative", text: "'Fifteen years ago, I testified against a cop. My partner. He was dirty. Walking into that courtroom was the hardest thing I'd ever done.' She looks up. 'What happened?' 'He's in prison. Still is.' Sometimes the system works. She needs to believe that.", nextNode: "5-s2" },
    "5-s1-survivor-silence": { id: "5-s1-survivor-silence", type: "narrative", text: "You sit. Don't say anything. After a few minutes, she speaks. 'Everyone keeps asking how I feel. Like there are words for this.' 'There aren't.' 'No. There aren't.' But somehow, the silence helps. Some things can't be talked through. Only endured.", nextNode: "5-s2", document: { title: "WITNESS_SUPPORT.pdf", preview: "Survivor stabilized. Ready for continued proceedings...", pdfUrl: "/documents/support.pdf" } },
    "5-s1-survivor-promise": { id: "5-s1-survivor-promise", type: "narrative", text: "'Morrison is going to prison. I've built cases for twenty years. This one is solid.' She studies your face. 'You really believe that?' 'I do.' It's not a lie. But you've seen juries before. Nothing is certain until the verdict.", nextNode: "5-s2" },

    // ========== STAGE 2: ON THE STAND ==========
    "5-s2": {
      id: "5-s2",
      type: "choice",
      text: "'The People call Detective Marcus Cole.' You walk to the stand, feeling the weight of every eye. Morrison sits at the defense table, expensive suit, practiced expression of wounded innocence. His lawyer - Richard Hayes, $2000 an hour - shuffles papers. You've faced killers. This is somehow worse.",
      question: "STAGE 2/5 — You're sworn in. The prosecutor begins. How do you start?",
      timerSeconds: 20,
      choices: [
        { id: 'a', text: "Establish your credentials methodically", nextNode: "5-s2-credentials", consequence: "Build authority..." },
        { id: 'b', text: "Jump straight to the evidence", nextNode: "5-s2-evidence", consequence: "Hit hard early..." },
        { id: 'c', text: "Humanize the investigation", nextNode: "5-s2-humanize", consequence: "Connect with jury..." },
        { id: 'd', text: "Make eye contact with Morrison", nextNode: "5-s2-death", consequence: "Let him know..." },
      ],
    },
    "5-s2-death": { id: "5-s2-death", type: "death", text: "You stare directly at Morrison as you answer questions. The jury notices. Defense objects - witness is attempting to intimidate defendant. The judge warns you. You do it again. 'Detective Cole, you are excused pending review of your conduct.' Your vendetta just became the story.", deathMessage: "Personal grudges don't belong in testimony." },
    "5-s2-credentials": {
      id: "5-s2-credentials",
      type: "choice",
      text: "'Twenty years with the department. Over 200 major crime investigations. Expert witness certification in forensic evidence analysis.' The jury is listening. You're not just a cop - you're THE cop. The one who brought down the island.",
      question: "The prosecutor asks about your role. How do you frame it?",
      timerSeconds: 20,
      choices: [
        { id: 'a', text: "Focus on the methodical investigation", nextNode: "5-s2-credentials-method", consequence: "Professional..." },
        { id: 'b', text: "Emphasize the multi-agency cooperation", nextNode: "5-s2-credentials-team", consequence: "Bigger than one person..." },
        { id: 'c', text: "Highlight key discoveries you made", nextNode: "5-s2-credentials-discoveries", consequence: "Your contributions..." },
        { id: 'd', text: "Describe the scale of the operation", nextNode: "5-s2-credentials-scale", consequence: "Massive conspiracy..." },
      ],
    },
    "5-s2-credentials-method": { id: "5-s2-credentials-method", type: "narrative", text: "'Every lead was documented. Every piece of evidence logged, verified, cross-referenced. We followed the facts wherever they led.' You see jurors nodding. This isn't a witch hunt. This is police work. The right way.", nextNode: "5-s3" },
    "5-s2-credentials-team": { id: "5-s2-credentials-team", type: "narrative", text: "'FBI, local PD, Coast Guard, international partners. This wasn't my investigation - it was everyone's. Dozens of professionals, all reaching the same conclusion.' The implication is clear: if everyone agrees, it's not bias. It's truth.", nextNode: "5-s3", document: { title: "TEAM_TESTIMONY.pdf", preview: "Multi-agency cooperation emphasized. Credibility established...", pdfUrl: "/documents/team.pdf" } },
    "5-s2-credentials-discoveries": { id: "5-s2-credentials-discoveries", type: "narrative", text: "'I found the connection between Meridian Holdings and the defendant's personal accounts. I identified the flight patterns that proved regular visits. I interviewed forty-seven witnesses.' Specific. Concrete. Undeniable.", nextNode: "5-s3" },
    "5-s2-credentials-scale": { id: "5-s2-credentials-scale", type: "narrative", text: "'Fourteen victims rescued. Forty-seven identified from records. Assets in twelve countries. This wasn't a crime - it was an industry. And the defendant was at its center.' The jury's faces harden. Good. They need to understand the scope.", nextNode: "5-s3" },
    "5-s2-evidence": {
      id: "5-s2-evidence",
      type: "choice",
      text: "The prosecutor moves to evidence. Photographs appear on the courtroom screens. Financial records. Flight logs. And then - the surveillance footage. Morrison, on camera, walking through the island compound. Victims visible in the background.",
      question: "How do you present the key evidence?",
      timerSeconds: 20,
      choices: [
        { id: 'a', text: "Walk through each piece chronologically", nextNode: "5-s2-evidence-chrono", consequence: "Build the story..." },
        { id: 'b', text: "Focus on the most damning items", nextNode: "5-s2-evidence-damning", consequence: "Hit the highlights..." },
        { id: 'c', text: "Explain the forensic verification", nextNode: "5-s2-evidence-forensic", consequence: "Prove it's real..." },
        { id: 'd', text: "Connect each piece to Morrison directly", nextNode: "5-s2-evidence-connect", consequence: "No deniability..." },
      ],
    },
    "5-s2-evidence-chrono": { id: "5-s2-evidence-chrono", type: "narrative", text: "'March 3rd: financial transfer. March 8th: flight to the island. March 12th: this photograph. March 15th: present during the escape.' Each piece builds on the last. By the time you're done, the timeline is a noose around Morrison's neck.", nextNode: "5-s3", document: { title: "EVIDENCE_TIMELINE.pdf", preview: "Chronological evidence presentation. Complete picture...", pdfUrl: "/documents/evidence-timeline.pdf" } },
    "5-s2-evidence-damning": { id: "5-s2-evidence-damning", type: "narrative", text: "'This video. Timestamp verified. Location verified. The defendant walks past three victims. He doesn't help them. He doesn't call police. He goes to dinner.' You let that sink in. Morrison's lawyer objects. Overruled. The damage is done.", nextNode: "5-s3" },
    "5-s2-evidence-forensic": { id: "5-s2-evidence-forensic", type: "narrative", text: "'Every frame analyzed for tampering. Metadata verified against server logs. Three independent labs confirmed authenticity.' You're preempting their deepfake defense. By the time Hayes tries it, the jury already knows it's desperate.", nextNode: "5-s3" },
    "5-s2-evidence-connect": { id: "5-s2-evidence-connect", type: "narrative", text: "'His fingerprints on documents in the island office. His DNA on items in the guest quarters. His voice on recorded phone calls discussing operations.' You hammer the connection. Not circumstantial. Direct. Personal. Undeniable.", nextNode: "5-s3" },
    "5-s2-humanize": {
      id: "5-s2-humanize",
      type: "choice",
      text: "The prosecutor asks about the victims. This is your chance to make the jury feel it - not just understand it.",
      question: "How do you humanize the investigation?",
      timerSeconds: 20,
      choices: [
        { id: 'a', text: "Describe finding the survivor's testimony", nextNode: "5-s2-humanize-survivor", consequence: "Her courage..." },
        { id: 'b', text: "Talk about the families you notified", nextNode: "5-s2-humanize-families", consequence: "The grief..." },
        { id: 'c', text: "Share the moment you knew the scope", nextNode: "5-s2-humanize-scope", consequence: "The horror..." },
        { id: 'd', text: "Describe the rescued victims", nextNode: "5-s2-humanize-rescued", consequence: "The relief..." },
      ],
    },
    "5-s2-humanize-survivor": { id: "5-s2-humanize-survivor", type: "narrative", text: "'She escaped by kayak. At night. Across miles of open ocean. Because she'd rather risk drowning than spend another day on that island.' Your voice catches. You let it. 'That's how bad it was. Death was preferable.' Juror 4 wipes her eyes.", nextNode: "5-s3" },
    "5-s2-humanize-families": { id: "5-s2-humanize-families", type: "narrative", text: "'I've made death notifications before. It never gets easier. But telling families their daughters were found alive after years of being presumed dead...' You pause. 'That I'll never forget.' The courtroom is absolutely silent.", nextNode: "5-s3", document: { title: "FAMILY_IMPACT.pdf", preview: "Family notifications documented. Emotional testimony...", pdfUrl: "/documents/families.pdf" } },
    "5-s2-humanize-scope": { id: "5-s2-humanize-scope", type: "narrative", text: "'The moment I understood. We found records going back fifteen years. Hundreds of victims. I went home that night and couldn't sleep. Couldn't eat. I have a daughter. Same age as some of them.' You see Morrison shift uncomfortably. Good.", nextNode: "5-s3" },
    "5-s2-humanize-rescued": { id: "5-s2-humanize-rescued", type: "narrative", text: "'When we breached the cottages, the first girl I saw thought we were there to hurt her. She was fifteen. Took us twenty minutes to convince her we were police. Twenty minutes to overcome what they'd done to her.' The jury understands now. This isn't abstract. It's real.", nextNode: "5-s3" },

    // ========== STAGE 3: CROSS-EXAMINATION ==========
    "5-s3": {
      id: "5-s3",
      type: "choice",
      text: "Richard Hayes approaches. $2000 an hour of legal expertise dedicated to one goal: destroying your credibility. 'Detective Cole. You've built quite a reputation on this case, haven't you? Book deal. Media appearances. A real celebrity.' The prosecutor objects. Overruled.",
      question: "STAGE 3/5 — Cross-examination begins. How do you handle Hayes?",
      timerSeconds: 20,
      choices: [
        { id: 'a', text: "Stay calm and factual", nextNode: "5-s3-calm", consequence: "Don't take the bait..." },
        { id: 'b', text: "Redirect to the evidence", nextNode: "5-s3-redirect", consequence: "Focus on facts..." },
        { id: 'c', text: "Acknowledge the attention, dismiss the implication", nextNode: "5-s3-acknowledge", consequence: "Honest but firm..." },
        { id: 'd', text: "Get defensive about your motives", nextNode: "5-s3-death", consequence: "Protect your reputation..." },
      ],
    },
    "5-s3-death": { id: "5-s3-death", type: "death", text: "'I didn't do this for fame!' Your voice rises. Hayes smiles - he wanted this reaction. 'So you admit there's fame to be had? And isn't it true your book advance was contingent on a conviction?' The jury sees an angry cop with financial motives. Reasonable doubt blooms.", deathMessage: "Never let a lawyer control your emotions." },
    "5-s3-calm": {
      id: "5-s3-calm",
      type: "choice",
      text: "'I've given interviews about trafficking awareness, yes. Any proceeds go to victim support organizations.' Your voice is steady. Hayes pivots. 'Let's talk about the Martinez case. Eight years ago. You arrested a man who was later exonerated.'",
      question: "He's bringing up your past. How do you respond?",
      timerSeconds: 20,
      choices: [
        { id: 'a', text: "Explain the circumstances", nextNode: "5-s3-calm-explain", consequence: "Context matters..." },
        { id: 'b', text: "Acknowledge the outcome, defend your process", nextNode: "5-s3-calm-defend", consequence: "I did my job..." },
        { id: 'c', text: "Point out the differences to this case", nextNode: "5-s3-calm-differ", consequence: "Apples and oranges..." },
        { id: 'd', text: "Ask what relevance it has", nextNode: "5-s3-calm-relevance", consequence: "Objection territory..." },
      ],
    },
    "5-s3-calm-explain": { id: "5-s3-calm-explain", type: "narrative", text: "'Martinez was arrested based on eyewitness testimony that was later recanted. There was no physical evidence connecting him to the crime. This case has physical evidence, financial records, surveillance footage, and multiple corroborating witnesses.' The contrast is clear. Hayes moves on.", nextNode: "5-s4" },
    "5-s3-calm-defend": { id: "5-s3-calm-defend", type: "narrative", text: "'I followed the evidence we had at the time. When new evidence emerged, the system worked correctly. That's what's supposed to happen.' You meet Hayes's eyes. 'I don't need defendants to be guilty. I need the truth. In this case, the truth is devastating.'", nextNode: "5-s4", document: { title: "CROSS_EXAM_NOTES.pdf", preview: "Martinez case addressed. Credibility intact...", pdfUrl: "/documents/cross-exam.pdf" } },
    "5-s3-calm-differ": { id: "5-s3-calm-differ", type: "narrative", text: "'Martinez had one eyewitness and no physical evidence. Your client has DNA evidence, financial records, flight logs, surveillance footage, victim testimony, and co-conspirator cooperation. Would you like me to list more differences?' Quiet laughter in the gallery. Hayes glares.", nextNode: "5-s4" },
    "5-s3-calm-relevance": { id: "5-s3-calm-relevance", type: "narrative", text: "'I'm not sure how a case from eight years ago with completely different circumstances relates to the evidence against Senator Morrison.' The prosecutor objects - relevance. Sustained. Hayes has to move on. Small victory.", nextNode: "5-s4" },
    "5-s3-redirect": {
      id: "5-s3-redirect",
      type: "choice",
      text: "'Let's focus on what matters - the evidence.' Hayes smiles. 'Indeed. Let's talk about the surveillance footage. Isn't it true that modern AI can create convincing fake videos?'",
      question: "He's pushing the deepfake defense. How do you counter?",
      timerSeconds: 20,
      choices: [
        { id: 'a', text: "Cite the forensic verification", nextNode: "5-s3-redirect-forensic", consequence: "Science says real..." },
        { id: 'b', text: "Explain the chain of custody", nextNode: "5-s3-redirect-custody", consequence: "No opportunity to fake..." },
        { id: 'c', text: "Point out corroborating evidence", nextNode: "5-s3-redirect-corroborate", consequence: "Multiple sources agree..." },
        { id: 'd', text: "Challenge him to prove it's fake", nextNode: "5-s3-redirect-challenge", consequence: "Put up or shut up..." },
      ],
    },
    "5-s3-redirect-forensic": { id: "5-s3-redirect-forensic", type: "narrative", text: "'Three independent labs analyzed that footage using six different forensic methods. No evidence of manipulation. No AI artifacts. No frame inconsistencies. If it's a fake, it's the most sophisticated one ever created - and no one can prove it.' Hayes has nothing.", nextNode: "5-s4", document: { title: "FORENSIC_VERIFICATION.pdf", preview: "Triple verification. Authentic footage confirmed...", pdfUrl: "/documents/forensic.pdf" } },
    "5-s3-redirect-custody": { id: "5-s3-redirect-custody", type: "narrative", text: "'The footage was recovered from servers on the island, immediately secured by FBI technicians, and has been under continuous chain of custody ever since. When exactly would someone have created a deepfake? The morning of the raid?'", nextNode: "5-s4" },
    "5-s3-redirect-corroborate": { id: "5-s3-redirect-corroborate", type: "narrative", text: "'The video shows Senator Morrison wearing a blue polo shirt on March 12th. His flight records show him traveling to the region. His credit card shows a purchase at the island gift shop. The survivor's testimony places him there. How many coincidences does the defense need?'", nextNode: "5-s4" },
    "5-s3-redirect-challenge": { id: "5-s3-redirect-challenge", type: "narrative", text: "'If counsel has evidence the footage is fabricated, I'd be happy to review it. Has the defense commissioned their own forensic analysis?' Hayes hesitates. 'We're... exploring options.' 'So that's a no.' The jury notices.", nextNode: "5-s4" },
    "5-s3-acknowledge": {
      id: "5-s3-acknowledge",
      type: "choice",
      text: "'Yes, this case has gotten attention. Fourteen victims rescued tends to make news. But I didn't seek it - I just did my job.' Hayes pounces. 'Your job. Let's talk about your job. Isn't it true you were passed over for promotion twice?'",
      question: "He's implying you have a grudge. How do you handle it?",
      timerSeconds: 20,
      choices: [
        { id: 'a', text: "Explain the circumstances honestly", nextNode: "5-s3-acknowledge-honest", consequence: "Nothing to hide..." },
        { id: 'b', text: "Question the relevance", nextNode: "5-s3-acknowledge-relevance", consequence: "What does this prove?" },
        { id: 'c', text: "Turn it into a positive", nextNode: "5-s3-acknowledge-positive", consequence: "Field work matters..." },
        { id: 'd', text: "Point out you were promoted after this case", nextNode: "5-s3-acknowledge-after", consequence: "Merit recognized..." },
      ],
    },
    "5-s3-acknowledge-honest": { id: "5-s3-acknowledge-honest", type: "narrative", text: "'I was passed over for administrative positions because I wanted to stay in the field. Desk jobs don't catch criminals. Is counsel suggesting I spent six months building a false case against Senator Morrison because I didn't want to become a captain?' The suggestion sounds absurd when you say it out loud.", nextNode: "5-s4" },
    "5-s3-acknowledge-relevance": { id: "5-s3-acknowledge-relevance", type: "narrative", text: "'What does my career trajectory have to do with DNA evidence and financial records? Is the defense arguing that my not being promoted somehow created the defendant's fingerprints on island documents?' Hayes backs off. He overreached.", nextNode: "5-s4", document: { title: "DEFENSE_TACTICS.pdf", preview: "Character attacks failing. Evidence focus restored...", pdfUrl: "/documents/tactics.pdf" } },
    "5-s3-acknowledge-positive": { id: "5-s3-acknowledge-positive", type: "narrative", text: "'I chose to stay in the field because that's where I can make a difference. Promotions come with paperwork. I'd rather be catching predators like...' You gesture at Morrison. Hayes objects. Sustained. But the jury saw where you were pointing.", nextNode: "5-s4" },
    "5-s3-acknowledge-after": { id: "5-s3-acknowledge-after", type: "narrative", text: "'Actually, I was offered a promotion after this case. I turned it down to see it through. Does that sound like someone with a grudge, or someone committed to justice?' Hayes has no follow-up. Next question.", nextNode: "5-s4" },

    // ========== STAGE 4: THE BOMBSHELL ==========
    "5-s4": {
      id: "5-s4",
      type: "choice",
      text: "Hayes is wrapping up when your phone buzzes. A text from Agent Chen: 'URGENT. New evidence. Judge Harrison connection confirmed. Morrison's people tried to fix the case.' This could change everything - but you're still on the stand.",
      question: "STAGE 4/5 — Critical new evidence. What do you do?",
      timerSeconds: 20,
      choices: [
        { id: 'a', text: "Signal the prosecutor discreetly", nextNode: "5-s4-signal", consequence: "She needs to know..." },
        { id: 'b', text: "Wait until you're off the stand", nextNode: "5-s4-wait", consequence: "Proper procedure..." },
        { id: 'c', text: "Request a brief recess", nextNode: "5-s4-recess", consequence: "Need to handle this..." },
        { id: 'd', text: "Blurt out the information", nextNode: "5-s4-death", consequence: "The jury needs to know..." },
      ],
    },
    "5-s4-death": { id: "5-s4-death", type: "death", text: "'Your Honor, I've just received evidence that Senator Morrison attempted to corrupt Judge Harrison!' The courtroom explodes. Hayes moves for mistrial. The judge is furious - testimony from the stand about evidence not yet admitted. Mistrial granted. Morrison walks free while the case is rebuilt - if it ever is.", deathMessage: "Procedure exists for a reason. You just destroyed the trial." },
    "5-s4-signal": {
      id: "5-s4-signal",
      type: "choice",
      text: "You catch ADA Chen's eye, tap your phone. She frowns, checks hers. Her eyes widen. She scribbles a note to her colleague. The wheels are turning.",
      question: "The prosecutor is informed. How does she proceed?",
      timerSeconds: 20,
      choices: [
        { id: 'a', text: "She asks for a sidebar", nextNode: "5-s4-signal-sidebar", consequence: "Private conference..." },
        { id: 'b', text: "She requests a recess", nextNode: "5-s4-signal-recess", consequence: "Time to verify..." },
        { id: 'c', text: "She continues normally, waits for redirect", nextNode: "5-s4-signal-redirect", consequence: "Introduce properly..." },
        { id: 'd', text: "She asks you about Judge Harrison directly", nextNode: "5-s4-signal-direct", consequence: "Open the door..." },
      ],
    },
    "5-s4-signal-sidebar": { id: "5-s4-signal-sidebar", type: "narrative", text: "Chen requests a sidebar. Whispered argument at the bench. The judge looks grim. 'We'll take a thirty-minute recess.' When court resumes, there's a new electricity in the air. Something's coming.", nextNode: "5-s5", document: { title: "SIDEBAR_NOTES.pdf", preview: "New evidence discussed. Judge approves introduction...", pdfUrl: "/documents/sidebar.pdf" } },
    "5-s4-signal-recess": { id: "5-s4-signal-recess", type: "narrative", text: "'Your Honor, the People request a brief recess.' Granted. In the hallway, Chen is on the phone with FBI. 'Harrison's been arrested. He's talking.' This case just got bigger. And Morrison just lost his last friend on the bench.", nextNode: "5-s5" },
    "5-s4-signal-redirect": { id: "5-s4-signal-redirect", type: "narrative", text: "Chen finishes cross-examination, then rises. 'Redirect, Your Honor.' She'll introduce the new evidence properly - through you, on the record, with foundation. The right way. Morrison's lawyers won't see it coming.", nextNode: "5-s5" },
    "5-s4-signal-direct": { id: "5-s4-signal-direct", type: "narrative", text: "'Detective, in your investigation, did you uncover any connections between the defendant and the judiciary?' Hayes objects. Chen has laid foundation. Overruled. 'Yes. Meridian Holdings made payments to Judge Harrison - the judge initially assigned to this case.' Gasps from the gallery.", nextNode: "5-s5", document: { title: "HARRISON_CONNECTION.pdf", preview: "Judicial corruption exposed. Major development...", pdfUrl: "/documents/harrison.pdf" } },
    "5-s4-wait": {
      id: "5-s4-wait",
      type: "choice",
      text: "You pocket your phone. Hayes asks a few more questions. 'No further questions.' You're excused. As you step down, Chen catches your eye. You need to talk - but Morrison's team is watching.",
      question: "How do you pass the information?",
      timerSeconds: 20,
      choices: [
        { id: 'a', text: "Meet her in the prosecutor's office", nextNode: "5-s4-wait-office", consequence: "Private setting..." },
        { id: 'b', text: "Pass a note as you walk by", nextNode: "5-s4-wait-note", consequence: "Discreet..." },
        { id: 'c', text: "Text her from outside the courtroom", nextNode: "5-s4-wait-text", consequence: "Digital trail..." },
        { id: 'd', text: "Wait until the lunch recess", nextNode: "5-s4-wait-lunch", consequence: "Natural break..." },
      ],
    },
    "5-s4-wait-office": { id: "5-s4-wait-office", type: "narrative", text: "In her office, you show her the message. 'Judge Harrison took money from Morrison's shell company. Tried to tank the case before he recused himself.' Chen sits down heavily. 'This explains his rulings on evidence suppression. We need to move fast.'", nextNode: "5-s5", document: { title: "OFFICE_BRIEFING.pdf", preview: "Full evidence reviewed. Strategy updated...", pdfUrl: "/documents/briefing.pdf" } },
    "5-s4-wait-note": { id: "5-s4-wait-note", type: "narrative", text: "You slip her a folded paper as you pass. 'Check your phone. Harrison.' She glances at it, pockets it smoothly. Later, she texts back: 'Getting warrants now. This is huge.'", nextNode: "5-s5" },
    "5-s4-wait-text": { id: "5-s4-wait-text", type: "narrative", text: "Outside, you forward Agent Chen's message to the prosecutor. Her reply is immediate: 'Don't talk to anyone. Coming to you now.' Twenty minutes later, you're in a secured room, planning how to introduce this bombshell.", nextNode: "5-s5" },
    "5-s4-wait-lunch": { id: "5-s4-wait-lunch", type: "narrative", text: "At lunch, you find Chen in the cafeteria. 'We have a problem. Or an opportunity.' You show her. Her sandwich goes untouched. 'This could be obstruction, witness tampering, judicial corruption... Morrison's going away forever.'", nextNode: "5-s5" },
    "5-s4-recess": {
      id: "5-s4-recess",
      type: "choice",
      text: "'Your Honor, may I request a brief recess? I'm not feeling well.' The judge eyes you. Hayes objects. But judges tend to accommodate witnesses. 'Fifteen minutes.' You step down, phone already in hand.",
      question: "You have fifteen minutes. What's the priority?",
      timerSeconds: 20,
      choices: [
        { id: 'a', text: "Call Agent Chen for details", nextNode: "5-s4-recess-call", consequence: "Get the full picture..." },
        { id: 'b', text: "Brief the prosecutor immediately", nextNode: "5-s4-recess-prosecutor", consequence: "She decides next steps..." },
        { id: 'c', text: "Verify the evidence yourself", nextNode: "5-s4-recess-verify", consequence: "Trust but verify..." },
        { id: 'd', text: "Alert courthouse security", nextNode: "5-s4-recess-security", consequence: "If Harrison's dirty, who else?" },
      ],
    },
    "5-s4-recess-call": { id: "5-s4-recess-call", type: "narrative", text: "'Marcus, we have Harrison dead to rights. Bank records, emails, recorded conversations. He was going to dismiss the case on technicalities. Morrison paid him $2 million.' You lean against the wall. Two million to let a monster walk. Now they both burn.", nextNode: "5-s5", document: { title: "HARRISON_EVIDENCE.pdf", preview: "Full corruption case detailed. $2M payment confirmed...", pdfUrl: "/documents/harrison-evidence.pdf" } },
    "5-s4-recess-prosecutor": { id: "5-s4-recess-prosecutor", type: "narrative", text: "Chen reads the message. Her face cycles through shock, anger, determination. 'This is why Harrison kept trying to suppress evidence. He was bought.' She starts making calls. 'We're introducing this today. No more surprises.'", nextNode: "5-s5" },
    "5-s4-recess-verify": { id: "5-s4-recess-verify", type: "narrative", text: "You call the FBI field office. 'The Harrison thing - is it solid?' 'Rock solid. We have the wire transfer, his signature on Meridian documents, and a cooperating witness who arranged the meetings.' Good enough. Now to use it.", nextNode: "5-s5" },
    "5-s4-recess-security": { id: "5-s4-recess-security", type: "narrative", text: "You find the head of courthouse security. 'We may have a compromised judge situation. Harrison was on Morrison's payroll.' He doesn't ask questions - just starts making calls. 'I'll have extra eyes on every exit. No one leaves without clearance.'", nextNode: "5-s5" },

    // ========== STAGE 5: THE VERDICT ==========
    "5-s5": {
      id: "5-s5",
      type: "choice",
      text: "The Harrison revelation rocks the courtroom. Morrison's defense scrambles. New motions, accusations of prosecutorial misconduct, demands for mistrial. But the judge - the new judge, untainted - denies everything. After two more days of testimony, the jury retires. You wait in the hallway. Hours pass.",
      question: "STAGE 5/5 — Waiting for the verdict. How do you spend the time?",
      timerSeconds: 20,
      choices: [
        { id: 'a', text: "Wait with the survivor", nextNode: "5-s5-survivor", consequence: "She needs support..." },
        { id: 'b', text: "Review case files for any loose ends", nextNode: "5-s5-files", consequence: "Never stop working..." },
        { id: 'c', text: "Coordinate with agents outside", nextNode: "5-s5-agents", consequence: "Security matters..." },
        { id: 'd', text: "Confront Morrison one last time", nextNode: "5-s5-death", consequence: "Look him in the eye..." },
      ],
    },
    "5-s5-death": { id: "5-s5-death", type: "death", text: "You corner Morrison in the men's room. 'Guilty or not guilty, I want you to know - I'll be watching you forever.' He smiles. 'Recorded that, Detective. Witness intimidation.' Hayes is already calling for sanctions. The verdict becomes secondary to your misconduct hearing.", deathMessage: "You never learn. Justice isn't personal." },
    "5-s5-survivor": {
      id: "5-s5-survivor",
      type: "choice",
      text: "She's sitting alone in the witness room. Still guarded, but the FBI agents have given her space. She looks up when you enter. 'Any news?' 'Jury's still out. Could be hours.' 'Or minutes.' 'Or minutes.'",
      question: "How do you wait with her?",
      timerSeconds: 20,
      choices: [
        { id: 'a', text: "Talk about what comes next", nextNode: "5-s5-survivor-next", consequence: "After the verdict..." },
        { id: 'b', text: "Share stories about other cases", nextNode: "5-s5-survivor-stories", consequence: "You're not alone..." },
        { id: 'c', text: "Sit in comfortable silence", nextNode: "5-s5-survivor-silence", consequence: "Words aren't needed..." },
        { id: 'd', text: "Ask how she's really doing", nextNode: "5-s5-survivor-truth", consequence: "Honest conversation..." },
      ],
    },
    "5-s5-survivor-next": { id: "5-s5-survivor-next", type: "narrative", text: "'Whatever happens, you've already won. You survived. You testified. Your courage has changed laws.' She shakes her head. 'I don't feel courageous. I feel tired.' 'That's what courage feels like, mostly. Tired and scared and doing it anyway.'", nextNode: "5-complete" },
    "5-s5-survivor-stories": { id: "5-s5-survivor-stories", type: "narrative", text: "You tell her about other survivors you've worked with. Where they are now. The families they've built. The lives they've reclaimed. 'It takes time. But people come back from this.' 'Did they all testify?' 'The brave ones did.'", nextNode: "5-complete" },
    "5-s5-survivor-silence": { id: "5-s5-survivor-silence", type: "narrative", text: "You sit across from her. Neither of you speaks. The clock ticks. Outside, you can hear the murmur of the courthouse. It's oddly peaceful. She closes her eyes. You watch the door. This is what protection looks like sometimes. Just being there.", nextNode: "5-complete", document: { title: "WITNESS_SUPPORT_LOG.pdf", preview: "Survivor supported through verdict wait. Stable condition...", pdfUrl: "/documents/support-log.pdf" } },
    "5-s5-survivor-truth": { id: "5-s5-survivor-truth", type: "narrative", text: "'Honestly? Terrified. If he walks...' She can't finish. 'He won't.' You say it with more confidence than you feel. 'The evidence is overwhelming.' 'Evidence doesn't always matter.' 'It matters today. I promise.' Some promises you have to make, even if you can't guarantee them.", nextNode: "5-complete" },
    "5-s5-files": {
      id: "5-s5-files",
      type: "choice",
      text: "Your case files are in the prosecutor's office. Something's been nagging at you - a loose thread you never fully pulled.",
      question: "What do you review?",
      timerSeconds: 20,
      choices: [
        { id: 'a', text: "Financial records for more connections", nextNode: "5-s5-files-money", consequence: "Who else was paid?" },
        { id: 'b', text: "Witness statements for inconsistencies", nextNode: "5-s5-files-witnesses", consequence: "Who's lying?" },
        { id: 'c', text: "Evidence logs for anything missed", nextNode: "5-s5-files-evidence", consequence: "What did we miss?" },
        { id: 'd', text: "Morrison's background for other crimes", nextNode: "5-s5-files-background", consequence: "Is this his first?" },
      ],
    },
    "5-s5-files-money": { id: "5-s5-files-money", type: "narrative", text: "You find another payment. Different shell company, same pattern. Recipient: a journalist who wrote favorable articles about Morrison. 'Add it to the pile,' Chen says when you show her. Even if he walks today, the investigations will never stop.", nextNode: "5-complete", document: { title: "JOURNALIST_PAYMENT.pdf", preview: "Additional corruption identified. Investigation expanding...", pdfUrl: "/documents/journalist-payment.pdf" } },
    "5-s5-files-witnesses": { id: "5-s5-files-witnesses", type: "narrative", text: "Guard Torres's timeline doesn't match the helicopter logs. You already knew this. But now you see why - he was covering for someone else on the island that night. Someone whose name you recognize. Another case, another day. The work never ends.", nextNode: "5-complete" },
    "5-s5-files-evidence": { id: "5-s5-files-evidence", type: "narrative", text: "Nothing missed. You're thorough - that's why they called you. Every piece of evidence catalogued, verified, presented. Whatever the jury decides, it won't be because you didn't do your job.", nextNode: "5-complete" },
    "5-s5-files-background": { id: "5-s5-files-background", type: "narrative", text: "Morrison's past: rumors, settled lawsuits, accusations that went nowhere. Always enough money to make problems disappear. Until now. You're the one who didn't take the money. Didn't back off. Didn't disappear. That matters.", nextNode: "5-complete" },
    "5-s5-agents": {
      id: "5-s5-agents",
      type: "choice",
      text: "FBI agents are positioned at every exit. If Morrison is acquitted, he walks free. If he's convicted, he might try to run before sentencing. Either way, you want eyes everywhere.",
      question: "What security concerns do you address?",
      timerSeconds: 20,
      choices: [
        { id: 'a', text: "Check on the witness protection detail", nextNode: "5-s5-agents-witness", consequence: "Survivor's safety..." },
        { id: 'b', text: "Verify Morrison's surveillance", nextNode: "5-s5-agents-morrison", consequence: "He's still dangerous..." },
        { id: 'c', text: "Coordinate with courthouse security", nextNode: "5-s5-agents-courthouse", consequence: "No surprises..." },
        { id: 'd', text: "Review escape route protocols", nextNode: "5-s5-agents-escape", consequence: "If he runs..." },
      ],
    },
    "5-s5-agents-witness": { id: "5-s5-agents-witness", type: "narrative", text: "The survivor's protection detail is solid. Four agents, rotating shifts, secure transport arranged. Whatever happens in that courtroom, she'll be safe. You made that promise. You keep your promises.", nextNode: "5-complete" },
    "5-s5-agents-morrison": { id: "5-s5-agents-morrison", type: "narrative", text: "'If he walks, we have units ready to follow. If he runs, we have warrants for the passport.' Agent Chen is thorough. 'Either way, we're not done with him. Harrison flipped. Named names. Morrison's just the beginning.'", nextNode: "5-complete", document: { title: "SURVEILLANCE_PLAN.pdf", preview: "Morrison monitoring active. All contingencies covered...", pdfUrl: "/documents/surveillance-plan.pdf" } },
    "5-s5-agents-courthouse": { id: "5-s5-agents-courthouse", type: "narrative", text: "Every entrance covered. Metal detectors working. Armed response standing by. 'We've had threats,' security chief tells you. 'Morrison's supporters aren't happy.' 'Morrison's supporters can file a complaint.' After the guilty verdict.", nextNode: "5-complete" },
    "5-s5-agents-escape": { id: "5-s5-agents-escape", type: "narrative", text: "'If he tries to run?' 'We've got his jet grounded, accounts frozen, and Mexican authorities notified. He's not getting to the Caymans.' For once, the system is working. Rich people go to prison too. Sometimes.", nextNode: "5-complete" },

    // ========== CHAPTER 5 COMPLETE ==========
    "5-complete": {
      id: "5-complete",
      type: "chapter-end",
      text: "The bailiff emerges. 'Jury's back.' The courtroom fills. Morrison stands, still projecting confidence. The foreman rises. 'On the count of human trafficking: guilty. On the count of conspiracy: guilty. On the count of obstruction of justice: guilty.' Fourteen counts. Fourteen guilty verdicts. Morrison sways. His lawyer catches him. The survivor gasps, then sobs. You feel... empty. Not triumphant. Just tired. Twenty years of this work, and you've never gotten used to the weight of it. Justice was served today. But the victims are still victims. The dead are still dead. Tomorrow, there'll be another case. Another monster. Another chance to do what's right. That's the job. You head for the exit, already thinking about the next one.",
      chapterComplete: {
        chapter: 5,
        nextChapter: 6,
        summary: "The trial concluded with guilty verdicts on all counts. Senator Morrison faces life in prison. But the investigation continues - Harrison named names, and the conspiracy runs deeper than anyone knew."
      },
    },
  },
};