import { BranchingChapter } from '../types';

export const CHAPTER_3: BranchingChapter = {
  id: 3, title: "CHAPTER 3", subtitle: "The Escape", startNode: "3-s1",
  nodes: {
    // STAGE 1: CHASE BEGINS
    "3-s1": { id: "3-s1", type: "choice", text: "Alarms blaring. Searchlights sweeping. Dogs barking closer. Helicopter spinning up. They know you're out. Northern cliffs ahead, marina below.", question: "STAGE 1/5 — How proceed?", timerSeconds: 20,
      choices: [
        { id: 'a', text: "Sprint for marina", nextNode: "3-s1-death", consequence: "Speed..." },
        { id: 'b', text: "Climb down cliffs", nextNode: "3-s1-cliffs", consequence: "Unexpected..." },
        { id: 'c', text: "Circle through jungle", nextNode: "3-s1-jungle", consequence: "Cover..." },
        { id: 'd', text: "Sabotage helicopter", nextNode: "3-s1-heli", consequence: "Air support..." },
      ],
    },
    "3-s1-death": { id: "3-s1-death", type: "death", text: "Sprint open ground. Searchlight at 200 yards. Dogs. Guards. 'Fastest capture. Under 3 minutes.'", deathMessage: "Running in open was suicide." },
    "3-s1-cliffs": { id: "3-s1-cliffs", type: "choice", text: "Cliff edge. 50 feet down, weathered rock with handholds. Helicopter passes overhead as you descend.", question: "Climbing down.", timerSeconds: 20,
      choices: [
        { id: 'a', text: "Fast descent - risk it", nextNode: "3-s1-cliffs-fast", consequence: "Speed matters..." },
        { id: 'b', text: "Slow and careful", nextNode: "3-s1-cliffs-slow", consequence: "Safe..." },
        { id: 'c', text: "Wait for searchlight to pass", nextNode: "3-s1-cliffs-wait", consequence: "Timing..." },
        { id: 'd', text: "Jump into water below", nextNode: "3-s1-cliffs-death", consequence: "Fastest..." },
      ],
    },
    "3-s1-cliffs-death": { id: "3-s1-cliffs-death", type: "death", text: "50-foot drop. Even water can kill from this height. Impact. Darkness.", deathMessage: "Too high to jump." },
    "3-s1-cliffs-fast": { id: "3-s1-cliffs-fast", type: "narrative", text: "Speed over caution. Hands bleeding, muscles screaming. You reach the cove. Kayaks waiting.", nextNode: "3-s2" },
    "3-s1-cliffs-slow": { id: "3-s1-cliffs-slow", type: "narrative", text: "Methodical. Test each handhold. Helicopter passes twice without seeing you. Cove reached intact.", nextNode: "3-s2", document: { title: "CLIFF_ROUTE.pdf", preview: "Safe descent achieved...", pdfUrl: "/documents/cliff.pdf" } },
    "3-s1-cliffs-wait": { id: "3-s1-cliffs-wait", type: "narrative", text: "Press against rock when light sweeps. Move between passes. Slower but invisible.", nextNode: "3-s2" },
    "3-s1-jungle": { id: "3-s1-jungle", type: "choice", text: "Into the jungle. Branches tear skin. Sounds of pursuit fade behind. Through gaps - marina lights.", question: "Moving through jungle.", timerSeconds: 20,
      choices: [
        { id: 'a', text: "Parallel to coast", nextNode: "3-s1-jungle-coast", consequence: "Keep ocean close..." },
        { id: 'b', text: "Deeper into trees", nextNode: "3-s1-jungle-deep", consequence: "Maximum cover..." },
        { id: 'c', text: "Follow animal trails", nextNode: "3-s1-jungle-trails", consequence: "Easier path..." },
        { id: 'd', text: "Run straight through", nextNode: "3-s1-jungle-death", consequence: "Direct..." },
      ],
    },
    "3-s1-jungle-death": { id: "3-s1-jungle-death", type: "death", text: "Running blind. Trip on root. Fall into gully. Ankle snaps. They find you within minutes.", deathMessage: "Rushing through unknown terrain." },
    "3-s1-jungle-coast": { id: "3-s1-jungle-coast", type: "narrative", text: "Ocean sound your guide. Emerge near storage building. Jet ski visible, keys in ignition.", nextNode: "3-s2" },
    "3-s1-jungle-deep": { id: "3-s1-jungle-deep", type: "narrative", text: "Deep into trees. Pursuit goes elsewhere. You circle back unseen. Marina clear approach.", nextNode: "3-s2", document: { title: "JUNGLE_ROUTE.pdf", preview: "Deep cover worked...", pdfUrl: "/documents/jungle.pdf" } },
    "3-s1-jungle-trails": { id: "3-s1-jungle-trails", type: "narrative", text: "Animal trails wind but move fast. You reach the marina perimeter ahead of any sweep.", nextNode: "3-s2" },
    "3-s1-heli": { id: "3-s1-heli", type: "choice", text: "Helipad. Pilot pre-flight, back turned. Fuel line accessible. Tail rotor exposed.", question: "Sabotage method?", timerSeconds: 20,
      choices: [
        { id: 'a', text: "Cut fuel line", nextNode: "3-s1-heli-fuel", consequence: "No fuel..." },
        { id: 'b', text: "Damage tail rotor", nextNode: "3-s1-heli-rotor", consequence: "Unsafe..." },
        { id: 'c', text: "Sever control cable", nextNode: "3-s1-heli-cable", consequence: "Subtle..." },
        { id: 'd', text: "Attack pilot directly", nextNode: "3-s1-heli-death", consequence: "Take control..." },
      ],
    },
    "3-s1-heli-death": { id: "3-s1-heli-death", type: "death", text: "Ex-military pilot. Helicopters have mirrors. He spins, catches arm, flips you. 'Nice try. Most go for fuel.'", deathMessage: "Pilot was combat-trained." },
    "3-s1-heli-fuel": { id: "3-s1-heli-fuel", type: "narrative", text: "Blade through fuel line. Aviation fuel spills. Pilot curses, kills engine. 'Ground it!' Eye in sky closed.", nextNode: "3-s2" },
    "3-s1-heli-rotor": { id: "3-s1-heli-rotor", type: "narrative", text: "Blade jammed in mechanism. Pilot lifts, gets 100 feet. Alarms. Hard landing. 'Mechanical failure!'", nextNode: "3-s2" },
    "3-s1-heli-cable": { id: "3-s1-heli-cable", type: "narrative", text: "Control cable partially severed. Lifts, lurches, yaws wildly. Emergency landing. 'Grounded!' Damage looks like fatigue.", nextNode: "3-s2", document: { title: "HELI_SABOTAGE.pdf", preview: "Control cable severed...", pdfUrl: "/documents/heli.pdf" } },

    // STAGE 2: WATER
    "3-s2": { id: "3-s2", type: "choice", text: "Waterline. Ocean dark and choppy. Mainland lights 5 miles out. Kayak in cove, jet ski near marina, sailboat moored further.", question: "STAGE 2/5 — How cross?", timerSeconds: 20,
      choices: [
        { id: 'a', text: "Kayak - silent", nextNode: "3-s2-kayak", consequence: "Quiet..." },
        { id: 'b', text: "Jet ski - fast", nextNode: "3-s2-jetski", consequence: "Speed..." },
        { id: 'c', text: "Swim to sailboat", nextNode: "3-s2-sail", consequence: "Better vessel..." },
        { id: 'd', text: "Signal passing boat", nextNode: "3-s2-death", consequence: "Help..." },
      ],
    },
    "3-s2-death": { id: "3-s2-death", type: "death", text: "Wave at approaching boat. It slows. Island security logo. 'Our missing guest.'", deathMessage: "That was island patrol." },
    "3-s2-kayak": { id: "3-s2-kayak", type: "choice", text: "Light, quick. No engine noise. Paddle into darkness.", question: "Kayak approach?", timerSeconds: 20,
      choices: [
        { id: 'a', text: "Steady pace - conserve energy", nextNode: "3-s2-kayak-a", consequence: "Marathon..." },
        { id: 'b', text: "Sprint bursts when waves help", nextNode: "3-s2-kayak-b", consequence: "Use nature..." },
        { id: 'c', text: "Hug the coastline further", nextNode: "3-s2-kayak-c", consequence: "More cover..." },
        { id: 'd', text: "Straight line to mainland", nextNode: "3-s2-kayak-d", consequence: "Direct..." },
      ],
    },
    "3-s2-kayak-a": { id: "3-s2-kayak-a", type: "narrative", text: "Steady rhythm. Arms burn but last. Island shrinks. Mainland grows.", nextNode: "3-s3" },
    "3-s2-kayak-b": { id: "3-s2-kayak-b", type: "narrative", text: "Ride the swells. Nature helps when you work with it. Progress faster than expected.", nextNode: "3-s3", document: { title: "KAYAK_SUCCESS.pdf", preview: "Wave timing worked...", pdfUrl: "/documents/kayak.pdf" } },
    "3-s2-kayak-c": { id: "3-s2-kayak-c", type: "narrative", text: "Coastline provides reference and partial cover. Longer but safer.", nextNode: "3-s3" },
    "3-s2-kayak-d": { id: "3-s2-kayak-d", type: "narrative", text: "Beeline for lights. Most exposed but fastest. You commit.", nextNode: "3-s3" },
    "3-s2-jetski": { id: "3-s2-jetski", type: "choice", text: "Engine roars. Spray flies. Shots fired wide. Speedboat gives chase.", question: "Being pursued.", timerSeconds: 20,
      choices: [
        { id: 'a', text: "Weave through rocks", nextNode: "3-s2-jetski-a", consequence: "They can't follow..." },
        { id: 'b', text: "Open water speed run", nextNode: "3-s2-jetski-b", consequence: "Outrun..." },
        { id: 'c', text: "Cut zigzags", nextNode: "3-s2-jetski-c", consequence: "Hard to hit..." },
        { id: 'd', text: "Turn back at them", nextNode: "3-s2-jetski-death", consequence: "Surprise..." },
      ],
    },
    "3-s2-jetski-death": { id: "3-s2-jetski-death", type: "death", text: "Turn into their path. Bigger boat wins chicken. They don't swerve.", deathMessage: "Speedboat called your bluff." },
    "3-s2-jetski-a": { id: "3-s2-jetski-a", type: "narrative", text: "Cut through rock formations. They can't follow. Emerge with clean lead.", nextNode: "3-s3", document: { title: "ROCKS_ESCAPE.pdf", preview: "Rock navigation succeeded...", pdfUrl: "/documents/rocks.pdf" } },
    "3-s2-jetski-b": { id: "3-s2-jetski-b", type: "narrative", text: "Full throttle. They're faster but you have a head start. Distance matters.", nextNode: "3-s3" },
    "3-s2-jetski-c": { id: "3-s2-jetski-c", type: "narrative", text: "Random zigzags. Shots go wide. They can't anticipate. Gap widens.", nextNode: "3-s3" },
    "3-s2-sail": { id: "3-s2-sail", type: "choice", text: "Brutal swim. Cold, current. Haul aboard 30-footer. Engine starts. Below deck: supplies.", question: "Sailboat prep.", timerSeconds: 20,
      choices: [
        { id: 'a', text: "Go immediately", nextNode: "3-s2-sail-a", consequence: "Every second..." },
        { id: 'b', text: "Check supplies first", nextNode: "3-s2-sail-b", consequence: "Prepare..." },
        { id: 'c', text: "Raise sail instead of engine", nextNode: "3-s2-sail-c", consequence: "Silent..." },
        { id: 'd', text: "Radio for help first", nextNode: "3-s2-sail-d", consequence: "Call out..." },
      ],
    },
    "3-s2-sail-a": { id: "3-s2-sail-a", type: "narrative", text: "No time to waste. Engine full. Point toward mainland lights. Go.", nextNode: "3-s3" },
    "3-s2-sail-b": { id: "3-s2-sail-b", type: "narrative", text: "Food, water, first aid, flare gun. You're equipped. Now go.", nextNode: "3-s3", document: { title: "BOAT_SUPPLIES.pdf", preview: "Equipment found...", pdfUrl: "/documents/supplies.pdf" } },
    "3-s2-sail-c": { id: "3-s2-sail-c", type: "narrative", text: "Sail up, engine off. Silent and slower but invisible to listening ears.", nextNode: "3-s3" },
    "3-s2-sail-d": { id: "3-s2-sail-d", type: "narrative", text: "VHF radio: 'Coast Guard? Escaping island. Trafficking. Need help.' Static. Then: 'Copy. Give position.'", nextNode: "3-s3" },

    // STAGE 3: PURSUIT
    "3-s3": { id: "3-s3", type: "choice", text: "Speedboat in your wake. Armed figures. Mainland 3 miles. Storm clouds ahead. Can't outrun straight.", question: "STAGE 3/5 — Lose them?", timerSeconds: 20,
      choices: [
        { id: 'a', text: "Head into storm", nextNode: "3-s3-storm", consequence: "They might not follow..." },
        { id: 'b', text: "Cut engine, drift dark", nextNode: "3-s3-drift", consequence: "Lose visual..." },
        { id: 'c', text: "Send mayday", nextNode: "3-s3-mayday", consequence: "Call for help..." },
        { id: 'd', text: "Turn and confront", nextNode: "3-s3-death", consequence: "Surprise..." },
      ],
    },
    "3-s3-death": { id: "3-s3-death", type: "death", text: "Turn to face them. Bigger boat, armed crew, professionals. Alongside before you can react. 'Brave. Stupid.'", deathMessage: "Your vessel vs armed speedboat." },
    "3-s3-storm": { id: "3-s3-storm", type: "choice", text: "Into the storm. Rain like bullets. Waves toss you. Speedboat hesitates.", question: "In the storm.", timerSeconds: 20,
      choices: [
        { id: 'a', text: "Push through to other side", nextNode: "3-s3-storm-a", consequence: "Fight through..." },
        { id: 'b', text: "Ride it parallel", nextNode: "3-s3-storm-b", consequence: "Use but not fight..." },
        { id: 'c', text: "Find the calm eye", nextNode: "3-s3-storm-c", consequence: "Center..." },
        { id: 'd', text: "Turn back before it gets worse", nextNode: "3-s3-storm-death", consequence: "Retreat..." },
      ],
    },
    "3-s3-storm-death": { id: "3-s3-storm-death", type: "death", text: "Turn back into their arms. Storm scared them less than losing you.", deathMessage: "They waited at the edge." },
    "3-s3-storm-a": { id: "3-s3-storm-a", type: "narrative", text: "Fight the sea itself for an hour. Bailing water. Clinging to anything solid. Storm passes. Island distant. Mainland close.", nextNode: "3-s4" },
    "3-s3-storm-b": { id: "3-s3-storm-b", type: "narrative", text: "Let storm push you parallel to coast. Free energy. Emerge miles from where they expect.", nextNode: "3-s4", document: { title: "STORM_TACTICS.pdf", preview: "Rode storm successfully...", pdfUrl: "/documents/storm.pdf" } },
    "3-s3-storm-c": { id: "3-s3-storm-c", type: "narrative", text: "Eye of storm is calm. You wait. They can't find you. Storm moves, you move.", nextNode: "3-s4" },
    "3-s3-drift": { id: "3-s3-drift", type: "choice", text: "Everything off. Drift in darkness. Speedboat passes 100 yards left.", question: "They're looking.", timerSeconds: 20,
      choices: [
        { id: 'a', text: "Hold absolutely still", nextNode: "3-s3-drift-a", consequence: "Don't breathe..." },
        { id: 'b', text: "Sink lower in boat", nextNode: "3-s3-drift-b", consequence: "Smaller profile..." },
        { id: 'c', text: "Drift with current away", nextNode: "3-s3-drift-c", consequence: "Let sea help..." },
        { id: 'd', text: "Start engine when they pass", nextNode: "3-s3-drift-death", consequence: "Quick escape..." },
      ],
    },
    "3-s3-drift-death": { id: "3-s3-drift-death", type: "death", text: "Engine sound. They spin. 'There!' Should have waited longer.", deathMessage: "Engine sound gave you away." },
    "3-s3-drift-a": { id: "3-s3-drift-a", type: "narrative", text: "Not a movement. 'Lost visual. Expanding search.' Wrong direction. Ten minutes. Restart. Run.", nextNode: "3-s4" },
    "3-s3-drift-b": { id: "3-s3-drift-b", type: "narrative", text: "Flat in the boat. Searchlight passes over. Nothing to see. 'Negative contact.'", nextNode: "3-s4", document: { title: "DRIFT_ESCAPE.pdf", preview: "Silent drift worked...", pdfUrl: "/documents/drift.pdf" } },
    "3-s3-drift-c": { id: "3-s3-drift-c", type: "narrative", text: "Current takes you southeast while they search northeast. Free distance.", nextNode: "3-s4" },
    "3-s3-mayday": { id: "3-s3-mayday", type: "choice", text: "'Mayday. Kidnapping victim. Armed pursuers.' Static. Then: 'Coast Guard Steadfast. Position?'", question: "Coast Guard responds.", timerSeconds: 20,
      choices: [
        { id: 'a', text: "Give exact GPS coordinates", nextNode: "3-s3-mayday-a", consequence: "Precise..." },
        { id: 'b', text: "Describe visual landmarks", nextNode: "3-s3-mayday-b", consequence: "They can find you..." },
        { id: 'c', text: "Keep channel open for them", nextNode: "3-s3-mayday-c", consequence: "Homing..." },
        { id: 'd', text: "Tell them to hurry, go silent", nextNode: "3-s3-mayday-d", consequence: "Not give away..." },
      ],
    },
    "3-s3-mayday-a": { id: "3-s3-mayday-a", type: "narrative", text: "GPS read off. 'En route. ETA 30 minutes.' Speedboat veers away - they heard too.", nextNode: "3-s4", document: { title: "COAST_GUARD.pdf", preview: "Help dispatched...", pdfUrl: "/documents/cg.pdf" } },
    "3-s3-mayday-b": { id: "3-s3-mayday-b", type: "narrative", text: "'Northeast of island, heading mainland.' 'Copy. Deploying assets.' Cavalry coming.", nextNode: "3-s4" },
    "3-s3-mayday-c": { id: "3-s3-mayday-c", type: "narrative", text: "Open channel lets them track. Speedboat realizes official help is coming. They break off.", nextNode: "3-s4" },
    "3-s3-mayday-d": { id: "3-s3-mayday-d", type: "narrative", text: "'Hurrying. Stay safe.' Radio off. You hope they got enough. Keep moving.", nextNode: "3-s4" },

    // STAGE 4: LANDFALL
    "3-s4": { id: "3-s4", type: "choice", text: "Less than a mile. Town lights. Fishing pier. Police station sign. Exhausted, maybe hypothermic.", question: "STAGE 4/5 — Make landfall?", timerSeconds: 20,
      choices: [
        { id: 'a', text: "Police station pier", nextNode: "3-s4-police", consequence: "Official help..." },
        { id: 'b', text: "Fishing pier", nextNode: "3-s4-fishing", consequence: "Less visible..." },
        { id: 'c', text: "Beach it and run", nextNode: "3-s4-beach", consequence: "Land first..." },
        { id: 'd', text: "Circle back to check pursuit", nextNode: "3-s4-death", consequence: "Make sure clear..." },
      ],
    },
    "3-s4-death": { id: "3-s4-death", type: "death", text: "Turn to check behind. Second speedboat from coastline. Flanking. 'Got this close. Cruelest part.'", deathMessage: "Second boat waiting." },
    "3-s4-police": { id: "3-s4-police", type: "choice", text: "Police pier. Stumble onto dock. Collapse into officer's arms.", question: "First words?", timerSeconds: 20,
      choices: [
        { id: 'a', text: "'Trafficking island... help...'", nextNode: "3-s4-police-a", consequence: "Direct..." },
        { id: 'b', text: "'FBI... now... please...'", nextNode: "3-s4-police-b", consequence: "Federal..." },
        { id: 'c', text: "'Keep me safe... they're coming...'", nextNode: "3-s4-police-c", consequence: "Protection..." },
        { id: 'd', text: "Pass out without speaking", nextNode: "3-s4-police-d", consequence: "Exhaustion..." },
      ],
    },
    "3-s4-police-a": { id: "3-s4-police-a", type: "narrative", text: "Officers snap to attention. Calls made. Wake in hospital. FBI waiting. They've suspected that island.", nextNode: "3-s5" },
    "3-s4-police-b": { id: "3-s4-police-b", type: "narrative", text: "'Federal case. Get FBI.' They listen. Wake to agents at your bedside. Immediate escalation.", nextNode: "3-s5", document: { title: "FBI_ARRIVAL.pdf", preview: "Federal response triggered...", pdfUrl: "/documents/fbi.pdf" } },
    "3-s4-police-c": { id: "3-s4-police-c", type: "narrative", text: "They put you in protected room immediately. No questions until you're ready. Smart cops.", nextNode: "3-s5" },
    "3-s4-police-d": { id: "3-s4-police-d", type: "narrative", text: "Darkness. Wake in hospital. Guarded room. They know something's wrong. Waiting for your story.", nextNode: "3-s5" },
    "3-s4-fishing": { id: "3-s4-fishing", type: "choice", text: "Old fisherman looks up from nets. You stumble ashore.", question: "Approach fisherman?", timerSeconds: 20,
      choices: [
        { id: 'a', text: "'Need to call FBI'", nextNode: "3-s4-fishing-a", consequence: "Direct..." },
        { id: 'b', text: "'Help... please... phone...'", nextNode: "3-s4-fishing-b", consequence: "Desperate..." },
        { id: 'c', text: "Collapse and let him decide", nextNode: "3-s4-fishing-c", consequence: "Trust..." },
        { id: 'd', text: "Ask for a place to hide", nextNode: "3-s4-fishing-d", consequence: "Shelter..." },
      ],
    },
    "3-s4-fishing-a": { id: "3-s4-fishing-a", type: "narrative", text: "He doesn't question. Hands phone. You dial tip line. Everything you know. Police arrive. Someone believed.", nextNode: "3-s5", document: { title: "TIP_LINE.pdf", preview: "FBI contacted...", pdfUrl: "/documents/tip.pdf" } },
    "3-s4-fishing-b": { id: "3-s4-fishing-b", type: "narrative", text: "He calls 911. 'Someone needs help down here.' Ambulance. Police. Medical first, questions later.", nextNode: "3-s5" },
    "3-s4-fishing-c": { id: "3-s4-fishing-c", type: "narrative", text: "He catches you as you fall. Good man. Makes all the right calls. Wake up safe.", nextNode: "3-s5" },
    "3-s4-fishing-d": { id: "3-s4-fishing-d", type: "narrative", text: "'Boat shed. Rest first.' No questions. People like him are why there's still hope.", nextNode: "3-s5" },
    "3-s4-beach": { id: "3-s4-beach", type: "choice", text: "Beach vessel. Collapse on sand. Sunrise. Alive.", question: "Next step?", timerSeconds: 20,
      choices: [
        { id: 'a', text: "Walk to nearest building", nextNode: "3-s4-beach-a", consequence: "Find help..." },
        { id: 'b', text: "Wait for someone to find you", nextNode: "3-s4-beach-b", consequence: "Conserve energy..." },
        { id: 'c', text: "Look for a phone", nextNode: "3-s4-beach-c", consequence: "Call out..." },
        { id: 'd', text: "Hide evidence first", nextNode: "3-s4-beach-d", consequence: "Protect what you have..." },
      ],
    },
    "3-s4-beach-a": { id: "3-s4-beach-a", type: "narrative", text: "Gas station 100 yards. Call 911 from payphone. Help incoming. You're out.", nextNode: "3-s5" },
    "3-s4-beach-b": { id: "3-s4-beach-b", type: "narrative", text: "Jogger finds you. 911 call. Paramedics. When coherent, demand FBI. Trust no one else.", nextNode: "3-s5" },
    "3-s4-beach-c": { id: "3-s4-beach-c", type: "narrative", text: "Restaurant on boardwalk. Borrow phone. FBI tip line. 'Stay where you are. Agents coming.'", nextNode: "3-s5", document: { title: "AGENTS_COMING.pdf", preview: "FBI responding...", pdfUrl: "/documents/agents.pdf" } },
    "3-s4-beach-d": { id: "3-s4-beach-d", type: "narrative", text: "Bury USB drives in sand. Mark the spot. Even if they catch you now, evidence survives.", nextNode: "3-s5" },

    // STAGE 5: SAFETY
    "3-s5": { id: "3-s5", type: "choice", text: "Hospital. Guarded room. FBI took initial statement. Lawyer warns: powerful people want you silenced.", question: "STAGE 5/5 — Protect yourself?", timerSeconds: 20,
      choices: [
        { id: 'a', text: "Trust FBI completely", nextNode: "3-s5-fbi", consequence: "Let them handle..." },
        { id: 'b', text: "Demand witness protection", nextNode: "3-s5-witsec", consequence: "Safety first..." },
        { id: 'c', text: "Contact journalist", nextNode: "3-s5-media", consequence: "Go public..." },
        { id: 'd', text: "Try to disappear alone", nextNode: "3-s5-death", consequence: "Trust no one..." },
      ],
    },
    "3-s5-death": { id: "3-s5-death", type: "death", text: "Slip out of hospital. Three blocks. Black car. 'Your presence requested.' Not FBI. Too vulnerable alone.", deathMessage: "Running alone - easy target." },
    "3-s5-fbi": { id: "3-s5-fbi", type: "choice", text: "Tell FBI everything. Names, locations, evidence. Lead agent's face goes grim.", question: "Testimony details?", timerSeconds: 20,
      choices: [
        { id: 'a', text: "Hold nothing back", nextNode: "3-s5-fbi-a", consequence: "Complete truth..." },
        { id: 'b', text: "Keep some details for leverage", nextNode: "3-s5-fbi-b", consequence: "Insurance..." },
        { id: 'c', text: "Focus on the big names", nextNode: "3-s5-fbi-c", consequence: "Headlines..." },
        { id: 'd', text: "Give locations first, names later", nextNode: "3-s5-fbi-d", consequence: "Rescue first..." },
      ],
    },
    "3-s5-fbi-a": { id: "3-s5-fbi-a", type: "narrative", text: "Everything. Every detail. 'This is bigger than we thought. Your testimony - enough for warrants. To raid. To bring them down.'", nextNode: "3-complete", document: { title: "FULL_TESTIMONY.pdf", preview: "Complete statement given...", pdfUrl: "/documents/testimony.pdf" } },
    "3-s5-fbi-b": { id: "3-s5-fbi-b", type: "narrative", text: "Most of it. Keep two names for later. Never know who might be compromised. Smart.", nextNode: "3-complete" },
    "3-s5-fbi-c": { id: "3-s5-fbi-c", type: "narrative", text: "Senator Morrison. CEO Chen. Diplomat. The big fish. Agents' eyes go wide. This is career-defining for them.", nextNode: "3-complete" },
    "3-s5-fbi-d": { id: "3-s5-fbi-d", type: "narrative", text: "'Raid the island NOW. Building 3. Four girls. Then I'll tell you everything else.' They move.", nextNode: "3-complete" },
    "3-s5-witsec": { id: "3-s5-witsec", type: "choice", text: "'Witness protection. New identity. Before another word.' Agents exchange looks.", question: "Negotiation stance?", timerSeconds: 20,
      choices: [
        { id: 'a', text: "Demand immediate family protection too", nextNode: "3-s5-witsec-a", consequence: "Everyone safe..." },
        { id: 'b', text: "Accept their terms", nextNode: "3-s5-witsec-b", consequence: "Whatever works..." },
        { id: 'c', text: "Request specific new location", nextNode: "3-s5-witsec-c", consequence: "Control..." },
        { id: 'd', text: "Ask for written guarantee", nextNode: "3-s5-witsec-d", consequence: "Documentation..." },
      ],
    },
    "3-s5-witsec-a": { id: "3-s5-witsec-a", type: "narrative", text: "'Family too or no deal.' 'Done. Everyone.' They know you're worth it.", nextNode: "3-complete", document: { title: "WITSEC_APPROVED.pdf", preview: "Full family protection...", pdfUrl: "/documents/witsec.pdf" } },
    "3-s5-witsec-b": { id: "3-s5-witsec-b", type: "narrative", text: "'Done. Paperwork in 24 hours. You don't leave this room. We don't leave your side.'", nextNode: "3-complete" },
    "3-s5-witsec-c": { id: "3-s5-witsec-c", type: "narrative", text: "'West coast. Small town.' They can work with that. New life, new name, new start.", nextNode: "3-complete" },
    "3-s5-witsec-d": { id: "3-s5-witsec-d", type: "narrative", text: "Signed guarantee from the US Marshal. Legally binding. They really want your testimony.", nextNode: "3-complete" },
    "3-s5-media": { id: "3-s5-media", type: "choice", text: "Contact journalist. Reputation for protecting sources. At bedside within hours.", question: "How much to tell?", timerSeconds: 20,
      choices: [
        { id: 'a', text: "Everything - complete story", nextNode: "3-s5-media-a", consequence: "Full exposure..." },
        { id: 'b', text: "Enough to break news, hold some back", nextNode: "3-s5-media-b", consequence: "Controlled leak..." },
        { id: 'c', text: "Anonymous source only", nextNode: "3-s5-media-c", consequence: "Protected..." },
        { id: 'd', text: "On camera, named, everything", nextNode: "3-s5-media-d", consequence: "Maximum visibility..." },
      ],
    },
    "3-s5-media-a": { id: "3-s5-media-a", type: "narrative", text: "'Once public, they can't touch you. Too many eyes.' Story breaks: ISLAND OF HORRORS. You're visible now.", nextNode: "3-complete", document: { title: "MEDIA_STORY.pdf", preview: "Story broke. Global attention...", pdfUrl: "/documents/media.pdf" } },
    "3-s5-media-b": { id: "3-s5-media-b", type: "narrative", text: "Enough for headlines. Hold names for trial. Best of both worlds.", nextNode: "3-complete" },
    "3-s5-media-c": { id: "3-s5-media-c", type: "narrative", text: "'Anonymous survivor.' Story runs without your name. Protected but heard.", nextNode: "3-complete" },
    "3-s5-media-d": { id: "3-s5-media-d", type: "narrative", text: "Face on camera. Name in print. They can't disappear you now. Too famous.", nextNode: "3-complete" },

    "3-complete": { id: "3-complete", type: "chapter-end", text: "You made it. Escaped the island, crossed the ocean, evaded pursuit, reached safety. FBI mobilizing. Media circling. Powerful people very nervous. Trial and testimony ahead. But you're alive. Free. The truth is coming out.", chapterComplete: { chapter: 3, nextChapter: 4, summary: "You escaped. Now justice begins." } },
  },
};