import { BranchingChapter } from '../types';

export const CHAPTER_2: BranchingChapter = {
  id: 2, title: "CHAPTER 2", subtitle: "The Compound", startNode: "2-s1",
  nodes: {
    // STAGE 1
    "2-s1": { id: "2-s1", type: "choice", text: "Outside Block C. Massive compound - luxury resort facade. Searchlights. Guard pairs. Mansion with party lights. Domed structure humming. Distant marina.", question: "STAGE 1/5 — Where first?", timerSeconds: 20,
      choices: [
        { id: 'a', text: "Head toward the marina", nextNode: "2-s1-marina", consequence: "Boats mean freedom..." },
        { id: 'b', text: "Investigate the dome", nextNode: "2-s1-dome", consequence: "Surveillance..." },
        { id: 'c', text: "Sneak to mansion", nextNode: "2-s1-mansion", consequence: "Know the enemy..." },
        { id: 'd', text: "Find cover, observe", nextNode: "2-s1-observe", consequence: "Patience..." },
      ],
    },
    "2-s1-marina": { id: "2-s1-marina", type: "choice", text: "Marina heavily guarded. Floodlights, cameras, four guards. But a service path near storage buildings.", question: "Approach?", timerSeconds: 20,
      choices: [
        { id: 'a', text: "Find camera blind spots", nextNode: "2-s1-marina-a", consequence: "Study security..." },
        { id: 'b', text: "Check storage buildings", nextNode: "2-s1-marina-b", consequence: "Another angle..." },
        { id: 'c', text: "Wait for guard rotation", nextNode: "2-s1-marina-c", consequence: "Timing..." },
        { id: 'd', text: "Sprint across open ground", nextNode: "2-s1-death", consequence: "Speed..." },
      ],
    },
    "2-s1-death": { id: "2-s1-death", type: "death", text: "Sprint across open ground. Searchlight at 50 yards. Dogs. 'Went for boats. Predictable.'", deathMessage: "Direct approach too obvious." },
    "2-s1-marina-a": { id: "2-s1-marina-a", type: "narrative", text: "Twenty minutes observing. Eastern fence has 40-foot blind zone. Tight, but walkable.", nextNode: "2-s2", document: { title: "CAMERA_GAPS.pdf", preview: "Blind zone mapped...", pdfUrl: "/documents/camera.pdf" } },
    "2-s1-marina-b": { id: "2-s1-marina-b", type: "narrative", text: "Storage: diving gear, boat supplies, GPS tracker manifest. One boat 'manual only' - Maria, Slip 7.", nextNode: "2-s2", document: { title: "BOAT_MANIFEST.pdf", preview: "Maria - no GPS...", pdfUrl: "/documents/manifest.pdf" } },
    "2-s1-marina-c": { id: "2-s1-marina-c", type: "narrative", text: "Every 20 minutes, both guards face away for 45 seconds. That's your window.", nextNode: "2-s2" },
    "2-s1-dome": { id: "2-s1-dome", type: "choice", text: "Dome = surveillance center. Rows of monitors. Guard on phone, bored.", question: "Approach?", timerSeconds: 20,
      choices: [
        { id: 'a', text: "Service entrance", nextNode: "2-s1-dome-a", consequence: "Back door..." },
        { id: 'b', text: "Watch guard routine", nextNode: "2-s1-dome-b", consequence: "Patterns..." },
        { id: 'c', text: "Find power supply", nextNode: "2-s1-dome-c", consequence: "Cut feed..." },
        { id: 'd', text: "Try main door", nextNode: "2-s1-dome-death", consequence: "He's distracted..." },
      ],
    },
    "2-s1-dome-death": { id: "2-s1-dome-death", type: "death", text: "UNAUTHORIZED ACCESS on every screen. Guard unsurprised. 'Motion sensors.'", deathMessage: "Best security on island." },
    "2-s1-dome-a": { id: "2-s1-dome-a", type: "narrative", text: "Service panel pops. Cables, circuits, maintenance shaft. Server room visible. USB port blinking.", nextNode: "2-s2", document: { title: "DOME_ACCESS.pdf", preview: "Service viable...", pdfUrl: "/documents/dome.pdf" } },
    "2-s1-dome-b": { id: "2-s1-dome-b", type: "narrative", text: "Bathroom every hour - 4 minutes. Motion sensors on but he rewinds. Lazy. Exploitable.", nextNode: "2-s2" },
    "2-s1-dome-c": { id: "2-s1-dome-c", type: "narrative", text: "External generator. Could kill power 30 seconds. Chaos, but everyone would know.", nextNode: "2-s2" },
    "2-s1-mansion": { id: "2-s1-mansion", type: "choice", text: "Mansion party. Suits, gowns, champagne. Faces from TV. Not prisoners - clients.", question: "Focus on?", timerSeconds: 20,
      choices: [
        { id: 'a', text: "Identify faces", nextNode: "2-s1-mansion-a", consequence: "Evidence..." },
        { id: 'b', text: "Service entrances", nextNode: "2-s1-mansion-b", consequence: "Access..." },
        { id: 'c', text: "Watch how girls brought in", nextNode: "2-s1-mansion-c", consequence: "Operations..." },
        { id: 'd', text: "Get closer to hear", nextNode: "2-s1-mansion-death", consequence: "Intel..." },
      ],
    },
    "2-s1-mansion-death": { id: "2-s1-mansion-death", type: "death", text: "Guard rounds corner. 'Peeping at guests?' Doesn't bother with taser.", deathMessage: "Too close to clients." },
    "2-s1-mansion-a": { id: "2-s1-mansion-a", type: "narrative", text: "Senator Morrison. Tech CEO Chen. Diplomat. Memorize everything. They'll burn.", nextNode: "2-s2", document: { title: "CLIENTS.pdf", preview: "Faces identified...", pdfUrl: "/documents/clients.pdf" } },
    "2-s1-mansion-b": { id: "2-s1-mansion-b", type: "narrative", text: "Kitchen entrance. Staff barely checked. With a uniform, you could walk in.", nextNode: "2-s2" },
    "2-s1-mansion-c": { id: "2-s1-mansion-c", type: "narrative", text: "Side door. Girls in white gowns led in drugged. Each assigned to a client. Personal shopping.", nextNode: "2-s2", document: { title: "OPERATION.pdf", preview: "Assignment system...", pdfUrl: "/documents/operation.pdf" } },
    "2-s1-observe": { id: "2-s1-observe", type: "choice", text: "Dark alcove. Watch. Guards rotate 20 min. Searchlight gaps. Truck barely checked. Smoke breaks.", question: "Most valuable intel?", timerSeconds: 20,
      choices: [
        { id: 'a', text: "Map patrol pattern", nextNode: "2-s1-observe-a", consequence: "All routes..." },
        { id: 'b', text: "Note truck schedule", nextNode: "2-s1-observe-b", consequence: "Exit option..." },
        { id: 'c', text: "ID lone smoker guard", nextNode: "2-s1-observe-c", consequence: "Target..." },
        { id: 'd', text: "Test sightlines", nextNode: "2-s1-observe-death", consequence: "Limits..." },
      ],
    },
    "2-s1-observe-death": { id: "2-s1-observe-death", type: "death", text: "Lean out to test. Flashlight. 'Contact northeast!' Thermal cameras.", deathMessage: "They have thermal." },
    "2-s1-observe-a": { id: "2-s1-observe-a", type: "narrative", text: "Complete map. Every guard, path, gap. You know this compound now.", nextNode: "2-s2", document: { title: "PATROL.pdf", preview: "Full routes...", pdfUrl: "/documents/patrol.pdf" } },
    "2-s1-observe-b": { id: "2-s1-observe-b", type: "narrative", text: "0400 and 1600 daily. Driver stays in. Cargo unchecked. You could hide in returning truck.", nextNode: "2-s2" },
    "2-s1-observe-c": { id: "2-s1-observe-c", type: "narrative", text: "One guard. Smoke breaks every 90 min behind shed. Alone. Vulnerable. Your target.", nextNode: "2-s2", document: { title: "TARGET.pdf", preview: "Solo guard...", pdfUrl: "/documents/target.pdf" } },

    // STAGE 2
    "2-s2": { id: "2-s2", type: "choice", text: "A scream. Girl's voice. 'Please! Help!' From cottage near mansion. Young. Terrified. Like you were.", question: "STAGE 2/5 — What do you do?", timerSeconds: 20,
      choices: [
        { id: 'a', text: "Rush to help", nextNode: "2-s2-rush", consequence: "She needs you..." },
        { id: 'b', text: "Approach carefully", nextNode: "2-s2-careful", consequence: "Don't rush blind..." },
        { id: 'c', text: "Focus on escape", nextNode: "2-s2-escape", consequence: "Save yourself..." },
        { id: 'd', text: "Get evidence first", nextNode: "2-s2-evidence", consequence: "More lives..." },
      ],
    },
    "2-s2-rush": { id: "2-s2-rush", type: "choice", text: "Cottage window - girl chained. Man in suit looms. Fire extinguisher in hall.", question: "How intervene?", timerSeconds: 20,
      choices: [
        { id: 'a', text: "Grab extinguisher, burst in", nextNode: "2-s2-rush-a", consequence: "Weapon ready..." },
        { id: 'b', text: "Pull fire alarm", nextNode: "2-s2-rush-b", consequence: "Chaos..." },
        { id: 'c', text: "Quiet entry through back", nextNode: "2-s2-rush-c", consequence: "Stealth..." },
        { id: 'd', text: "Break window directly", nextNode: "2-s2-rush-death", consequence: "Fast..." },
      ],
    },
    "2-s2-rush-death": { id: "2-s2-rush-death", type: "death", text: "Smash glass. Man shouts. Guards already close. 'Hero complex.'", deathMessage: "Guards were nearby." },
    "2-s2-rush-a": { id: "2-s2-rush-a", type: "narrative", text: "Extinguisher, kick door, spray face. He screams blind. Grab the girl. 'We're leaving. NOW.'", nextNode: "2-s3" },
    "2-s2-rush-b": { id: "2-s2-rush-b", type: "narrative", text: "Alarm screams. Sprinklers. Man bolts. You slip in, cut chains. 'Follow me.'", nextNode: "2-s3", document: { title: "RESCUE.pdf", preview: "Fire alarm diversion...", pdfUrl: "/documents/rescue.pdf" } },
    "2-s2-rush-c": { id: "2-s2-rush-c", type: "narrative", text: "Back door unlocked. Creep up behind. Strike. He drops. 'I'm getting you out.'", nextNode: "2-s3" },
    "2-s2-careful": { id: "2-s2-careful", type: "choice", text: "Circle cottage. Multiple rooms. Four girls minimum. Guards patrol. Fire alarm accessible.", question: "It's bigger than one victim.", timerSeconds: 20,
      choices: [
        { id: 'a', text: "Save one - the screamer", nextNode: "2-s2-careful-a", consequence: "Save who you can..." },
        { id: 'b', text: "Pull alarm for all", nextNode: "2-s2-careful-b", consequence: "Mass confusion..." },
        { id: 'c', text: "Mark location, keep moving", nextNode: "2-s2-careful-c", consequence: "Come back..." },
        { id: 'd', text: "Coordinate through windows", nextNode: "2-s2-careful-death", consequence: "Work together..." },
      ],
    },
    "2-s2-careful-death": { id: "2-s2-careful-death", type: "death", text: "Tap window. Girl screams - not hope, conditioning. 'GUARD!' They trained victims to report.", deathMessage: "Victims conditioned to alert." },
    "2-s2-careful-a": { id: "2-s2-careful-a", type: "narrative", text: "One at a time. Window, lock, cut chains. She's terrified until she sees you. One saved.", nextNode: "2-s3" },
    "2-s2-careful-b": { id: "2-s2-careful-b", type: "narrative", text: "Alarm. Chaos. Three girls bolt into night. You've given them a chance.", nextNode: "2-s3", document: { title: "MASS_ESCAPE.pdf", preview: "Multiple fled...", pdfUrl: "/documents/mass.pdf" } },
    "2-s2-careful-c": { id: "2-s2-careful-c", type: "narrative", text: "Four girls. Building 3, east. Burned into memory. You'll bring help.", nextNode: "2-s3" },
    "2-s2-escape": { id: "2-s2-escape", type: "choice", text: "Turn away. Hardest thing ever. One vs army. Need real help. FBI. Media.", question: "Escape priority?", timerSeconds: 20,
      choices: [
        { id: 'a', text: "Marina - find boat", nextNode: "2-s2-escape-a", consequence: "Water exit..." },
        { id: 'b', text: "Perimeter - find weakness", nextNode: "2-s2-escape-b", consequence: "Land exit..." },
        { id: 'c', text: "Comms - call for help", nextNode: "2-s2-escape-c", consequence: "Signal out..." },
        { id: 'd', text: "Scout everything", nextNode: "2-s2-escape-death", consequence: "Complete recon..." },
      ],
    },
    "2-s2-escape-death": { id: "2-s2-escape-death", type: "death", text: "Too much ground. Patrol catches you mid-transit. 'Scenic route?'", deathMessage: "Too much ground, too little time." },
    "2-s2-escape-a": { id: "2-s2-escape-a", type: "narrative", text: "Memorize everything. Girl's location. Layouts. Guards. You'll be back with an army.", nextNode: "2-s3", document: { title: "ESCAPE_ROUTE.pdf", preview: "Return strategy...", pdfUrl: "/documents/route.pdf" } },
    "2-s2-escape-b": { id: "2-s2-escape-b", type: "narrative", text: "North fence drainage pipe. 24 inches. Under the wire. Tight but free.", nextNode: "2-s3" },
    "2-s2-escape-c": { id: "2-s2-escape-c", type: "narrative", text: "Staff quarters might have phone. One call - FBI, journalist - world knows.", nextNode: "2-s3" },
    "2-s2-evidence": { id: "2-s2-evidence", type: "choice", text: "Scream haunts you. But evidence saves more lives. Dome has years of footage.", question: "How get it?", timerSeconds: 20,
      choices: [
        { id: 'a', text: "Service entrance", nextNode: "2-s2-evidence-a", consequence: "Known access..." },
        { id: 'b', text: "Wait for bathroom break", nextNode: "2-s2-evidence-b", consequence: "Timing..." },
        { id: 'c', text: "Cut power, grab in dark", nextNode: "2-s2-evidence-c", consequence: "30 sec chaos..." },
        { id: 'd', text: "Start fire elsewhere", nextNode: "2-s2-evidence-death", consequence: "Draw away..." },
      ],
    },
    "2-s2-evidence-death": { id: "2-s2-evidence-death", type: "death", text: "Fire draws too much attention. Someone finds you near dome. 'Arsonist AND infiltrator.'", deathMessage: "Distraction too big." },
    "2-s2-evidence-a": { id: "2-s2-evidence-a", type: "narrative", text: "Maintenance shaft. Servers hum. USB drives grabbed before motion sensors trip. Run.", nextNode: "2-s3", document: { title: "EVIDENCE.pdf", preview: "6 drives. 10+ years...", pdfUrl: "/documents/evidence.pdf" } },
    "2-s2-evidence-b": { id: "2-s2-evidence-b", type: "narrative", text: "020. Bathroom. Slip in front door low. Grab drives. Out in 3 min. He never knew.", nextNode: "2-s3" },
    "2-s2-evidence-c": { id: "2-s2-evidence-c", type: "narrative", text: "Emergency cutoff. Dark. 30 seconds. Grab grab grab. Lights flicker back. Five drives.", nextNode: "2-s3" },

    // STAGE 3
    "2-s3": { id: "2-s3", type: "choice", text: "Need supplies. Blade and keycard won't be enough. Shed, staff quarters, clinic accessible.", question: "STAGE 3/5 — Resources?", timerSeconds: 20,
      choices: [
        { id: 'a', text: "Maintenance shed", nextNode: "2-s3-shed", consequence: "Tools..." },
        { id: 'b', text: "Staff quarters", nextNode: "2-s3-staff", consequence: "Comms..." },
        { id: 'c', text: "Medical clinic", nextNode: "2-s3-medical", consequence: "Supplies..." },
        { id: 'd', text: "Skip - move now", nextNode: "2-s3-death", consequence: "Time short..." },
      ],
    },
    "2-s3-death": { id: "2-s3-death", type: "death", text: "No supplies. Dogs at perimeter. Razor wire. 'No plan. What did you expect?'", deathMessage: "Unprepared was foolish." },
    "2-s3-shed": { id: "2-s3-shed", type: "choice", text: "Shed unlocked. Rope, cutters, flashlight, wrench. Irrigation map shows underground pipes outside perimeter.", question: "Most important?", timerSeconds: 20,
      choices: [
        { id: 'a', text: "Wire cutters for fence", nextNode: "2-s3-shed-a", consequence: "Cut through..." },
        { id: 'b', text: "Study irrigation map", nextNode: "2-s3-shed-b", consequence: "Underground..." },
        { id: 'c', text: "Wrench as weapon", nextNode: "2-s3-shed-c", consequence: "Heavy..." },
        { id: 'd', text: "Take everything", nextNode: "2-s3-shed-death", consequence: "Prepared..." },
      ],
    },
    "2-s3-shed-death": { id: "2-s3-shed-death", type: "death", text: "Arms full. Step outside. Guard sees stolen gear. Can't run loaded down.", deathMessage: "Greed slowed you." },
    "2-s3-shed-a": { id: "2-s3-shed-a", type: "narrative", text: "Cutters tucked away. Any fence now optional. Freedom is one cut away.", nextNode: "2-s4" },
    "2-s3-shed-b": { id: "2-s3-shed-b", type: "narrative", text: "Northeast pipe, 24 inches. 200 feet to outside. Tight, muddy, invisible.", nextNode: "2-s4", document: { title: "TUNNEL.pdf", preview: "Underground route...", pdfUrl: "/documents/tunnel.pdf" } },
    "2-s3-shed-c": { id: "2-s3-shed-c", type: "narrative", text: "Heavy steel wrench. One swing drops anyone. You're armed.", nextNode: "2-s4" },
    "2-s3-staff": { id: "2-s3-staff", type: "choice", text: "Staff quarters. Break room. Landline phone. Wallet with keys. Uniform.", question: "Need most?", timerSeconds: 20,
      choices: [
        { id: 'a', text: "Phone to call help", nextNode: "2-s3-staff-a", consequence: "Word out..." },
        { id: 'b', text: "Uniform disguise", nextNode: "2-s3-staff-b", consequence: "Blend in..." },
        { id: 'c', text: "Keys - might fit boat", nextNode: "2-s3-staff-c", consequence: "Mobile..." },
        { id: 'd', text: "Search more", nextNode: "2-s3-staff-death", consequence: "Intel..." },
      ],
    },
    "2-s3-staff-death": { id: "2-s3-staff-death", type: "death", text: "Drawers open. Door opens. Staff returns for forgotten item. 'Who are you?'", deathMessage: "Too long searching." },
    "2-s3-staff-a": { id: "2-s3-staff-a", type: "narrative", text: "'FBI? Trafficking island. Multiple victims.' Everything you can. Maybe they'll come. At least a record.", nextNode: "2-s4", document: { title: "FBI_TIP.pdf", preview: "Tip called...", pdfUrl: "/documents/tip.pdf" } },
    "2-s3-staff-b": { id: "2-s3-staff-b", type: "narrative", text: "Uniform fits. In dim light, pass for staff. Buys seconds when seconds matter.", nextNode: "2-s4" },
    "2-s3-staff-c": { id: "2-s3-staff-c", type: "narrative", text: "'MARIA - SLIP 7.' Same no-GPS boat. Exit confirmed.", nextNode: "2-s4" },
    "2-s3-medical": { id: "2-s3-medical", type: "choice", text: "Clinic empty. Bandages, antibiotics, sedatives. Medical log - names, dates, procedures.", question: "Focus?", timerSeconds: 20,
      choices: [
        { id: 'a', text: "Photograph logs", nextNode: "2-s3-medical-a", consequence: "Evidence..." },
        { id: 'b', text: "Take sedatives", nextNode: "2-s3-medical-b", consequence: "Chemical..." },
        { id: 'c', text: "Bandage wounds", nextNode: "2-s3-medical-c", consequence: "Heal..." },
        { id: 'd', text: "Search patient records", nextNode: "2-s3-medical-death", consequence: "Details..." },
      ],
    },
    "2-s3-medical-death": { id: "2-s3-medical-death", type: "death", text: "Deep in files. Nurse arrives early shift. 'Security! Intruder!'", deathMessage: "Early shift." },
    "2-s3-medical-a": { id: "2-s3-medical-a", type: "narrative", text: "Camera found. Everything photographed. 200+ entries. Damning.", nextNode: "2-s4", document: { title: "MEDICAL_LOG.pdf", preview: "Full log...", pdfUrl: "/documents/medical.pdf" } },
    "2-s3-medical-b": { id: "2-s3-medical-b", type: "narrative", text: "Sedatives pocketed. Syringe loaded. Close to someone, they go down quiet.", nextNode: "2-s4" },
    "2-s3-medical-c": { id: "2-s3-medical-c", type: "narrative", text: "Clean cuts. Antiseptic. Proper bandage. Hands ready for climbing, swimming, fighting.", nextNode: "2-s4" },

    // STAGE 4
    "2-s4": { id: "2-s4", type: "choice", text: "Two guards round corner ahead. Haven't seen you yet. Fountain left. Planter right. Flashlights sweeping.", question: "STAGE 4/5 — Guards approaching.", timerSeconds: 20,
      choices: [
        { id: 'a', text: "Duck behind fountain", nextNode: "2-s4-fountain", consequence: "Stone cover..." },
        { id: 'b', text: "Slip behind planter", nextNode: "2-s4-planter", consequence: "Vegetation..." },
        { id: 'c', text: "Throw distraction", nextNode: "2-s4-distract", consequence: "Misdirect..." },
        { id: 'd', text: "Walk past confident", nextNode: "2-s4-death", consequence: "Belong..." },
      ],
    },
    "2-s4-death": { id: "2-s4-death", type: "death", text: "'Badge?' Don't have one. 'Subject escape.' Taser. 'Staff doesn't wander 3 AM.'", deathMessage: "Bluffing doesn't work during searches." },
    "2-s4-fountain": { id: "2-s4-fountain", type: "choice", text: "Behind wet stone. Flashlights inches away. '...Block C runner?' 'They never make it.'", question: "They pass. Now what?", timerSeconds: 20,
      choices: [
        { id: 'a', text: "Stay hidden longer", nextNode: "2-s4-fountain-a", consequence: "Patience..." },
        { id: 'b', text: "Follow them for routes", nextNode: "2-s4-fountain-b", consequence: "Intel..." },
        { id: 'c', text: "Move opposite direction", nextNode: "2-s4-fountain-c", consequence: "Use gap..." },
        { id: 'd', text: "Ambush from behind", nextNode: "2-s4-fountain-death", consequence: "Take down..." },
      ],
    },
    "2-s4-fountain-death": { id: "2-s4-fountain-death", type: "death", text: "Attack two trained guards from behind? Partner spins, fires taser. 'Nice try.'", deathMessage: "Two at once was overconfident." },
    "2-s4-fountain-a": { id: "2-s4-fountain-a", type: "narrative", text: "Five minutes frozen. They pass twice more. Now you know exact timing.", nextNode: "2-s5" },
    "2-s4-fountain-b": { id: "2-s4-fountain-b", type: "narrative", text: "Follow at distance. Three checkpoints mapped. Know where guards are and aren't.", nextNode: "2-s5", document: { title: "PATROL_INTEL.pdf", preview: "Routes followed...", pdfUrl: "/documents/follow.pdf" } },
    "2-s4-fountain-c": { id: "2-s4-fountain-c", type: "narrative", text: "Slip away while backs turned. Distance matters. Soon you're clear.", nextNode: "2-s5" },
    "2-s4-planter": { id: "2-s4-planter", type: "choice", text: "Behind leaves. One smokes. 'Senator client?' 'Sick bastard. Even by our standards.' They laugh.", question: "Useful gossip.", timerSeconds: 20,
      choices: [
        { id: 'a', text: "Keep listening", nextNode: "2-s4-planter-a", consequence: "Names..." },
        { id: 'b', text: "Wait for them to leave", nextNode: "2-s4-planter-b", consequence: "Safe..." },
        { id: 'c', text: "Memorize their faces", nextNode: "2-s4-planter-c", consequence: "Witnesses..." },
        { id: 'd', text: "Cough to get attention", nextNode: "2-s4-planter-death", consequence: "Maybe help..." },
      ],
    },
    "2-s4-planter-death": { id: "2-s4-planter-death", type: "death", text: "Cough. Spin. 'Switch sides because opinions? Still paid.'", deathMessage: "Limits don't make allies." },
    "2-s4-planter-a": { id: "2-s4-planter-a", type: "narrative", text: "'Morrison wants young.' 'Chen's rough.' 'Diplomat's worst.' Names. Preferences. Evidence.", nextNode: "2-s5", document: { title: "GUARD_INTEL.pdf", preview: "Client preferences...", pdfUrl: "/documents/overheard.pdf" } },
    "2-s4-planter-b": { id: "2-s4-planter-b", type: "narrative", text: "Cigarette done. They move. New knowledge about guard morals. Even monsters have standards.", nextNode: "2-s5" },
    "2-s4-planter-c": { id: "2-s4-planter-c", type: "narrative", text: "Badge names: Torres, Wallace. If you testify, name them. Their choice later.", nextNode: "2-s5" },
    "2-s4-distract": { id: "2-s4-distract", type: "choice", text: "Stone left. Guards spin. Cat bolts - perfect cover.", question: "They're investigating.", timerSeconds: 20,
      choices: [
        { id: 'a', text: "Slip right while distracted", nextNode: "2-s4-distract-a", consequence: "Opening..." },
        { id: 'b', text: "Circle behind them", nextNode: "2-s4-distract-b", consequence: "Flank..." },
        { id: 'c', text: "Run straight past", nextNode: "2-s4-distract-c", consequence: "Clear path..." },
        { id: 'd', text: "Throw another stone", nextNode: "2-s4-distract-death", consequence: "Keep busy..." },
      ],
    },
    "2-s4-distract-death": { id: "2-s4-distract-death", type: "death", text: "Second stone. Don't fall for twice. 'Playing games.' Systematic sweep. Found.", deathMessage: "Same trick doesn't work twice." },
    "2-s4-distract-a": { id: "2-s4-distract-a", type: "narrative", text: "Vanish right. They investigate left. 30 seconds, two buildings away.", nextNode: "2-s5" },
    "2-s4-distract-b": { id: "2-s4-distract-b", type: "narrative", text: "Wide arc. When they resume, you're behind them heading opposite.", nextNode: "2-s5" },
    "2-s4-distract-c": { id: "2-s4-distract-c", type: "narrative", text: "Straight through. Fast quiet. Their backs to you. Gone before they turn.", nextNode: "2-s5", document: { title: "DISTRACTION.pdf", preview: "Misdirection worked...", pdfUrl: "/documents/distract.pdf" } },

    // STAGE 5
    "2-s5": { id: "2-s5", type: "choice", text: "Dawn approaches. Resources gathered. Marina accessible. Evidence maybe secured. Someone might need rescue. Can't do everything.", question: "STAGE 5/5 — Final priority?", timerSeconds: 20,
      choices: [
        { id: 'a', text: "Escape via marina", nextNode: "2-s5-marina", consequence: "Get out..." },
        { id: 'b', text: "One more rescue", nextNode: "2-s5-rescue", consequence: "Save someone..." },
        { id: 'c', text: "Secure more evidence", nextNode: "2-s5-evidence", consequence: "Make count..." },
        { id: 'd', text: "Confront clients", nextNode: "2-s5-death", consequence: "Face monsters..." },
      ],
    },
    "2-s5-death": { id: "2-s5-death", type: "death", text: "Storm mansion. 'Monsters!' Tackled instantly. Guests annoyed. 'Another one.'", deathMessage: "Clients aren't allies." },
    "2-s5-marina": { id: "2-s5-marina", type: "choice", text: "Marina. Slip 7. Maria. Keys ready. One pier guard.", question: "Handle guard?", timerSeconds: 20,
      choices: [
        { id: 'a', text: "Wait for rotation", nextNode: "2-s5-marina-a", consequence: "Patience..." },
        { id: 'b', text: "Distraction elsewhere", nextNode: "2-s5-marina-b", consequence: "Draw away..." },
        { id: 'c', text: "Approach in disguise", nextNode: "2-s5-marina-c", consequence: "Blend..." },
        { id: 'd', text: "Take him down", nextNode: "2-s5-marina-d", consequence: "Eliminate..." },
      ],
    },
    "2-s5-marina-a": { id: "2-s5-marina-a", type: "narrative", text: "Rotation. He turns. Sprint to Slip 7. Push off. Ocean. Freedom.", nextNode: "2-complete" },
    "2-s5-marina-b": { id: "2-s5-marina-b", type: "narrative", text: "Stone through far window. He investigates. Boat and gone.", nextNode: "2-complete" },
    "2-s5-marina-c": { id: "2-s5-marina-c", type: "narrative", text: "Uniform on. 'Checking Maria.' He barely looks. Aboard and pushing off.", nextNode: "2-complete" },
    "2-s5-marina-d": { id: "2-s5-marina-d", type: "narrative", text: "Sedative syringe. Approach friendly, inject fast. Down quiet. Boat. Water. Gone.", nextNode: "2-complete", document: { title: "CLEAN_EXIT.pdf", preview: "Guard neutralized...", pdfUrl: "/documents/clean.pdf" } },
    "2-s5-rescue": { id: "2-s5-rescue", type: "choice", text: "Back to cottage. Sofia. Fire alarm ready. Window accessible.", question: "Approach?", timerSeconds: 20,
      choices: [
        { id: 'a', text: "Alarm chaos", nextNode: "2-s5-rescue-a", consequence: "Confusion..." },
        { id: 'b', text: "Window during rotation", nextNode: "2-s5-rescue-b", consequence: "Quiet..." },
        { id: 'c', text: "Talk through window first", nextNode: "2-s5-rescue-c", consequence: "Prepare..." },
        { id: 'd', text: "Knock out cottage guard", nextNode: "2-s5-rescue-d", consequence: "Clear way..." },
      ],
    },
    "2-s5-rescue-a": { id: "2-s5-rescue-a", type: "narrative", text: "Alarm. Sprinklers. Chaos. Smash through, cut chains. 'RUN.' Her name is Sofia. 15. Coming with you.", nextNode: "2-complete" },
    "2-s5-rescue-b": { id: "2-s5-rescue-b", type: "narrative", text: "Rotation gap. Window. Chains cut. She's terrified but quiet. Two shadows.", nextNode: "2-complete" },
    "2-s5-rescue-c": { id: "2-s5-rescue-c", type: "narrative", text: "'Be ready to run. Trust me.' She nods. Enter, cut, out. Not alone anymore.", nextNode: "2-complete", document: { title: "SOFIA.pdf", preview: "Victim rescued...", pdfUrl: "/documents/sofia.pdf" } },
    "2-s5-rescue-d": { id: "2-s5-rescue-d", type: "narrative", text: "Wrench to head. Guard drops. Inside. Chains. 'Let's go.' Sofia runs like waiting her whole life.", nextNode: "2-complete" },
    "2-s5-evidence": { id: "2-s5-evidence", type: "choice", text: "More evidence. Dome or elsewhere. More you have, harder to cover up.", question: "Where look?", timerSeconds: 20,
      choices: [
        { id: 'a', text: "Dome - more drives", nextNode: "2-s5-evidence-a", consequence: "Footage..." },
        { id: 'b', text: "Office - financial", nextNode: "2-s5-evidence-b", consequence: "Money trail..." },
        { id: 'c', text: "Guest quarters - client list", nextNode: "2-s5-evidence-c", consequence: "Names..." },
        { id: 'd', text: "Have enough - go", nextNode: "2-s5-evidence-d", consequence: "Don't push..." },
      ],
    },
    "2-s5-evidence-a": { id: "2-s5-evidence-a", type: "narrative", text: "One more trip. Alarm already tripped earlier - thought glitch. Four more drives. Backup.", nextNode: "2-complete", document: { title: "BACKUP.pdf", preview: "More drives...", pdfUrl: "/documents/backup.pdf" } },
    "2-s5-evidence-b": { id: "2-s5-evidence-b", type: "narrative", text: "Financial records. Wire transfers. Shell companies. Switzerland, Cayman, Singapore.", nextNode: "2-complete" },
    "2-s5-evidence-c": { id: "2-s5-evidence-c", type: "narrative", text: "Clipboard in service area. Guest list with room assignments. Names matched to victims. Pocket it.", nextNode: "2-complete" },
    "2-s5-evidence-d": { id: "2-s5-evidence-d", type: "narrative", text: "Enough. Don't push luck. Marina. Boat. Need to be alive to testify.", nextNode: "2-complete" },

    "2-complete": { id: "2-complete", type: "chapter-end", text: "Dawn breaks. Whatever you chose - evidence, rescue, escape - you've taken action. This isn't over. They know someone got out.", chapterComplete: { chapter: 2, nextChapter: 3, summary: "You explored the compound and made critical choices. Now the escape." } },
  },
};