import { BranchingChapter } from '../types';

/**
 * CHAPTER 5: THE TRIAL - 5 Stages, full branching
 * PERSPECTIVE SHIFT: You are Detective Marcus Cole, lead investigator.
 * 20 years on the force. You've seen the worst of humanity. But this case... this is different.
 * NO DEATH NODES - This is a courtroom drama chapter
 */
export const CHAPTER_5: BranchingChapter = {
  id: 5,
  title: "CHAPTER 5",
  subtitle: "The Trial",
  startNode: "5-s1",
  nodes: {
    // ========== STAGE 1: THE DETECTIVE ==========
    "5-s1": {
      id: "5-s1",
      type: "choice",
      text: "Detective Marcus Cole. Twenty years on the force, fifteen in major crimes. You've worked homicides, kidnappings, organized crime. But when the FBI called you in as local liaison for 'the island case,' you didn't know it would consume your life. Now you're sitting in the courthouse hallway, waiting to testify. The survivor just finished - three days of devastating testimony. Your turn next.",
      question: "STAGE 1/5 — How do you prepare for your testimony?",
      timerSeconds: 20,
      choices: [
        { id: 'a', text: "Review your case notes one more time", nextNode: "5-s1-notes", consequence: "Every detail matters..." },
        { id: 'b', text: "Talk to the prosecutor about strategy", nextNode: "5-s1-prosecutor", consequence: "Coordinate approach..." },
        { id: 'c', text: "Check on the survivor witness", nextNode: "5-s1-survivor", consequence: "She's been through hell..." },
        { id: 'd', text: "Take a moment to collect yourself", nextNode: "5-s1-collect", consequence: "Clear your mind..." },
      ],
    },
    "5-s1-collect": {
      id: "5-s1-collect",
      type: "choice",
      text: "You find a quiet corner. Twenty years of this work. Hundreds of cases. But this one... the scale of it. The evil of it. You close your eyes and breathe. When you open them, you're ready.",
      question: "What thought steadies you?",
      timerSeconds: 20,
      choices: [
        { id: 'a', text: "The victims deserve justice", nextNode: "5-s1-collect-victims", consequence: "For them..." },
        { id: 'b', text: "The evidence is solid", nextNode: "5-s1-collect-evidence", consequence: "The truth speaks..." },
        { id: 'c', text: "This is what you trained for", nextNode: "5-s1-collect-training", consequence: "You're ready..." },
        { id: 'd', text: "Morrison will face consequences", nextNode: "5-s1-collect-morrison", consequence: "Justice is coming..." },
      ],
    },
    "5-s1-collect-victims": { id: "5-s1-collect-victims", type: "narrative", text: "Thirty-seven confirmed victims. Names you've memorized. Faces you'll never forget. Some survived. Many didn't. You carry them with you into that courtroom. Their stories. Their suffering. You won't let them down.", nextNode: "5-s2" },
    "5-s1-collect-evidence": { id: "5-s1-collect-evidence", type: "narrative", text: "Six months of investigation. Thousands of documents. Dozens of witnesses. The evidence tells a clear story of calculated evil. All you have to do is present it clearly. Let the facts speak. They're damning enough.", nextNode: "5-s2" },
    "5-s1-collect-training": { id: "5-s1-collect-training", type: "narrative", text: "You've testified hundreds of times. Faced hostile defense attorneys. Weathered cross-examinations. This is bigger, but the job is the same: tell the truth, clearly and completely. You know how to do this.", nextNode: "5-s2" },
    "5-s1-collect-morrison": { id: "5-s1-collect-morrison", type: "narrative", text: "Senator Morrison. The man who smiled for cameras while funding a trafficking operation. Who used his power to silence victims and obstruct investigations. Today, his power means nothing. Today, he faces the law.", nextNode: "5-s2" },
    "5-s1-notes": {
      id: "5-s1-notes",
      type: "choice",
      text: "Your case file is three inches thick. Witness statements. Forensic reports. Financial records. The timeline you built piece by piece over six months. Something's been nagging at you - a connection you haven't quite made.",
      question: "What do you focus on in your notes?",
      timerSeconds: 20,
      choices: [
        { id: 'a', text: "The financial trail", nextNode: "5-s1-notes-money", consequence: "Follow the money..." },
        { id: 'b', text: "Witness testimony inconsistencies", nextNode: "5-s1-notes-witnesses", consequence: "Small details..." },
        { id: 'c', text: "The timeline of events", nextNode: "5-s1-notes-timeline", consequence: "When things happened..." },
        { id: 'd', text: "Evidence chain of custody", nextNode: "5-s1-notes-custody", consequence: "Airtight case..." },
      ],
    },
    "5-s1-notes-money": { id: "5-s1-notes-money", type: "narrative", text: "There. A shell company - Meridian Holdings - appears in Morrison's finances AND the island's operating budget. You'd flagged it before but... now you see it also connects to Judge Harrison. The judge who was supposed to hear this case before recusing himself. That's not coincidence.", nextNode: "5-s2", document: { title: "FINANCIAL_CONNECTION.pdf", preview: "Meridian Holdings links Morrison, island, and Judge Harrison...", pdfUrl: "/documents/financial-connection.pdf" } },
    "5-s1-notes-witnesses": { id: "5-s1-notes-witnesses", type: "narrative", text: "Guard Torres said the helicopter was grounded for maintenance on March 15th. But pilot logs show a flight that night. Someone's lying. If you can prove which one, you can flip them against Morrison.", nextNode: "5-s2" },
    "5-s1-notes-timeline": { id: "5-s1-notes-timeline", type: "narrative", text: "The survivor escaped at 0347. Morrison's phone pinged the island at 0342 - five minutes before. He was there. He saw her escape. And he didn't alert security. Why? Unless he wanted chaos. A distraction from something else happening that night.", nextNode: "5-s2", document: { title: "TIMELINE_ANOMALY.pdf", preview: "Morrison present during escape. No alert triggered. Why?", pdfUrl: "/documents/timeline.pdf" } },
    "5-s1-notes-custody": { id: "5-s1-notes-custody", type: "narrative", text: "Every piece of evidence properly logged. Every transfer documented. Defense will try to claim tampering - they always do. But your chain is airtight. Six months of meticulous work. They won't break it.", nextNode: "5-s2" },
    "5-s1-prosecutor": {
      id: "5-s1-prosecutor",
      type: "choice",
      text: "ADA Sarah Chen - no relation to the FBI agent - has been preparing this case for months. She looks exhausted but determined. 'Detective. How are you feeling?' 'Ready,' you lie. 'Good. Because Morrison's team is going to come at you hard.'",
      question: "What do you discuss with the prosecutor?",
      timerSeconds: 20,
      choices: [
        { id: 'a', text: "Defense strategy predictions", nextNode: "5-s1-prosecutor-defense", consequence: "Know the enemy..." },
        { id: 'b', text: "Key evidence to emphasize", nextNode: "5-s1-prosecutor-evidence", consequence: "Hit them hard..." },
        { id: 'c', text: "Potential weaknesses in the case", nextNode: "5-s1-prosecutor-weak", consequence: "Shore up holes..." },
        { id: 'd', text: "Your concerns about jury tampering", nextNode: "5-s1-prosecutor-jury", consequence: "Something feels off..." },
      ],
    },
    "5-s1-prosecutor-defense": { id: "5-s1-prosecutor-defense", type: "narrative", text: "'They'll attack your methods. Claim you had a vendetta against Morrison. They've dug into your past cases - looking for anything.' She pauses. 'The Martinez case.' Your stomach drops. A case from eight years ago. Suspect walked on a technicality. 'I followed procedure.' 'I know. Just be ready.'", nextNode: "5-s2" },
    "5-s1-prosecutor-evidence": { id: "5-s1-prosecutor-evidence", type: "narrative", text: "'The surveillance footage is our strongest piece. Morrison on camera, on the island, with victims visible in frame. His lawyers will claim deepfake, editing, anything. You need to explain chain of custody like you're talking to children.' You nod. Simple. Clear. Devastating.", nextNode: "5-s2", document: { title: "KEY_EVIDENCE.pdf", preview: "Surveillance footage strategy. Unimpeachable chain...", pdfUrl: "/documents/key-evidence.pdf" } },
    "5-s1-prosecutor-weak": { id: "5-s1-prosecutor-weak", type: "narrative", text: "'The weak point is the gap. Three hours on March 12th where Morrison's whereabouts are unaccounted for - but so is anyone else's. Defense will argue he wasn't on the island then.' 'But the phone records-' 'Are circumstantial. We need you to sell the totality.'", nextNode: "5-s2" },
    "5-s1-prosecutor-jury": { id: "5-s1-prosecutor-jury", type: "narrative", text: "'Juror 7. He's been watching Morrison's lawyer, not the witnesses.' Chen frowns. 'We noticed too. Background check came up clean, but...' 'But Morrison has resources.' 'We're monitoring. If he makes a move, we'll catch it.'", nextNode: "5-s2", document: { title: "JUROR_CONCERN.pdf", preview: "Juror 7 flagged. Surveillance authorized...", pdfUrl: "/documents/juror.pdf" } },
    "5-s1-survivor": {
      id: "5-s1-survivor",
      type: "choice",
      text: "She's in the witness room, FBI agents at the door. Exhausted. Pale. But when she sees you, she manages a small smile. 'Detective Cole.' 'How are you holding up?' Stupid question. You know it as soon as you ask.",
      question: "How do you support the survivor?",
      timerSeconds: 20,
      choices: [
        { id: 'a', text: "Offer practical reassurance", nextNode: "5-s1-survivor-practical", consequence: "Facts help..." },
        { id: 'b', text: "Share your own experience with difficult cases", nextNode: "5-s1-survivor-share", consequence: "You're not alone..." },
        { id: 'c', text: "Just sit with her in silence", nextNode: "5-s1-survivor-silence", consequence: "Presence matters..." },
        { id: 'd', text: "Tell her how strong she's been", nextNode: "5-s1-survivor-strong", consequence: "Acknowledge her courage..." },
      ],
    },
    "5-s1-survivor-practical": { id: "5-s1-survivor-practical", type: "narrative", text: "'Your testimony was solid. Defense couldn't shake you. The jury was paying attention - the right kind of attention.' She nods slowly. 'I just kept thinking about the others. The ones who didn't make it out.' 'That's why we're here. For them too.'", nextNode: "5-s2" },
    "5-s1-survivor-share": { id: "5-s1-survivor-share", type: "narrative", text: "'Fifteen years ago, I testified against a cop. My partner. He was dirty. Walking into that courtroom was the hardest thing I'd ever done.' She looks up. 'What happened?' 'He's in prison. Still is.' Sometimes the system works. She needs to believe that.", nextNode: "5-s2" },
    "5-s1-survivor-silence": { id: "5-s1-survivor-silence", type: "narrative", text: "You sit. Don't say anything. After a few minutes, she speaks. 'Everyone keeps asking how I feel. Like there are words for this.' 'There aren't.' 'No. There aren't.' But somehow, the silence helps. Some things can't be talked through. Only endured.", nextNode: "5-s2", document: { title: "WITNESS_SUPPORT.pdf", preview: "Survivor stabilized. Ready for continued proceedings...", pdfUrl: "/documents/support.pdf" } },
    "5-s1-survivor-strong": { id: "5-s1-survivor-strong", type: "narrative", text: "'What you did up there... three days of cross-examination. Morrison's lawyers trying to twist your words. And you didn't break.' She looks down. 'I almost did. Several times.' 'But you didn't. That's what matters.' She takes a breath. 'Neither will you.'", nextNode: "5-s2" },

    // ========== STAGE 2: THE TESTIMONY ==========
    "5-s2": {
      id: "5-s2",
      type: "choice",
      text: "'The People call Detective Marcus Cole.' You walk to the stand. The courtroom is packed - media in the gallery, Morrison's family in the front row, victim's families scattered throughout. Morrison himself watches you with cold, calculating eyes. The oath. The chair. And then the questions begin.",
      question: "STAGE 2/5 — The prosecutor starts with your background. How do you present yourself?",
      timerSeconds: 20,
      choices: [
        { id: 'a', text: "Stick to credentials - just the facts", nextNode: "5-s2-facts", consequence: "Professional distance..." },
        { id: 'b', text: "Show your dedication to the case", nextNode: "5-s2-dedication", consequence: "Let them see you care..." },
        { id: 'c', text: "Emphasize your experience with similar cases", nextNode: "5-s2-experience", consequence: "You've seen this before..." },
        { id: 'd', text: "Acknowledge the case affected you personally", nextNode: "5-s2-personal", consequence: "Honesty matters..." },
      ],
    },
    "5-s2-facts": {
      id: "5-s2-facts",
      type: "choice",
      text: "'Twenty years in law enforcement. Fifteen in major crimes. Lead investigator on forty-seven cases resulting in conviction.' You keep your voice level. Professional. The jury needs to see a methodical investigator, not an emotional crusader.",
      question: "The prosecutor moves to the investigation. Where do you start?",
      timerSeconds: 20,
      choices: [
        { id: 'a', text: "The initial tip that broke the case", nextNode: "5-s2-facts-tip", consequence: "How it began..." },
        { id: 'b', text: "The evidence collection process", nextNode: "5-s2-facts-evidence", consequence: "Methodical work..." },
        { id: 'c', text: "The connections to Morrison", nextNode: "5-s2-facts-morrison", consequence: "Building the case..." },
        { id: 'd', text: "The survivor's rescue", nextNode: "5-s2-facts-rescue", consequence: "The breakthrough..." },
      ],
    },
    "5-s2-facts-tip": { id: "5-s2-facts-tip", type: "narrative", text: "'A Coast Guard lieutenant noticed unusual boat traffic. Patterns that didn't match fishing or recreation. He flagged it. We investigated.' You don't mention the months of dead ends before that. The cases that went nowhere. Just this one - the one that led to the island.", nextNode: "5-s3" },
    "5-s2-facts-evidence": { id: "5-s2-facts-evidence", type: "narrative", text: "'Every piece of evidence was collected following federal protocols. Chain of custody documented. Multiple verification at each stage.' You walk through the process like a textbook. Defense can't claim sloppiness if you give them nothing to work with.", nextNode: "5-s3", document: { title: "EVIDENCE_PROTOCOL.pdf", preview: "Complete chain of custody documentation...", pdfUrl: "/documents/evidence-protocol.pdf" } },
    "5-s2-facts-morrison": { id: "5-s2-facts-morrison", type: "narrative", text: "'Financial records showed payments from shell companies to the island's operating budget. Those shell companies trace back to accounts controlled by the defendant.' You present the connections like a math equation. Cold. Logical. Undeniable.", nextNode: "5-s3" },
    "5-s2-facts-rescue": { id: "5-s2-facts-rescue", type: "narrative", text: "'The survivor made contact with Coast Guard vessel Resolute at 0523 hours. She provided information that led to the raid.' You don't describe her condition when they found her. The jury doesn't need those details. Not yet.", nextNode: "5-s3" },
    "5-s2-dedication": {
      id: "5-s2-dedication",
      type: "choice",
      text: "'This case... I've worked hundreds of investigations. But the scope of what we found on that island - it demanded our full attention. My team worked around the clock for six months.' The jury is listening. Some lean forward.",
      question: "How do you describe what you found?",
      timerSeconds: 20,
      choices: [
        { id: 'a', text: "Focus on the systematic nature of the operation", nextNode: "5-s2-dedication-system", consequence: "Show the scale..." },
        { id: 'b', text: "Emphasize the victims' experiences", nextNode: "5-s2-dedication-victims", consequence: "Make it real..." },
        { id: 'c', text: "Detail Morrison's specific involvement", nextNode: "5-s2-dedication-morrison", consequence: "Connect him directly..." },
        { id: 'd', text: "Describe the evidence trail", nextNode: "5-s2-dedication-evidence", consequence: "Follow the facts..." },
      ],
    },
    "5-s2-dedication-system": { id: "5-s2-dedication-system", type: "narrative", text: "'This wasn't random violence. It was a business. Logistics. Schedules. Payment systems. Everything documented because they never expected to be caught. That documentation is what convicted them.' The word 'business' hangs in the air. The jury understands - this was calculated evil.", nextNode: "5-s3" },
    "5-s2-dedication-victims": { id: "5-s2-dedication-victims", type: "narrative", text: "'Thirty-seven victims that we've identified. Some held for weeks. Some for months. Families who didn't know if their daughters were alive or dead.' A juror in the back row wipes her eyes. Good. They need to feel this.", nextNode: "5-s3", document: { title: "VICTIM_RECORDS.pdf", preview: "Thirty-seven confirmed victims. Documentation of captivity...", pdfUrl: "/documents/victim-records.pdf" } },
    "5-s2-dedication-morrison": { id: "5-s2-dedication-morrison", type: "narrative", text: "'The defendant's phone records place him on the island seventeen times. His financial records show payments to the operation. His communications reference 'inventory' and 'merchandise' - their words for human beings.'", nextNode: "5-s3" },
    "5-s2-dedication-evidence": { id: "5-s2-dedication-evidence", type: "narrative", text: "'The evidence speaks for itself. Surveillance footage. Financial records. Witness testimony. Communications. Everything we collected points to one conclusion - the defendant was central to this operation.'", nextNode: "5-s3" },
    "5-s2-experience": {
      id: "5-s2-experience",
      type: "choice",
      text: "'I've investigated trafficking operations before. Usually small-scale - local pimps, isolated incidents. This was different. This was organized. Protected. Funded.' You see a flicker of something in Morrison's eyes. Fear? Anger?",
      question: "How do you explain what made this case different?",
      timerSeconds: 20,
      choices: [
        { id: 'a', text: "The level of organization", nextNode: "5-s2-experience-org", consequence: "Professional operation..." },
        { id: 'b', text: "The powerful people involved", nextNode: "5-s2-experience-power", consequence: "No one is above the law..." },
        { id: 'c', text: "The geographic isolation", nextNode: "5-s2-experience-isolation", consequence: "Designed to hide..." },
        { id: 'd', text: "The cover-up attempts", nextNode: "5-s2-experience-coverup", consequence: "They tried to hide it..." },
      ],
    },
    "5-s2-experience-org": { id: "5-s2-experience-org", type: "narrative", text: "'Most trafficking operations are chaotic. This one had schedules. Security protocols. Medical staff. It was run like a corporation because that's what it was - a criminal enterprise with a product, clients, and profit margins.'", nextNode: "5-s3" },
    "5-s2-experience-power": { id: "5-s2-experience-power", type: "narrative", text: "'In most cases, we catch the small players. Here, we followed the money upward. Past the guards. Past the managers. To the people who funded it. Who used it. Who protected it.' You don't look at Morrison. You don't need to.", nextNode: "5-s3", document: { title: "POWER_STRUCTURE.pdf", preview: "Organizational hierarchy. Morrison at funding level...", pdfUrl: "/documents/power-structure.pdf" } },
    "5-s2-experience-isolation": { id: "5-s2-experience-isolation", type: "narrative", text: "'The island wasn't chosen randomly. No jurisdiction. Limited access. Natural barriers. If you wanted to build a place where laws didn't apply, you couldn't design it better.' The jury looks at the island photos on the screen. Paradise as prison.", nextNode: "5-s3" },
    "5-s2-experience-coverup": { id: "5-s2-experience-coverup", type: "narrative", text: "'When we got close, evidence started disappearing. Witnesses stopped cooperating. Pressure came from... unexpected places.' You choose your words carefully. 'But we preserved what we could. And what we have is enough.'", nextNode: "5-s3" },
    "5-s2-personal": {
      id: "5-s2-personal",
      type: "choice",
      text: "'I'll be honest with the court. This case affected me. The things we found... the suffering we documented... you don't walk away from that unchanged.' A risk - defense might claim bias. But juries trust honesty.",
      question: "How do you address the emotional impact without undermining your objectivity?",
      timerSeconds: 20,
      choices: [
        { id: 'a', text: "Acknowledge it but emphasize professionalism", nextNode: "5-s2-personal-pro", consequence: "Balance is key..." },
        { id: 'b', text: "Explain how emotion drives thorough investigation", nextNode: "5-s2-personal-thorough", consequence: "Care means attention..." },
        { id: 'c', text: "Connect it to why justice matters", nextNode: "5-s2-personal-justice", consequence: "This is why we serve..." },
        { id: 'd', text: "Pivot to the evidence itself", nextNode: "5-s2-personal-evidence", consequence: "Let facts speak..." },
      ],
    },
    "5-s2-personal-pro": { id: "5-s2-personal-pro", type: "narrative", text: "'Being affected by evil doesn't make my work less objective. It makes it more thorough. Every detail mattered. Every protocol followed. Because this case deserved our best work.' The prosecutor nods slightly. Good answer.", nextNode: "5-s3" },
    "5-s2-personal-thorough": { id: "5-s2-personal-thorough", type: "narrative", text: "'When you care about justice, you don't cut corners. You document everything. Check everything twice. Because you know defense will look for any weakness.' You meet the jury's eyes. 'They won't find one in this case.'", nextNode: "5-s3" },
    "5-s2-personal-justice": { id: "5-s2-personal-justice", type: "narrative", text: "'Twenty years in this job, you see things that test you. But that's why we do it - because someone has to stand between predators and their victims. Someone has to say: this is wrong, and there will be consequences.'", nextNode: "5-s3", document: { title: "COLE_STATEMENT.pdf", preview: "Detective's personal account. Professional dedication...", pdfUrl: "/documents/cole-statement.pdf" } },
    "5-s2-personal-evidence": { id: "5-s2-personal-evidence", type: "narrative", text: "'But feelings don't convict. Evidence does. So let me walk you through what we found.' You shift to the facts. Systematic. Methodical. The emotion gave context; now the evidence will build the case.", nextNode: "5-s3" },

    // ========== STAGE 3: THE CROSS-EXAMINATION ==========
    "5-s3": {
      id: "5-s3",
      type: "choice",
      text: "Morrison's lead attorney approaches. Richard Blackwell - $2000 suits and a reputation for destroying witnesses. 'Detective Cole. Thank you for your service.' His tone is acid. 'Let's talk about your investigation. You had... strong feelings about my client from the beginning, didn't you?'",
      question: "STAGE 3/5 — How do you handle the opening attack?",
      timerSeconds: 20,
      choices: [
        { id: 'a', text: "Deny any bias - stick to evidence", nextNode: "5-s3-deny", consequence: "Pure professionalism..." },
        { id: 'b', text: "Acknowledge concern but defend objectivity", nextNode: "5-s3-acknowledge", consequence: "Honest but firm..." },
        { id: 'c', text: "Redirect to what the evidence shows", nextNode: "5-s3-redirect", consequence: "Facts over feelings..." },
        { id: 'd', text: "Challenge the implication directly", nextNode: "5-s3-challenge", consequence: "Don't let him control..." },
      ],
    },
    "5-s3-deny": {
      id: "5-s3-deny",
      type: "choice",
      text: "'My feelings are irrelevant. The evidence is what matters.' Blackwell smiles - he was hoping you'd say that. 'So you had no preconceptions? No assumptions? You investigated with a completely open mind?' He's setting a trap.",
      question: "How do you respond?",
      timerSeconds: 20,
      choices: [
        { id: 'a', text: "Maintain the position - evidence speaks", nextNode: "5-s3-deny-maintain", consequence: "Stand firm..." },
        { id: 'b', text: "Clarify the distinction between suspicion and bias", nextNode: "5-s3-deny-clarify", consequence: "Nuance matters..." },
        { id: 'c', text: "Turn it back on him", nextNode: "5-s3-deny-turn", consequence: "Play offense..." },
        { id: 'd', text: "Ask him to rephrase", nextNode: "5-s3-deny-rephrase", consequence: "Buy time..." },
      ],
    },
    "5-s3-deny-maintain": { id: "5-s3-deny-maintain", type: "narrative", text: "'The evidence led where it led. I followed procedure at every step. Every document is logged. Every interview recorded. If there was bias, you'd see it in the work.' You meet his eyes. 'You don't.'", nextNode: "5-s4" },
    "5-s3-deny-clarify": { id: "5-s3-deny-clarify", type: "narrative", text: "'There's a difference between suspicion based on evidence and bias that taints investigation. When evidence pointed to your client, we investigated further. When it pointed elsewhere, we followed that too. That's procedure.'", nextNode: "5-s4", document: { title: "INVESTIGATION_LOG.pdf", preview: "Complete investigation record. All leads followed...", pdfUrl: "/documents/investigation-log.pdf" } },
    "5-s3-deny-turn": { id: "5-s3-deny-turn", type: "narrative", text: "'Let me ask you something, counselor. If evidence showed your client was innocent, wouldn't I be biased toward that too? I follow evidence. That's my job. The evidence led to your client.'", nextNode: "5-s4" },
    "5-s3-deny-rephrase": { id: "5-s3-deny-rephrase", type: "narrative", text: "'Could you be more specific? Are you asking if I had theories, or if I let theories override evidence?' Blackwell pauses. You've forced him to be precise - and precision isn't where he wants this to go.", nextNode: "5-s4" },
    "5-s3-acknowledge": {
      id: "5-s3-acknowledge",
      type: "choice",
      text: "'When the evidence started pointing to a sitting senator, I was... cautious. Cases against powerful people get scrutinized. I made sure everything was documented three times over.' Blackwell raises an eyebrow. 'Cautious. Not suspicious?'",
      question: "How do you clarify?",
      timerSeconds: 20,
      choices: [
        { id: 'a', text: "Explain the extra documentation standards", nextNode: "5-s3-acknowledge-docs", consequence: "Show the work..." },
        { id: 'b', text: "Describe the review process", nextNode: "5-s3-acknowledge-review", consequence: "Multiple eyes..." },
        { id: 'c', text: "Point out defense has access to everything", nextNode: "5-s3-acknowledge-access", consequence: "Transparency..." },
        { id: 'd', text: "Emphasize the weight of the evidence", nextNode: "5-s3-acknowledge-weight", consequence: "Overwhelming proof..." },
      ],
    },
    "5-s3-acknowledge-docs": { id: "5-s3-acknowledge-docs", type: "narrative", text: "'Every interview was recorded. Every piece of evidence photographed and catalogued with witnesses present. Everything cross-referenced. Defense has had full access to all of it. If something was wrong, they would have found it.'", nextNode: "5-s4", document: { title: "DOCUMENTATION_STANDARDS.pdf", preview: "Triple-verified documentation. Full defense access...", pdfUrl: "/documents/documentation.pdf" } },
    "5-s3-acknowledge-review": { id: "5-s3-acknowledge-review", type: "narrative", text: "'The investigation was reviewed by FBI oversight, the DA's office, and an independent prosecutor before charges were filed. Multiple sets of eyes on every piece of evidence. Multiple opportunities to find problems.'", nextNode: "5-s4" },
    "5-s3-acknowledge-access": { id: "5-s3-acknowledge-access", type: "narrative", text: "'Mr. Blackwell, your team has had access to every document we collected. Every recording. Every photograph. If there were issues with the investigation, you've had months to find them.' You let that hang. He hasn't found anything.", nextNode: "5-s4" },
    "5-s3-acknowledge-weight": { id: "5-s3-acknowledge-weight", type: "narrative", text: "'The evidence isn't borderline, counselor. Surveillance footage. Financial records. Witness testimony. Phone records. Physical evidence from the scene. Each piece supports the others. That's not bias - that's convergent proof.'", nextNode: "5-s4" },
    "5-s3-redirect": {
      id: "5-s3-redirect",
      type: "choice",
      text: "'What I felt doesn't change what the evidence shows. Surveillance footage of your client on the island. Financial transfers from his accounts. Communications using coded language that matches what we found. Should I walk through each item?'",
      question: "Blackwell changes tactics. What angle does he try next?",
      timerSeconds: 20,
      choices: [
        { id: 'a', text: "Questions the surveillance footage authenticity", nextNode: "5-s3-redirect-footage", consequence: "Attack the evidence..." },
        { id: 'b', text: "Suggests alternative explanations for finances", nextNode: "5-s3-redirect-finances", consequence: "Muddy the waters..." },
        { id: 'c', text: "Attacks witness credibility", nextNode: "5-s3-redirect-witnesses", consequence: "Undermine testimony..." },
        { id: 'd', text: "Implies evidence was planted", nextNode: "5-s3-redirect-planted", consequence: "Conspiracy theory..." },
      ],
    },
    "5-s3-redirect-footage": { id: "5-s3-redirect-footage", type: "narrative", text: "'The footage was analyzed by three independent forensic labs. No evidence of manipulation. The metadata is consistent with the camera's internal clock, which was verified against network time servers. It's your client. On that island. Walking among victims.'", nextNode: "5-s4", document: { title: "FORENSIC_ANALYSIS.pdf", preview: "Triple-verified surveillance footage. No manipulation detected...", pdfUrl: "/documents/forensic-analysis.pdf" } },
    "5-s3-redirect-finances": { id: "5-s3-redirect-finances", type: "narrative", text: "'Your client's attorney can suggest 'charitable donations' and 'consulting fees,' but the accounts those payments went to funded the island's operations directly. Guards' salaries. Supply runs. 'Entertainment' expenses. The money trail is clear.'", nextNode: "5-s4" },
    "5-s3-redirect-witnesses": { id: "5-s3-redirect-witnesses", type: "narrative", text: "'Seventeen witnesses. Island staff who flipped. Coast Guard personnel. Financial analysts. And one survivor who identified your client from a photo array before we told her who he was. Their stories corroborate each other and the physical evidence.'", nextNode: "5-s4" },
    "5-s3-redirect-planted": { id: "5-s3-redirect-planted", type: "narrative", text: "'Mr. Blackwell, are you suggesting that the FBI, Coast Guard, local law enforcement, three forensic labs, and multiple independent witnesses all conspired to frame your client? That's quite a conspiracy. Almost as elaborate as the one he ran.'", nextNode: "5-s4" },
    "5-s3-challenge": {
      id: "5-s3-challenge",
      type: "choice",
      text: "'Counselor, are you asking if I had feelings about a senator who funded human trafficking? Yes. I did. I have feelings about all predators. It doesn't change the evidence, which is what we're here to discuss.'",
      question: "Blackwell tries another approach. How do you handle it?",
      timerSeconds: 20,
      choices: [
        { id: 'a', text: "Stay aggressive - don't cede ground", nextNode: "5-s3-challenge-aggressive", consequence: "Control the exchange..." },
        { id: 'b', text: "Moderate your tone for the jury", nextNode: "5-s3-challenge-moderate", consequence: "Appear reasonable..." },
        { id: 'c', text: "Let him talk himself into a corner", nextNode: "5-s3-challenge-wait", consequence: "Patience wins..." },
        { id: 'd', text: "Defer to the evidence repeatedly", nextNode: "5-s3-challenge-evidence", consequence: "Broken record..." },
      ],
    },
    "5-s3-challenge-aggressive": { id: "5-s3-challenge-aggressive", type: "narrative", text: "'If counsel wants to question my integrity, let him point to a specific failure. A procedure not followed. Evidence mishandled. A witness coached. He won't, because he can't. The investigation was clean.'", nextNode: "5-s4" },
    "5-s3-challenge-moderate": { id: "5-s3-challenge-moderate", type: "narrative", text: "You take a breath. 'I understand defense counsel's job is to question everything. That's how the system works. But when he's done questioning, the evidence will still be there. All of it. Pointing to one conclusion.'", nextNode: "5-s4" },
    "5-s3-challenge-wait": { id: "5-s3-challenge-wait", type: "narrative", text: "Blackwell tries three more angles. Each time, you give short, factual answers. Each time, he fails to land a blow. The jury watches him flounder. Sometimes the best cross-examination defense is letting the attacker exhaust himself.", nextNode: "5-s4" },
    "5-s3-challenge-evidence": { id: "5-s3-challenge-evidence", type: "narrative", text: "'The evidence shows what it shows. The surveillance footage. The financial records. The witness testimony. The physical evidence. Would counsel like me to walk through each item again?' You've said it four times now. It's sinking in.", nextNode: "5-s4", document: { title: "EVIDENCE_SUMMARY.pdf", preview: "Complete evidence summary. Every item catalogued...", pdfUrl: "/documents/evidence-summary.pdf" } },

    // ========== STAGE 4: THE REVELATION ==========
    "5-s4": {
      id: "5-s4",
      type: "choice",
      text: "After three hours, Blackwell finally sits. The prosecutor approaches for redirect. 'Detective Cole, one more question. During your investigation, did you uncover evidence of anyone else involved in this operation? Anyone the defense hasn't mentioned?' This is it. The door is open.",
      question: "STAGE 4/5 — How do you handle this opening?",
      timerSeconds: 20,
      choices: [
        { id: 'a', text: "Mention Judge Harrison's connection", nextNode: "5-s4-harrison", consequence: "Expand the conspiracy..." },
        { id: 'b', text: "Reference other names from the documents", nextNode: "5-s4-names", consequence: "Show the network..." },
        { id: 'c', text: "Describe the organizational structure", nextNode: "5-s4-structure", consequence: "This was bigger..." },
        { id: 'd', text: "Stick to Morrison - he's the defendant", nextNode: "5-s4-focused", consequence: "Stay on target..." },
      ],
    },
    "5-s4-harrison": {
      id: "5-s4-harrison",
      type: "choice",
      text: "'The financial investigation uncovered connections to Judge Harrison - the same judge who was originally assigned to this case before recusing himself. He's currently cooperating with federal investigators.' The courtroom erupts. Morrison's face goes white.",
      question: "The judge calls for order. What do you add?",
      timerSeconds: 20,
      choices: [
        { id: 'a', text: "Harrison has been providing names", nextNode: "5-s4-harrison-names", consequence: "The dam is breaking..." },
        { id: 'b', text: "The investigation is expanding", nextNode: "5-s4-harrison-expanding", consequence: "More to come..." },
        { id: 'c', text: "Morrison was not the top of the organization", nextNode: "5-s4-harrison-top", consequence: "Bigger fish..." },
        { id: 'd', text: "Let it stand - less is more", nextNode: "5-s4-harrison-stand", consequence: "Let them wonder..." },
      ],
    },
    "5-s4-harrison-names": { id: "5-s4-harrison-names", type: "narrative", text: "'Judge Harrison has provided detailed information about other participants. Names, dates, activities. The investigation is ongoing, but I can tell you this much: Senator Morrison was not operating alone.' You watch the jury process this. The scope of it. The power of it.", nextNode: "5-s5", document: { title: "HARRISON_COOPERATION.pdf", preview: "Judge Harrison testimony. Names provided. Investigation expanding...", pdfUrl: "/documents/harrison-cooperation.pdf" } },
    "5-s4-harrison-expanding": { id: "5-s4-harrison-expanding", type: "narrative", text: "'What started as a single investigation has grown. Harrison's cooperation has opened doors we didn't know existed. This case - Morrison's case - is just the beginning.' The jury understands now. This isn't one monster. It's a network.", nextNode: "5-s5" },
    "5-s4-harrison-top": { id: "5-s4-harrison-top", type: "narrative", text: "'Senator Morrison funded and used the operation. But he didn't create it. He wasn't at the top. There are others - people whose names you would recognize - who are now subjects of federal investigation.' Morrison looks like he might be sick.", nextNode: "5-s5" },
    "5-s4-harrison-stand": { id: "5-s4-harrison-stand", type: "narrative", text: "You stop there. Let the implication hang. The jury doesn't need every detail - they need to understand that this was bigger than one man. That the system they're asked to deliver justice through is working. That more is coming.", nextNode: "5-s5" },
    "5-s4-names": {
      id: "5-s4-names",
      type: "choice",
      text: "'The documents we recovered included references to multiple individuals. Some have been identified. Some are still under investigation. But the pattern is clear - this was a network with participants at the highest levels of business and government.'",
      question: "How specific do you get?",
      timerSeconds: 20,
      choices: [
        { id: 'a', text: "Mention sectors without names", nextNode: "5-s4-names-sectors", consequence: "Imply broadly..." },
        { id: 'b', text: "Describe the types of involvement", nextNode: "5-s4-names-types", consequence: "Funders, users, protectors..." },
        { id: 'c', text: "Reference the ongoing investigations", nextNode: "5-s4-names-ongoing", consequence: "More to come..." },
        { id: 'd', text: "Focus back on Morrison's specific role", nextNode: "5-s4-names-morrison", consequence: "This defendant..." },
      ],
    },
    "5-s4-names-sectors": { id: "5-s4-names-sectors", type: "narrative", text: "'Tech executives. Political figures. Military contractors. Financial services. The client list we recovered reads like a Who's Who of American power.' You let that sink in. Some jurors glance at Morrison differently now. He's not an aberration. He's a symptom.", nextNode: "5-s5", document: { title: "CLIENT_SECTORS.pdf", preview: "Network participants across sectors. Pattern of power and access...", pdfUrl: "/documents/client-sectors.pdf" } },
    "5-s4-names-types": { id: "5-s4-names-types", type: "narrative", text: "'Some funded the operation. Some used its services. Some provided protection - killing investigations, blocking legislation. Each played a role in keeping this running for years.' A system. A machine. Morrison was a cog - but a willing one.", nextNode: "5-s5" },
    "5-s4-names-ongoing": { id: "5-s4-names-ongoing", type: "narrative", text: "'I've been asked not to comment on ongoing investigations. But I can tell you that the work isn't done. The island was one location. The network was much larger. We're still following the threads.'", nextNode: "5-s5" },
    "5-s4-names-morrison": { id: "5-s4-names-morrison", type: "narrative", text: "'But we're here for Senator Morrison. And what I can tell you definitively is that his involvement was central. His money. His presence. His protection. Whatever else we find, his guilt is established.'", nextNode: "5-s5" },
    "5-s4-structure": {
      id: "5-s4-structure",
      type: "choice",
      text: "'What we uncovered wasn't a criminal enterprise - it was an institution. Dedicated staff. Regular schedules. Client management. They ran this like a business because that's what it was. A business that traded in human beings.'",
      question: "How do you describe the scale?",
      timerSeconds: 20,
      choices: [
        { id: 'a', text: "The financial scale", nextNode: "5-s4-structure-financial", consequence: "Millions moved..." },
        { id: 'b', text: "The operational scale", nextNode: "5-s4-structure-operational", consequence: "Years of operation..." },
        { id: 'c', text: "The victim count", nextNode: "5-s4-structure-victims", consequence: "Human cost..." },
        { id: 'd', text: "The protection infrastructure", nextNode: "5-s4-structure-protection", consequence: "How they stayed hidden..." },
      ],
    },
    "5-s4-structure-financial": { id: "5-s4-structure-financial", type: "narrative", text: "'Conservative estimates put the total revenue at over $50 million across five years. That money came from somewhere - from clients with resources. And it went somewhere - into real estate, investments, more operations.'", nextNode: "5-s5", document: { title: "FINANCIAL_SCALE.pdf", preview: "$50M+ estimated revenue. Complex money movement...", pdfUrl: "/documents/financial-scale.pdf" } },
    "5-s4-structure-operational": { id: "5-s4-structure-operational", type: "narrative", text: "'Five years of continuous operation. At least fifty staff members at any given time. Regular supply deliveries. Medical personnel on site. This wasn't improvised - it was engineered.'", nextNode: "5-s5" },
    "5-s4-structure-victims": { id: "5-s4-structure-victims", type: "narrative", text: "'Thirty-seven victims we've identified with certainty. But the records suggest more. Some who never made it off the island. Some we may never identify. Each one a person with a family wondering what happened to them.'", nextNode: "5-s5" },
    "5-s4-structure-protection": { id: "5-s4-structure-protection", type: "narrative", text: "'The operation lasted five years because it was protected. Investigations that went nowhere. Witnesses who stopped cooperating. Cases that fell apart. Someone was making sure this stayed hidden.' You glance at Morrison. 'Now we know who.'", nextNode: "5-s5" },
    "5-s4-focused": {
      id: "5-s4-focused",
      type: "choice",
      text: "'The investigation continues, but today is about Senator Morrison. And the evidence against him specifically is overwhelming. Shall I summarize?'",
      question: "How do you close your testimony on Morrison?",
      timerSeconds: 20,
      choices: [
        { id: 'a', text: "Walk through each piece of evidence again", nextNode: "5-s4-focused-evidence", consequence: "Repetition works..." },
        { id: 'b', text: "Focus on the strongest points", nextNode: "5-s4-focused-strongest", consequence: "Quality over quantity..." },
        { id: 'c', text: "Connect him personally to victims", nextNode: "5-s4-focused-victims", consequence: "Make it human..." },
        { id: 'd', text: "Emphasize his position of trust", nextNode: "5-s4-focused-trust", consequence: "A senator..." },
      ],
    },
    "5-s4-focused-evidence": { id: "5-s4-focused-evidence", type: "narrative", text: "You walk through it methodically. Surveillance footage - seventeen visits documented. Financial records - $3.2 million in payments. Communications - coded language about 'inventory.' Phone records - present during the escape. Each item a nail in the coffin.", nextNode: "5-s5", document: { title: "MORRISON_EVIDENCE.pdf", preview: "Complete evidence summary against Morrison. 17 visits, $3.2M payments...", pdfUrl: "/documents/morrison-evidence.pdf" } },
    "5-s4-focused-strongest": { id: "5-s4-focused-strongest", type: "narrative", text: "'The surveillance footage shows him on the island. The survivor identified him in a photo array. His financial records show payments to the operation. That's not circumstantial. That's direct evidence of participation.'", nextNode: "5-s5" },
    "5-s4-focused-victims": { id: "5-s4-focused-victims", type: "narrative", text: "'The survivor who testified - she saw Senator Morrison. Spoke to him. He looked at her like she was furniture to be used. Her testimony, combined with the physical evidence, leaves no doubt about his role.'", nextNode: "5-s5" },
    "5-s4-focused-trust": { id: "5-s4-focused-trust", type: "narrative", text: "'A United States Senator. Sworn to serve the people. Using that position to fund and protect human trafficking. That's not just a crime - it's a betrayal of everything public office is supposed to mean.'", nextNode: "5-s5" },

    // ========== STAGE 5: THE VERDICT ==========
    "5-s5": {
      id: "5-s5",
      type: "choice",
      text: "Days pass. Closing arguments. Jury instructions. And then - waiting. You can't eat. Can't sleep. Everything rides on twelve strangers in a room. Finally, at 3:47 PM on a Thursday, the bailiff emerges. 'Jury's reached a verdict.'",
      question: "STAGE 5/5 — As you return to the courtroom, what do you focus on?",
      timerSeconds: 20,
      choices: [
        { id: 'a', text: "Watch Morrison's reaction", nextNode: "5-s5-morrison", consequence: "See him face justice..." },
        { id: 'b', text: "Find the survivor in the gallery", nextNode: "5-s5-survivor", consequence: "She needs to see this..." },
        { id: 'c', text: "Observe the jury", nextNode: "5-s5-jury", consequence: "Read their faces..." },
        { id: 'd', text: "Focus on your own thoughts", nextNode: "5-s5-thoughts", consequence: "Prepare yourself..." },
      ],
    },
    "5-s5-morrison": { id: "5-s5-morrison", type: "narrative", text: "Morrison sits rigid, hands flat on the defense table. The confident smile is gone. For the first time since you met him, he looks afraid. Good. He should be afraid. The system he thought he controlled is about to pass judgment.", nextNode: "5-complete" },
    "5-s5-survivor": { id: "5-s5-survivor", type: "narrative", text: "She's in the back row, flanked by FBI agents. Your eyes meet. You nod. She nods back. Whatever happens in the next five minutes, she survived. She fought. She testified. Nothing can take that away.", nextNode: "5-complete", document: { title: "SURVIVOR_STATEMENT.pdf", preview: "Final witness statement. Testimony concluded. Awaiting verdict...", pdfUrl: "/documents/survivor-statement.pdf" } },
    "5-s5-jury": { id: "5-s5-jury", type: "narrative", text: "The jury files in. You try to read their faces. Juror 7 - the one you worried about - won't look at Morrison. The foreperson carries the verdict form like it weighs a thousand pounds. They know what they hold. They understand the weight.", nextNode: "5-complete" },
    "5-s5-thoughts": { id: "5-s5-thoughts", type: "narrative", text: "Twenty years of this work. Hundreds of cases. But this one... this one mattered differently. Whatever the verdict, you did everything right. The investigation was clean. The evidence was solid. The truth was told. That has to be enough.", nextNode: "5-complete" },

    // ========== CHAPTER 5 COMPLETE ==========
    "5-complete": {
      id: "5-complete",
      type: "chapter-end",
      text: "The bailiff's voice: 'All rise.' The foreperson stands. 'On the count of human trafficking: guilty. On the count of conspiracy: guilty. On the count of obstruction of justice: guilty.' Fourteen counts. Fourteen guilty verdicts. Morrison sways. His lawyer catches him. The survivor gasps, then sobs. The gallery erupts - cheers from victims' families, shocked silence from Morrison's supporters. The judge bangs the gavel. 'Order!' You feel... empty. Not triumphant. Just tired. Justice was served today. But the investigation isn't over. Harrison named names. The conspiracy runs deeper. Tomorrow, the real work continues.",
      chapterComplete: {
        chapter: 5,
        nextChapter: 6,
        summary: "Guilty on all counts. Senator Morrison faces life in prison. But this is just the beginning - Harrison's cooperation has revealed a network of powerful conspirators. The investigation continues in Chapter 6."
      },
    },
  },
};