import { BranchingChapter } from '../types';

/**
 * CHAPTER 8: THE FILES - 5 Stages, full branching
 * FINAL CHAPTER: The survivor exposes everything.
 * PERSPECTIVE SHIFT: Back to YOU - the survivor from Chapter 1.
 * The powerful tried to bury the truth. You won't let them.
 * NO DEATH NODES - This is about justice and exposure
 */
export const CHAPTER_8: BranchingChapter = {
  id: 8,
  title: "CHAPTER 8",
  subtitle: "The Files",
  startNode: "8-s1",
  nodes: {
    // ========== STAGE 1: THE COVER-UP ==========
    "8-s1": {
      id: "8-s1",
      type: "choice",
      text: "Six months since The Gathering raid. You've watched from your new life, under your new name, as the trials played out on television. Morrison - life in prison. Ashford - life in prison. Six of The Board members - convicted. But the seventh, 'The Crown,' was never charged. 'Insufficient evidence,' they said. 'National security concerns.' You know the truth: she's protected. And now the government is moving to seal the files permanently. Detective Cole calls you with news: 'They're burying it. The full client list, the videos, the photographs - all of it classified for 75 years.' He pauses. 'Unless someone leaks it first.'",
      question: "STAGE 1/5 — What is your reaction?",
      timerSeconds: 20,
      choices: [
        { id: 'a', text: "I have a copy of everything", nextNode: "8-s1-copy", consequence: "Insurance policy..." },
        { id: 'b', text: "Who is The Crown? Why is she protected?", nextNode: "8-s1-crown", consequence: "Know your enemy..." },
        { id: 'c', text: "What happens if I go public?", nextNode: "8-s1-public", consequence: "Consequences..." },
        { id: 'd', text: "I can't do this alone", nextNode: "8-s1-allies", consequence: "Need help..." },
      ],
    },
    "8-s1-copy": {
      id: "8-s1-copy",
      type: "choice",
      text: "Before the trials, you made copies. Everything Elizabeth Kane provided. Everything seized from Ashford's servers. Everything from The Gathering. Names. Dates. Photographs. Videos. Financial records. The complete client list - 247 names spanning three decades. Politicians. Celebrities. Business leaders. Royalty. All of it sitting on encrypted drives hidden in three locations.",
      question: "Why did you keep copies?",
      timerSeconds: 20,
      choices: [
        { id: 'a', text: "I knew they'd try to bury it", nextNode: "8-s1-copy-knew", consequence: "You saw this coming..." },
        { id: 'b', text: "Insurance - in case they came for me", nextNode: "8-s1-copy-insurance", consequence: "Protection..." },
        { id: 'c', text: "For the other survivors who deserve the truth", nextNode: "8-s1-copy-survivors", consequence: "For them..." },
        { id: 'd', text: "Because the world needs to know", nextNode: "8-s1-copy-world", consequence: "The truth matters..." },
      ],
    },
    "8-s1-copy-knew": { id: "8-s1-copy-knew", type: "narrative", text: "You learned on that island: powerful people protect each other. The same system that let this happen for decades wasn't going to suddenly deliver full justice. Some names were always going to be protected. Some files were always going to disappear. Unless someone made sure they didn't.", nextNode: "8-s2", document: { title: "CLASSIFIED_ORDER.pdf", preview: "Government order to seal files. 75-year classification...", pdfUrl: "/documents/classified-order.pdf" } },
    "8-s1-copy-insurance": { id: "8-s1-copy-insurance", type: "narrative", text: "They've already tried once. A break-in at your old apartment - nothing taken, just a message. A car that followed you for three days. A stranger asking questions at your workplace. They want you scared. They want you silent. The files are your shield.", nextNode: "8-s2" },
    "8-s1-copy-survivors": { id: "8-s1-copy-survivors", type: "narrative", text: "Thirty-seven confirmed victims from the island. Hundreds more from The Gathering years. Most never got justice. Some were paid off. Some were threatened into silence. Some died before they could testify. They deserve to have their stories told. Their abusers deserve to be named.", nextNode: "8-s2" },
    "8-s1-copy-world": { id: "8-s1-copy-world", type: "narrative", text: "This isn't just about one island or one organization. It's about a system that protects predators because they're powerful. That silences victims because they're not. The world thinks justice was served. The world needs to know the truth: most of them got away with it.", nextNode: "8-s2", document: { title: "UNPROSECUTED_LIST.pdf", preview: "187 names never charged. Evidence suppressed...", pdfUrl: "/documents/unprosecuted-list.pdf" } },
    "8-s1-crown": {
      id: "8-s1-crown",
      type: "choice",
      text: "'The Crown is Lady Victoria Ashworth,' Cole tells you. 'British aristocracy. Old money going back centuries. Her family has connections to intelligence services on three continents. She was at The Gathering - we have her on video. But the moment we tried to charge her, calls came from... high up. Very high up.'",
      question: "How high?",
      timerSeconds: 20,
      choices: [
        { id: 'a', text: "White House?", nextNode: "8-s1-crown-wh", consequence: "The President..." },
        { id: 'b', text: "Intelligence agencies?", nextNode: "8-s1-crown-intel", consequence: "CIA, MI6..." },
        { id: 'c', text: "International pressure?", nextNode: "8-s1-crown-international", consequence: "Foreign governments..." },
        { id: 'd', text: "All of them?", nextNode: "8-s1-crown-all", consequence: "Everyone..." },
      ],
    },
    "8-s1-crown-wh": { id: "8-s1-crown-wh", type: "narrative", text: "'The Attorney General personally called the prosecutors. Said charging Ashworth would 'damage critical diplomatic relationships.' The President's chief of staff attended three Gatherings in the 90s - he's on the client list. They're not protecting her. They're protecting themselves.'", nextNode: "8-s2" },
    "8-s1-crown-intel": { id: "8-s1-crown-intel", type: "narrative", text: "'The Ashworth family has provided 'services' to intelligence agencies for decades. Blackmail material on foreign leaders. Compromising situations arranged for targets. The island wasn't just about exploitation - it was about control. Charging her would expose operations going back to the Cold War.'", nextNode: "8-s2", document: { title: "INTEL_CONNECTIONS.pdf", preview: "Intelligence agency involvement documented...", pdfUrl: "/documents/intel-connections.pdf" } },
    "8-s1-crown-international": { id: "8-s1-crown-international", type: "narrative", text: "'The British government made it clear: charge Ashworth, and intelligence sharing stops. Trade negotiations freeze. The 'special relationship' ends. She's too connected to too many secrets. Prosecuting her would cause an international incident.'", nextNode: "8-s2" },
    "8-s1-crown-all": { id: "8-s1-crown-all", type: "narrative", text: "'All of them. Every power structure has people on that client list. Prosecuting everyone would collapse governments, crash markets, end careers across the globe. So they made a deal: sacrifice some, protect the rest. Morrison and Ashford were expendable. The Crown is not.'", nextNode: "8-s2" },
    "8-s1-public": {
      id: "8-s1-public",
      type: "choice",
      text: "'If you release the files...' Cole pauses. 'You'll be a hero to some. A target to others. They'll come after you legally - violation of classified information, theft of government documents. They might come after you other ways too. Are you prepared for that?'",
      question: "What are you most concerned about?",
      timerSeconds: 20,
      choices: [
        { id: 'a', text: "My safety", nextNode: "8-s1-public-safety", consequence: "They might try to silence me..." },
        { id: 'b', text: "Legal consequences", nextNode: "8-s1-public-legal", consequence: "Prison..." },
        { id: 'c', text: "Being believed", nextNode: "8-s1-public-believed", consequence: "Will anyone listen?" },
        { id: 'd', text: "Nothing - I've already survived worse", nextNode: "8-s1-public-nothing", consequence: "I'm not afraid anymore..." },
      ],
    },
    "8-s1-public-safety": { id: "8-s1-public-safety", type: "narrative", text: "'Once it's out, killing you doesn't help them - it just proves you were telling the truth. Your best protection is publicity. The more people see the files, the safer you are. They can't silence millions of witnesses.'", nextNode: "8-s2" },
    "8-s1-public-legal": { id: "8-s1-public-legal", type: "narrative", text: "'Whistleblower protections might apply. You're exposing crimes, not national security. And if they prosecute you, every news network will cover the trial - which means covering what's in those files. They might decide it's not worth the attention.'", nextNode: "8-s2", document: { title: "LEGAL_ANALYSIS.pdf", preview: "Whistleblower protection assessment. Prosecution risks...", pdfUrl: "/documents/legal-analysis.pdf" } },
    "8-s1-public-believed": { id: "8-s1-public-believed", type: "narrative", text: "'The evidence speaks for itself. Photographs. Videos. Financial records. Bank transfers with names attached. This isn't allegation - it's documentation. They'll try to discredit you, but the files are undeniable.'", nextNode: "8-s2" },
    "8-s1-public-nothing": { id: "8-s1-public-nothing", type: "narrative", text: "You spent months in captivity. Escaped through fire and water. Testified against senators. Watched your abusers sentenced to prison. What can they do to you now that's worse than what you've already survived? Nothing. You're not the scared girl they captured. You're the one who brought them down.", nextNode: "8-s2" },
    "8-s1-allies": {
      id: "8-s1-allies",
      type: "choice",
      text: "'You're not alone,' Cole assures you. 'Chen and the Clean Hands are still with us. The whistleblower, Kane, is willing to go public. Other survivors are ready to speak. And there are journalists who've been waiting years for something like this.'",
      question: "Who do you want to work with?",
      timerSeconds: 20,
      choices: [
        { id: 'a', text: "The journalists - they can amplify the message", nextNode: "8-s1-allies-press", consequence: "Media power..." },
        { id: 'b', text: "Other survivors - strength in numbers", nextNode: "8-s1-allies-survivors", consequence: "United voices..." },
        { id: 'c', text: "Kane - she knows the system inside", nextNode: "8-s1-allies-kane", consequence: "Inside knowledge..." },
        { id: 'd', text: "All of them - coordinated release", nextNode: "8-s1-allies-all", consequence: "Maximum impact..." },
      ],
    },
    "8-s1-allies-press": { id: "8-s1-allies-press", type: "narrative", text: "Three journalists have been tracking this story for years. One at the Times, one at the Guardian, one running an investigative podcast. They've been waiting for evidence they could publish. You have that evidence. Together, you can reach millions.", nextNode: "8-s2", document: { title: "MEDIA_CONTACTS.pdf", preview: "Journalist network established. Publication strategy...", pdfUrl: "/documents/media-contacts.pdf" } },
    "8-s1-allies-survivors": { id: "8-s1-allies-survivors", type: "narrative", text: "Twelve other survivors are ready to go public. Different years, different circumstances, same predators. When the files drop, they'll share their stories. Twelve voices confirming what the documents show. Impossible to dismiss. Impossible to ignore.", nextNode: "8-s2" },
    "8-s1-allies-kane": { id: "8-s1-allies-kane", type: "narrative", text: "Elizabeth Kane spent three years inside the system. She knows how they think, how they'll respond, how they'll try to spin it. 'Release everything at once,' she advises. 'Don't give them time to prepare a narrative. Overwhelm them with truth.'", nextNode: "8-s2" },
    "8-s1-allies-all": { id: "8-s1-allies-all", type: "narrative", text: "A coordinated effort. Journalists ready to publish. Survivors ready to speak. Kane ready to explain the documents. Cole ready to confirm the investigation. When you release the files, it won't be one voice - it'll be a chorus. Too loud to silence.", nextNode: "8-s2" },

    // ========== STAGE 2: THE PREPARATION ==========
    "8-s2": {
      id: "8-s2",
      type: "choice",
      text: "You retrieve the drives from their hiding places. Three copies, three locations. Inside: 247 names on the client list. 1,847 photographs. 312 videos. Financial records totaling $890 million in transactions. Communications going back thirty years. The complete documentation of a criminal empire that operated in plain sight. Everything the government wants to bury forever.",
      question: "STAGE 2/5 — How do you prepare for the release?",
      timerSeconds: 20,
      choices: [
        { id: 'a', text: "Verify and organize everything", nextNode: "8-s2-verify", consequence: "Make it undeniable..." },
        { id: 'b', text: "Redact victim identities for their protection", nextNode: "8-s2-redact", consequence: "Protect the innocent..." },
        { id: 'c', text: "Create a public-friendly summary", nextNode: "8-s2-summary", consequence: "Make it accessible..." },
        { id: 'd', text: "Set up distribution channels", nextNode: "8-s2-distribute", consequence: "Make it unstoppable..." },
      ],
    },
    "8-s2-verify": {
      id: "8-s2-verify",
      type: "choice",
      text: "Every document must be verified. Every photograph authenticated. Every claim backed by evidence. They'll try to dismiss this as fake, as conspiracy, as AI manipulation. You won't give them that opening. Kane helps you build an evidence package that's legally bulletproof.",
      question: "What evidence is most damning?",
      timerSeconds: 20,
      choices: [
        { id: 'a', text: "The client list with payment records", nextNode: "8-s2-verify-payments", consequence: "Follow the money..." },
        { id: 'b', text: "Photographs of powerful people at events", nextNode: "8-s2-verify-photos", consequence: "Faces don't lie..." },
        { id: 'c', text: "Communications discussing 'services'", nextNode: "8-s2-verify-comms", consequence: "Their own words..." },
        { id: 'd', text: "Victim testimony matching the records", nextNode: "8-s2-verify-testimony", consequence: "Corroboration..." },
      ],
    },
    "8-s2-verify-payments": { id: "8-s2-verify-payments", type: "narrative", text: "Bank transfers with names attached. Wire receipts. Cryptocurrency transactions traced to real identities. 247 people paid for 'services' - and the financial trail proves exactly what those services were. Money doesn't lie.", nextNode: "8-s3", document: { title: "PAYMENT_RECORDS.pdf", preview: "Complete financial documentation. 247 clients identified...", pdfUrl: "/documents/payment-records.pdf" } },
    "8-s2-verify-photos": { id: "8-s2-verify-photos", type: "narrative", text: "Photographs with metadata intact. Timestamps. GPS coordinates. Facial recognition matches to public figures. Images that place specific people in specific locations on specific dates - dates that match victim testimony and financial transfers.", nextNode: "8-s3" },
    "8-s2-verify-comms": { id: "8-s2-verify-comms", type: "narrative", text: "Emails and messages discussing 'fresh inventory,' 'client preferences,' 'special requests.' Communications that reveal not just participation but enthusiasm. These weren't people who stumbled into evil - they sought it out, paid for it, celebrated it.", nextNode: "8-s3", document: { title: "COMMUNICATIONS.pdf", preview: "Internal messages. Criminal intent documented...", pdfUrl: "/documents/communications.pdf" } },
    "8-s2-verify-testimony": { id: "8-s2-verify-testimony", type: "narrative", text: "Survivor statements that match the documents exactly. Descriptions that align with photographs. Dates that correspond to financial records. Every piece of evidence corroborated by human testimony. The truth from every angle.", nextNode: "8-s3" },
    "8-s2-redact": {
      id: "8-s2-redact",
      type: "choice",
      text: "The files contain victim information too. Names. Photographs. Details no survivor should have exposed without consent. You spend days carefully redacting - protecting the innocent while exposing the guilty. Some survivors want to be named. Others want to stay hidden. You respect both.",
      question: "How do you handle sensitive victim information?",
      timerSeconds: 20,
      choices: [
        { id: 'a', text: "Full redaction unless they consent", nextNode: "8-s2-redact-full", consequence: "Protect everyone..." },
        { id: 'b', text: "Reach out to each survivor personally", nextNode: "8-s2-redact-reach", consequence: "Give them the choice..." },
        { id: 'c', text: "Remove victim content entirely", nextNode: "8-s2-redact-remove", consequence: "Focus on perpetrators..." },
        { id: 'd', text: "Let an advocacy group handle it", nextNode: "8-s2-redact-advocacy", consequence: "Professional help..." },
      ],
    },
    "8-s2-redact-full": { id: "8-s2-redact-full", type: "narrative", text: "Every victim name blacked out. Every identifying detail removed. The abusers will be exposed; the abused will be protected. Some will come forward later, on their own terms. That's their right. Your job is to make sure the choice is theirs.", nextNode: "8-s3" },
    "8-s2-redact-reach": { id: "8-s2-redact-reach", type: "narrative", text: "You contact every survivor you can find. Explain what you're doing. Give them the choice. Seventeen choose to be named - they want the world to know what was done to them. The rest are protected. Everyone decides their own story.", nextNode: "8-s3", document: { title: "SURVIVOR_CONSENT.pdf", preview: "Consent documentation. 17 public, others protected...", pdfUrl: "/documents/survivor-consent.pdf" } },
    "8-s2-redact-remove": { id: "8-s2-redact-remove", type: "narrative", text: "You strip all victim content entirely. The release focuses purely on perpetrators - their names, their payments, their communications. The story is about what they did, not who they did it to. The survivors can add their voices later, if they choose.", nextNode: "8-s3" },
    "8-s2-redact-advocacy": { id: "8-s2-redact-advocacy", type: "narrative", text: "A survivor advocacy organization handles the sensitive material. Trained counselors contact each person. Legal experts ensure privacy protections. The release is handled with care - exposing evil without causing more harm.", nextNode: "8-s3" },
    "8-s2-summary": {
      id: "8-s2-summary",
      type: "choice",
      text: "The full files are overwhelming - thousands of documents, hundreds of hours of material. You create a summary: key names, key evidence, key connections. Something a journalist can report, a citizen can understand, a prosecutor can use.",
      question: "What do you emphasize in the summary?",
      timerSeconds: 20,
      choices: [
        { id: 'a', text: "The famous names - celebrities and politicians", nextNode: "8-s2-summary-famous", consequence: "Headlines..." },
        { id: 'b', text: "The system - how it operated for decades", nextNode: "8-s2-summary-system", consequence: "The machine..." },
        { id: 'c', text: "The cover-up - who protected them", nextNode: "8-s2-summary-coverup", consequence: "The complicity..." },
        { id: 'd', text: "The scale - how many victims, how much money", nextNode: "8-s2-summary-scale", consequence: "The magnitude..." },
      ],
    },
    "8-s2-summary-famous": { id: "8-s2-summary-famous", type: "narrative", text: "The names people will recognize. A former president's advisor. A beloved actor. A tech billionaire. A talk show host. A sports legend. A royal family member. Names that will dominate headlines and force people to pay attention.", nextNode: "8-s3", document: { title: "KEY_NAMES.pdf", preview: "High-profile clients identified. Public figures exposed...", pdfUrl: "/documents/key-names.pdf" } },
    "8-s2-summary-system": { id: "8-s2-summary-system", type: "narrative", text: "How it worked. Recruitment. Transportation. Payment systems. Blackmail. Protection. A machine designed to exploit humans, perfected over decades. Not a scandal - a system. Not bad actors - an institution.", nextNode: "8-s3" },
    "8-s2-summary-coverup": { id: "8-s2-summary-coverup", type: "narrative", text: "The prosecutors who declined cases. The judges who sealed records. The politicians who blocked legislation. The journalists who killed stories. Everyone who knew, or should have known, and chose silence. The guilty - and the complicit.", nextNode: "8-s3" },
    "8-s2-summary-scale": { id: "8-s2-summary-scale", type: "narrative", text: "247 clients. 400+ confirmed victims. $890 million in documented payments. Thirty years of operation. Properties on four continents. A conspiracy larger than any single country, longer than most careers, more profitable than many corporations.", nextNode: "8-s3", document: { title: "SCALE_SUMMARY.pdf", preview: "Complete scope documented. Unprecedented scale...", pdfUrl: "/documents/scale-summary.pdf" } },
    "8-s2-distribute": {
      id: "8-s2-distribute",
      type: "choice",
      text: "Once released, the files can't be unreleased. But they can be suppressed, deleted, discredited. You need distribution channels they can't shut down. Multiple platforms. Multiple countries. Redundancy that survives any takedown attempt.",
      question: "How do you ensure the files survive?",
      timerSeconds: 20,
      choices: [
        { id: 'a', text: "Upload to multiple news organizations simultaneously", nextNode: "8-s2-distribute-news", consequence: "Media saturation..." },
        { id: 'b', text: "Post to decentralized platforms and blockchain", nextNode: "8-s2-distribute-blockchain", consequence: "Permanent record..." },
        { id: 'c', text: "Share with international partners", nextNode: "8-s2-distribute-international", consequence: "Beyond US jurisdiction..." },
        { id: 'd', text: "All of the above", nextNode: "8-s2-distribute-all", consequence: "Unstoppable..." },
      ],
    },
    "8-s2-distribute-news": { id: "8-s2-distribute-news", type: "narrative", text: "The New York Times. Washington Post. The Guardian. Le Monde. Der Spiegel. Every major outlet receives the files simultaneously. They can't pressure one without the others publishing. Competition ensures coverage.", nextNode: "8-s3" },
    "8-s2-distribute-blockchain": { id: "8-s2-distribute-blockchain", type: "narrative", text: "The files go on IPFS. The hash goes on multiple blockchains. The data becomes permanent - distributed across thousands of computers worldwide. No government, no corporation, no billionaire can delete what exists everywhere and nowhere.", nextNode: "8-s3", document: { title: "BLOCKCHAIN_RECORD.pdf", preview: "Permanent distribution established. Hash verified...", pdfUrl: "/documents/blockchain-record.pdf" } },
    "8-s2-distribute-international": { id: "8-s2-distribute-international", type: "narrative", text: "News organizations in countries the US can't pressure. Servers in jurisdictions that protect whistleblowers. International human rights organizations ready to archive and share. The truth belongs to the world now, not any one nation.", nextNode: "8-s3" },
    "8-s2-distribute-all": { id: "8-s2-distribute-all", type: "narrative", text: "Maximum redundancy. Maximum reach. The files exist in newsrooms, on blockchains, in archives across the globe. They can silence you. They can imprison you. They can discredit you. But they cannot unrelease what's already everywhere.", nextNode: "8-s3" },

    // ========== STAGE 3: THE CONFRONTATION ==========
    "8-s3": {
      id: "8-s3",
      type: "choice",
      text: "The night before the release. You receive a visitor at your safehouse. Lady Victoria Ashworth - The Crown herself. She's elegant, composed, radiating old money and older power. 'I know what you're planning,' she says. 'I'm here to offer you an alternative.'",
      question: "STAGE 3/5 — How do you respond to The Crown?",
      timerSeconds: 20,
      choices: [
        { id: 'a', text: "Hear her out", nextNode: "8-s3-listen", consequence: "Know what she's offering..." },
        { id: 'b', text: "Refuse to engage", nextNode: "8-s3-refuse", consequence: "Nothing she says matters..." },
        { id: 'c', text: "Record the conversation", nextNode: "8-s3-record", consequence: "More evidence..." },
        { id: 'd', text: "Ask her why she did it", nextNode: "8-s3-why", consequence: "Understand the monster..." },
      ],
    },
    "8-s3-listen": {
      id: "8-s3-listen",
      type: "choice",
      text: "'$50 million. A new identity in any country you choose. Complete immunity from any consequences. All you have to do is destroy the files.' She smiles like she's offering a gift. 'You've suffered enough. Take the money. Live your life. Let this end.'",
      question: "What do you say?",
      timerSeconds: 20,
      choices: [
        { id: 'a', text: "No amount of money can buy my silence", nextNode: "8-s3-listen-no", consequence: "I can't be bought..." },
        { id: 'b', text: "You can't buy justice", nextNode: "8-s3-listen-justice", consequence: "Some things aren't for sale..." },
        { id: 'c', text: "Is that what you told your victims?", nextNode: "8-s3-listen-victims", consequence: "Turn it back on her..." },
        { id: 'd', text: "Your money comes from human trafficking", nextNode: "8-s3-listen-blood", consequence: "Blood money..." },
      ],
    },
    "8-s3-listen-no": { id: "8-s3-listen-no", type: "narrative", text: "'I was sold. My body was a product. Now you want to buy my silence?' You stand. 'Everything I am was shaped by what you did. And everything I do from now on will be about making sure it never happens again. Keep your money.'", nextNode: "8-s4" },
    "8-s3-listen-justice": { id: "8-s3-listen-justice", type: "narrative", text: "'Justice isn't for sale. The truth isn't for sale. The lives you destroyed aren't for sale.' You look her in the eyes - this woman who controlled an empire of suffering. 'And neither am I.'", nextNode: "8-s4" },
    "8-s3-listen-victims": { id: "8-s3-listen-victims", type: "narrative", text: "'Is that what you told the girls on the island? 'Take the money, live your life'?' Her smile wavers. 'How many did you offer this deal? How many had no choice?' She doesn't answer. She doesn't need to. You both know.", nextNode: "8-s4" },
    "8-s3-listen-blood": { id: "8-s3-listen-blood", type: "narrative", text: "'That $50 million - where did it come from? Human trafficking. Rape. Exploitation. You're offering me blood money.' You step closer. 'I'd rather be poor and free than rich and silent. Get out.'", nextNode: "8-s4", document: { title: "BRIBE_ATTEMPT.pdf", preview: "Attempted bribery documented. $50M offered...", pdfUrl: "/documents/bribe-attempt.pdf" } },
    "8-s3-refuse": {
      id: "8-s3-refuse",
      type: "choice",
      text: "'I have nothing to say to you.' You turn away. 'Wait,' she says, voice harder now. 'You don't understand what you're doing. The people on that list - they won't simply accept exposure. They'll fight back. They'll destroy you.'",
      question: "How do you respond to the threat?",
      timerSeconds: 20,
      choices: [
        { id: 'a', text: "They already tried to destroy me", nextNode: "8-s3-refuse-tried", consequence: "I survived..." },
        { id: 'b', text: "Let them try", nextNode: "8-s3-refuse-let", consequence: "I'm not afraid..." },
        { id: 'c', text: "The truth is already out of my hands", nextNode: "8-s3-refuse-out", consequence: "Too late to stop it..." },
        { id: 'd', text: "Your threats don't work anymore", nextNode: "8-s3-refuse-threats", consequence: "I'm beyond fear..." },
      ],
    },
    "8-s3-refuse-tried": { id: "8-s3-refuse-tried", type: "narrative", text: "'They held me captive. Sold me. Broke me. And I'm still here.' You finally turn to face her. 'I survived your island. I survived your trial. I survived your silence. Whatever comes next - I'll survive that too.'", nextNode: "8-s4" },
    "8-s3-refuse-let": { id: "8-s3-refuse-let", type: "narrative", text: "'Let them come. Let them sue me, threaten me, try to discredit me. Every attack proves I'm telling the truth. Every attempt to silence me proves why these files matter.' You smile. 'They're scared. They should be.'", nextNode: "8-s4" },
    "8-s3-refuse-out": { id: "8-s3-refuse-out", type: "narrative", text: "'Even if you killed me right now, the files release tomorrow. Multiple copies. Multiple locations. Multiple people ready to publish. You can't stop it. No one can.' For the first time, fear flickers in her eyes.", nextNode: "8-s4" },
    "8-s3-refuse-threats": { id: "8-s3-refuse-threats", type: "narrative", text: "'I stopped being afraid when I jumped off that island into black water. I stopped being afraid when I testified against a senator. Your threats mean nothing to someone who's already lost everything - and rebuilt anyway.'", nextNode: "8-s4", document: { title: "THREAT_RECORD.pdf", preview: "Intimidation attempt documented...", pdfUrl: "/documents/threat-record.pdf" } },
    "8-s3-record": {
      id: "8-s3-record",
      type: "choice",
      text: "Your phone is already recording. Everything she says, documented. If she offers a bribe, that's a crime. If she makes threats, that's a crime. Whatever happens in this room becomes part of the evidence.",
      question: "What do you try to get her to admit?",
      timerSeconds: 20,
      choices: [
        { id: 'a', text: "Her role in the organization", nextNode: "8-s3-record-role", consequence: "Confession..." },
        { id: 'b', text: "Why she was protected", nextNode: "8-s3-record-protected", consequence: "The connections..." },
        { id: 'c', text: "What she's afraid of", nextNode: "8-s3-record-afraid", consequence: "Her weakness..." },
        { id: 'd', text: "How many victims there really were", nextNode: "8-s3-record-victims", consequence: "The full scope..." },
      ],
    },
    "8-s3-record-role": { id: "8-s3-record-role", type: "narrative", text: "'So you're The Crown. The leader. The one who built all of this.' She laughs. 'Built? My dear, I inherited it. My family has been providing... services... for powerful people for over a century. I merely modernized the operation.' Confession. Recorded.", nextNode: "8-s4", document: { title: "CROWN_CONFESSION.pdf", preview: "Leadership role admitted. Generational conspiracy confirmed...", pdfUrl: "/documents/crown-confession.pdf" } },
    "8-s3-record-protected": { id: "8-s3-record-protected", type: "narrative", text: "'Why wasn't I charged? Because half your government owes me favors. Because I have photographs that would end presidencies. Because destroying me would mean destroying the very institutions that protect your democracy.' She's proud of it. Recorded.", nextNode: "8-s4" },
    "8-s3-record-afraid": { id: "8-s3-record-afraid", type: "narrative", text: "'Afraid? I'm not afraid of prison. I'm afraid of what happens when the wrong people are exposed. When alliances crumble. When nuclear powers lose stable leadership because their leaders are busy defending themselves.' Her fear isn't justice - it's chaos.", nextNode: "8-s4" },
    "8-s3-record-victims": { id: "8-s3-record-victims", type: "narrative", text: "'Your files show 400 victims? Try thousands. Across decades. Across continents. The island was one location. There were others. Some still operating.' She says it casually. Thousands of victims. Recorded.", nextNode: "8-s4", document: { title: "SCOPE_ADMISSION.pdf", preview: "Scale confirmed. Thousands of victims. Ongoing operations...", pdfUrl: "/documents/scope-admission.pdf" } },
    "8-s3-why": {
      id: "8-s3-why",
      type: "choice",
      text: "'Why?' The question escapes before you can stop it. 'You have everything. Money. Power. Respect. Why do this?' She considers the question seriously, as if no one has ever asked.",
      question: "How does she justify it?",
      timerSeconds: 20,
      choices: [
        { id: 'a', text: "'Because I could'", nextNode: "8-s3-why-could", consequence: "Pure power..." },
        { id: 'b', text: "'Because they're not real people to me'", nextNode: "8-s3-why-people", consequence: "Dehumanization..." },
        { id: 'c', text: "'Because the world runs on exploitation'", nextNode: "8-s3-why-world", consequence: "System..." },
        { id: 'd', text: "'Because power requires leverage'", nextNode: "8-s3-why-leverage", consequence: "Control..." },
      ],
    },
    "8-s3-why-could": { id: "8-s3-why-could", type: "narrative", text: "'Because I could. Because no one stopped me. Because when you have enough money and enough connections, the rules don't apply.' She shrugs. 'You think I'm a monster. I think I'm honest about how the world works.'", nextNode: "8-s4" },
    "8-s3-why-people": { id: "8-s3-why-people", type: "narrative", text: "'You were products. Inventory. I know that sounds cruel, but it's simply how I was raised to see certain... categories of people.' Her casual dehumanization is more chilling than rage would be.", nextNode: "8-s4" },
    "8-s3-why-world": { id: "8-s3-why-world", type: "narrative", text: "'Everything you consume is built on exploitation. Your clothes, your phone, your food - all produced by people with no power, for people with all of it. I simply... removed the middlemen.' She believes it. That's the worst part.", nextNode: "8-s4" },
    "8-s3-why-leverage": { id: "8-s3-why-leverage", type: "narrative", text: "'Power isn't money. Power is leverage. Compromising material on the right people opens any door, stops any investigation, changes any policy. The island was a leverage factory.' She smiles. 'Until you.'", nextNode: "8-s4", document: { title: "LEVERAGE_SYSTEM.pdf", preview: "Blackmail operation explained. Control mechanism documented...", pdfUrl: "/documents/leverage-system.pdf" } },

    // ========== STAGE 4: THE RELEASE ==========
    "8-s4": {
      id: "8-s4",
      type: "choice",
      text: "Dawn. The files are ready. The distribution networks are primed. Journalists are standing by. Other survivors are prepared to speak. In a few hours, the world changes forever. You sit alone, finger hovering over the button that will release everything.",
      question: "STAGE 4/5 — Before you release, what do you think about?",
      timerSeconds: 20,
      choices: [
        { id: 'a', text: "The victims who never got justice", nextNode: "8-s4-victims", consequence: "For them..." },
        { id: 'b', text: "The girl you were before the island", nextNode: "8-s4-before", consequence: "Who you were..." },
        { id: 'c', text: "The life you've built since", nextNode: "8-s4-since", consequence: "Who you've become..." },
        { id: 'd', text: "The future you're about to change", nextNode: "8-s4-future", consequence: "What comes next..." },
      ],
    },
    "8-s4-victims": {
      id: "8-s4-victims",
      type: "choice",
      text: "You think about them. The ones who didn't escape. The ones who died in captivity. The ones who survived but never recovered. The ones whose names you'll never know. This is for them. This was always for them.",
      question: "What do you want for them?",
      timerSeconds: 20,
      choices: [
        { id: 'a', text: "Recognition - their suffering acknowledged", nextNode: "8-s4-victims-recognition", consequence: "They existed..." },
        { id: 'b', text: "Justice - their abusers exposed", nextNode: "8-s4-victims-justice", consequence: "Consequences..." },
        { id: 'c', text: "Prevention - this never happens again", nextNode: "8-s4-victims-prevention", consequence: "Protect the future..." },
        { id: 'd', text: "All of it - everything they deserve", nextNode: "8-s4-victims-all", consequence: "Everything..." },
      ],
    },
    "8-s4-victims-recognition": { id: "8-s4-victims-recognition", type: "narrative", text: "They weren't statistics. They were people. Daughters. Sisters. Friends. Humans with hopes and dreams that were stolen from them. The world needs to know they existed, they mattered, they suffered. Their stories deserve to be told.", nextNode: "8-s5" },
    "8-s4-victims-justice": { id: "8-s4-victims-justice", type: "narrative", text: "The men who hurt them - the men who paid to hurt them - walked free for decades. Smiled for cameras. Received awards. Shaped policy. That ends today. Every name on that list will be known. Every monster will be exposed.", nextNode: "8-s5" },
    "8-s4-victims-prevention": { id: "8-s4-victims-prevention", type: "narrative", text: "This can't happen again. Not like this. Not on this scale. The systems that protected predators - the silence, the complicity, the willful ignorance - all of it exposed. Future victims protected by the truth.", nextNode: "8-s5", document: { title: "PREVENTION_IMPACT.pdf", preview: "Systemic changes anticipated. Protection improvements...", pdfUrl: "/documents/prevention-impact.pdf" } },
    "8-s4-victims-all": { id: "8-s4-victims-all", type: "narrative", text: "Recognition. Justice. Prevention. They deserve all of it. And today, you're going to give them everything you can. It's not enough - it's never enough - but it's something. It's everything you have.", nextNode: "8-s5" },
    "8-s4-before": {
      id: "8-s4-before",
      type: "choice",
      text: "You remember her. The girl from before. College student. Dreams of a normal life. A family, a career, a future that looked like everyone else's. That girl went to a charity gala and never came home. What would she think of who you've become?",
      question: "What would the old you think?",
      timerSeconds: 20,
      choices: [
        { id: 'a', text: "She'd be proud", nextNode: "8-s4-before-proud", consequence: "You fought..." },
        { id: 'b', text: "She'd be sad for what was lost", nextNode: "8-s4-before-sad", consequence: "The cost..." },
        { id: 'c', text: "She'd barely recognize you", nextNode: "8-s4-before-recognize", consequence: "You've changed..." },
        { id: 'd', text: "She'd understand it had to be done", nextNode: "8-s4-before-understand", consequence: "Necessary..." },
      ],
    },
    "8-s4-before-proud": { id: "8-s4-before-proud", type: "narrative", text: "That scared girl who jumped into black water - she'd be amazed at who you became. A survivor. A fighter. Someone who took the worst experience imaginable and turned it into something meaningful. She'd be proud. You let yourself feel that.", nextNode: "8-s5" },
    "8-s4-before-sad": { id: "8-s4-before-sad", type: "narrative", text: "The normal life you wanted is gone forever. The innocence that was stolen can't be returned. You grieve for that girl sometimes - her simple dreams, her easy trust. But grief isn't regret. You did what you had to do.", nextNode: "8-s5" },
    "8-s4-before-recognize": { id: "8-s4-before-recognize", type: "narrative", text: "You've changed so much. Harder. Stronger. Sadder. The girl who believed the world was basically fair is gone. In her place: someone who knows exactly how dark it can get - and chooses to fight the darkness anyway.", nextNode: "8-s5" },
    "8-s4-before-understand": { id: "8-s4-before-understand", type: "narrative", text: "She was naive, but she wasn't weak. Even then, she would have understood: some things are worth fighting for, no matter the cost. You're honoring her - the girl you were - by being the woman you've become.", nextNode: "8-s5", document: { title: "SURVIVOR_JOURNEY.pdf", preview: "Personal statement prepared. Transformation documented...", pdfUrl: "/documents/survivor-journey.pdf" } },
    "8-s4-since": {
      id: "8-s4-since",
      type: "choice",
      text: "The life you've built. New name. New city. New friends who don't know your past. Moments of genuine happiness between the nightmares. Therapy that helped. Work that matters. A future that once seemed impossible.",
      question: "What has recovery taught you?",
      timerSeconds: 20,
      choices: [
        { id: 'a', text: "Survival is its own victory", nextNode: "8-s4-since-survival", consequence: "You're still here..." },
        { id: 'b', text: "Healing is possible, even if incomplete", nextNode: "8-s4-since-healing", consequence: "Progress matters..." },
        { id: 'c', text: "Purpose gives strength", nextNode: "8-s4-since-purpose", consequence: "Meaning helps..." },
        { id: 'd', text: "You're more than what was done to you", nextNode: "8-s4-since-more", consequence: "Identity reclaimed..." },
      ],
    },
    "8-s4-since-survival": { id: "8-s4-since-survival", type: "narrative", text: "Every day you wake up is a victory they didn't want you to have. Every moment of happiness is something you reclaimed. Survival itself is resistance. And you've been resisting for years.", nextNode: "8-s5" },
    "8-s4-since-healing": { id: "8-s4-since-healing", type: "narrative", text: "The scars don't disappear. The nightmares still come. But they're less frequent. Less powerful. You've learned to live around them, through them, despite them. Healing isn't a destination - it's a direction.", nextNode: "8-s5" },
    "8-s4-since-purpose": { id: "8-s4-since-purpose", type: "narrative", text: "Having something to fight for helps. It transforms pain into fuel, trauma into motivation. This mission - exposing the truth - has given meaning to suffering that once felt meaningless.", nextNode: "8-s5" },
    "8-s4-since-more": { id: "8-s4-since-more", type: "narrative", text: "They tried to reduce you to a product. A victim. A number on a ledger. But you're a person. A survivor. A fighter. Someone who took back her own story and refused to let them write the ending.", nextNode: "8-s5", document: { title: "IDENTITY_RECLAIMED.pdf", preview: "Survivor statement on recovery and purpose...", pdfUrl: "/documents/identity-reclaimed.pdf" } },
    "8-s4-future": {
      id: "8-s4-future",
      type: "choice",
      text: "After today, nothing will be the same. Governments will face scrutiny. Institutions will be questioned. Powerful people will fall. And you - you'll be known. The anonymous survivor becomes a public figure. A target. A symbol.",
      question: "What do you hope for the future?",
      timerSeconds: 20,
      choices: [
        { id: 'a', text: "Systemic change that prevents this", nextNode: "8-s4-future-systemic", consequence: "Change the system..." },
        { id: 'b', text: "Justice for every victim, named and unnamed", nextNode: "8-s4-future-justice", consequence: "Complete accountability..." },
        { id: 'c', text: "A world that believes survivors", nextNode: "8-s4-future-belief", consequence: "Cultural shift..." },
        { id: 'd', text: "The end of untouchable predators", nextNode: "8-s4-future-end", consequence: "No more protection..." },
      ],
    },
    "8-s4-future-systemic": { id: "8-s4-future-systemic", type: "narrative", text: "New laws. Better enforcement. Victim protections that actually protect. The systems that failed have to change - not just the individuals. After today, ignoring this problem becomes politically impossible.", nextNode: "8-s5" },
    "8-s4-future-justice": { id: "8-s4-future-justice", type: "narrative", text: "Prosecutions in every country. Civil suits that bankrupt perpetrators. Asset seizures that fund victim recovery. Justice delayed too long, but justice finally delivered.", nextNode: "8-s5" },
    "8-s4-future-belief": { id: "8-s4-future-belief", type: "narrative", text: "A world where victims are believed first, not last. Where coming forward doesn't mean being destroyed. Where 'he's too powerful' is no longer an excuse to stay silent. That's the world you're trying to build.", nextNode: "8-s5", document: { title: "CULTURAL_CHANGE.pdf", preview: "Anticipated social impact. Belief systems shifting...", pdfUrl: "/documents/cultural-change.pdf" } },
    "8-s4-future-end": { id: "8-s4-future-end", type: "narrative", text: "No more untouchable elites. No more 'too big to prosecute.' No more quiet settlements and sealed records. Power should not be a shield for predators. After today, everyone knows: the rules apply to everyone.", nextNode: "8-s5" },

    // ========== STAGE 5: THE TRUTH ==========
    "8-s5": {
      id: "8-s5",
      type: "choice",
      text: "You press the button. The files begin to upload. Within minutes, journalists receive the documents. Within hours, the first stories break. Within days, the world will never be the same. You watch the news coverage begin - your truth, finally told. The names scroll across screens worldwide. The powerful scramble to respond. The victims see their abusers exposed.",
      question: "STAGE 5/5 — As the world reacts, what do you do?",
      timerSeconds: 20,
      choices: [
        { id: 'a', text: "Give a public statement", nextNode: "8-s5-statement", consequence: "Speak for yourself..." },
        { id: 'b', text: "Watch in silence as justice unfolds", nextNode: "8-s5-watch", consequence: "Let the evidence speak..." },
        { id: 'c', text: "Reach out to other survivors", nextNode: "8-s5-survivors", consequence: "Support each other..." },
        { id: 'd', text: "Plan what comes next", nextNode: "8-s5-next", consequence: "The work continues..." },
      ],
    },
    "8-s5-statement": { id: "8-s5-statement", type: "narrative", text: "You step in front of cameras for the first time. Millions watch. 'My name is...' You use your real name. 'I was kidnapped, trafficked, and sold to powerful men who believed they were untouchable. Today, I'm proving them wrong. These files contain the truth - names, dates, evidence. The world deserves to know. The victims deserve to be heard. And the guilty deserve to face consequences.' You are no longer a victim. You are a witness. You are the truth.", nextNode: "8-complete", document: { title: "PUBLIC_STATEMENT.pdf", preview: "Full testimony delivered. Global audience reached...", pdfUrl: "/documents/public-statement.pdf" } },
    "8-s5-watch": { id: "8-s5-watch", type: "narrative", text: "You don't need to say anything. The files speak for themselves. You watch as names trend worldwide. As lawyers issue statements. As politicians resign. As arrests begin in multiple countries. The evidence is undeniable. The truth is unstoppable. You've done your part. Now the world does theirs.", nextNode: "8-complete" },
    "8-s5-survivors": { id: "8-s5-survivors", type: "narrative", text: "You reach out to the others. Survivors who've been waiting for this moment. Some are crying. Some are laughing. Some are both. 'We did it,' one says. 'They can't ignore us anymore.' You hold a virtual vigil for the ones who didn't make it - the victims who died before seeing justice. You carry them with you. Always.", nextNode: "8-complete", document: { title: "SURVIVOR_NETWORK.pdf", preview: "Support network activated. Collective healing begins...", pdfUrl: "/documents/survivor-network.pdf" } },
    "8-s5-next": { id: "8-s5-next", type: "narrative", text: "This isn't the end. It's a beginning. The files exposed one network, but others exist. Other victims need help. Other predators need to be stopped. You've built something - credibility, connections, courage. You'll use it. The work continues. It always continues.", nextNode: "8-complete" },

    // ========== CHAPTER 8 / GAME COMPLETE ==========
    "8-complete": {
      id: "8-complete",
      type: "chapter-end",
      text: "THE FILES ARE PUBLIC.\n\n247 names exposed to the world. Within 72 hours, investigations open in fourteen countries. Resignations cascade through governments and corporations. Assets are frozen. Passports are revoked. The powerful who thought they were untouchable discover they were wrong.\n\nLady Victoria Ashworth - The Crown - is arrested by Interpol attempting to flee to a non-extradition country. She will face trial alongside the others.\n\nThe survivors - all of you - are believed. Your testimonies corroborate the documents. Your courage inspires others to come forward. Hundreds more victims find their voices.\n\nIt's not perfect justice. Some will escape. Some will receive light sentences. Some will die before facing trial. The system that protected them for decades won't transform overnight.\n\nBut everything has changed.\n\nYou changed it.\n\nYou escaped the island. You survived the silence. You exposed the truth. And now, finally, the world knows what you know:\n\nNo one is untouchable.\nNo secret is forever.\nThe truth always finds a way.\n\n— THE END —\n\nThank you for playing SPECIMEN PROTOCOL.",
      chapterComplete: {
        chapter: 8,
        nextChapter: 9,
        summary: "You did it. The files are public. The powerful are exposed. The truth is known. From captive to survivor to the one who brought them all down - your journey is complete. The world will never be the same."
      },
    },
  },
};