import { BranchingChapter } from '../types';

/**
 * CHAPTER 4: THE INVESTIGATION - 5 Stages, full branching
 * The FBI builds their case. You're the star witness. But powerful people fight back.
 */
export const CHAPTER_4: BranchingChapter = {
  id: 4,
  title: "CHAPTER 4",
  subtitle: "The Investigation",
  startNode: "4-s1",
  nodes: {
    // ========== STAGE 1: FBI SAFEHOUSE ==========
    "4-s1": {
      id: "4-s1",
      type: "choice",
      text: "Two weeks in an FBI safehouse. Beige walls. Armed agents outside. You've given your testimony five times. Today, Lead Agent Chen arrives with news: 'We're ready to move on the island. But we need more. Names, account numbers, anything you remember.' She slides photos across the table - faces from the party.",
      question: "STAGE 1/5 — How do you help the investigation?",
      timerSeconds: 20,
      choices: [
        { id: 'a', text: "Study the photos carefully", nextNode: "4-s1-photos", consequence: "Identify everyone you can..." },
        { id: 'b', text: "Offer to review the USB evidence", nextNode: "4-s1-usb", consequence: "Help analyze the footage..." },
        { id: 'c', text: "Suggest they raid immediately", nextNode: "4-s1-raid", consequence: "Time is critical..." },
        { id: 'd', text: "Demand to know their full plan first", nextNode: "4-s1-plan", consequence: "Trust but verify..." },
      ],
    },
    "4-s1-photos": {
      id: "4-s1-photos",
      type: "choice",
      text: "You spread the photos across the table. Some faces you recognize - the senator, the tech CEO. Others are blurry, half-hidden. One photo catches your eye: a man in the background of every shot. Never the center, always watching.",
      question: "You notice something. What do you focus on?",
      timerSeconds: 20,
      choices: [
        { id: 'a', text: "Point out the watching man", nextNode: "4-s1-photos-watcher", consequence: "Who is he?" },
        { id: 'b', text: "Identify all the clients you recognize", nextNode: "4-s1-photos-clients", consequence: "Name them all..." },
        { id: 'c', text: "Look for staff members", nextNode: "4-s1-photos-staff", consequence: "Guards might flip..." },
        { id: 'd', text: "Check for anyone you saw hurting victims", nextNode: "4-s1-photos-death", consequence: "The worst ones..." },
      ],
    },
    "4-s1-photos-death": { id: "4-s1-photos-death", type: "death", text: "You point to a face. 'This one. I saw him with Sofia before I rescued her.' Agent Chen's face goes pale. 'That's Deputy Director Morrison. FBI.' She reaches for her phone - but the door bursts open. Men in tactical gear. 'We'll take it from here.' You've identified the mole - too late.", deathMessage: "The corruption runs deeper than you knew." },
    "4-s1-photos-watcher": { id: "4-s1-photos-watcher", type: "narrative", text: "'This man. Every photo.' Agent Chen's eyes narrow. She runs facial recognition. 'Victor Marsh. No criminal record, but... he's connected to offshore accounts in Cyprus.' She looks at you. 'You just found their money man.'", nextNode: "4-s2", document: { title: "MARSH_PROFILE.pdf", preview: "Victor Marsh. Financial coordinator. Cyprus connections...", pdfUrl: "/documents/marsh.pdf" } },
    "4-s1-photos-clients": { id: "4-s1-photos-clients", type: "narrative", text: "Senator Morrison. CEO Chen. Ambassador Volkov. Judge Patterson. You name twelve faces. Agent Chen records everything. 'This is enough for warrants. Multiple warrants.' Her hands are shaking - this is the biggest case of her career.", nextNode: "4-s2" },
    "4-s1-photos-staff": { id: "4-s1-photos-staff", type: "narrative", text: "'These two guards - Torres and Wallace. They had doubts. I heard them talking.' Agent Chen nods. 'Potential cooperating witnesses. We approach them first, flip them before the raid.' Smart. Turn the guards against their bosses.", nextNode: "4-s2", document: { title: "GUARD_INTEL.pdf", preview: "Torres, Wallace identified. Potential informants...", pdfUrl: "/documents/guards.pdf" } },
    "4-s1-usb": {
      id: "4-s1-usb",
      type: "choice",
      text: "The tech team has been analyzing the USB drives. Terabytes of footage. They set you up at a workstation with a victim advocate beside you. 'Flag anyone you recognize. Any location. Any detail.' The screen fills with thumbnails - years of horror.",
      question: "The footage is overwhelming. How do you approach it?",
      timerSeconds: 20,
      choices: [
        { id: 'a', text: "Focus on identifying locations", nextNode: "4-s1-usb-locations", consequence: "Map the facility..." },
        { id: 'b', text: "Look for the highest-profile clients", nextNode: "4-s1-usb-clients", consequence: "Big fish..." },
        { id: 'c', text: "Search for other victims who might still be there", nextNode: "4-s1-usb-victims", consequence: "Save them..." },
        { id: 'd', text: "Try to find footage of yourself", nextNode: "4-s1-usb-death", consequence: "Know what they have..." },
      ],
    },
    "4-s1-usb-death": { id: "4-s1-usb-death", type: "death", text: "You search for your own files. There you are - being processed, drugged, prepared. You watch yourself being led to a room. The door closes. You can't stop watching. Hours pass. When the advocate finally pulls you away, something has broken inside. You can't testify. You can't even speak.", deathMessage: "Some footage should never be seen. You've traumatized yourself beyond recovery." },
    "4-s1-usb-locations": { id: "4-s1-usb-locations", type: "narrative", text: "You map every building. The main house. Guest cottages. The dome. Underground areas you never saw. 'There's a whole sublevel,' you tell them. 'Medical facility. Maybe holding cells.' Agent Chen calls in architectural analysts.", nextNode: "4-s2", document: { title: "FACILITY_MAP.pdf", preview: "Underground level confirmed. Medical wing. Holding cells...", pdfUrl: "/documents/facility.pdf" } },
    "4-s1-usb-clients": { id: "4-s1-usb-clients", type: "narrative", text: "You flag every face you recognize from the party. Some are caught in compromising positions - irrefutable evidence. 'Senator Morrison,' you say flatly, pausing on a frame. 'That's enough to end his career.' 'And start a prosecution,' Chen adds.", nextNode: "4-s2" },
    "4-s1-usb-victims": { id: "4-s1-usb-victims", type: "narrative", text: "You count faces. Cross-reference with dates. 'These twelve were there recently - within the last month.' You write down descriptions. Hair color. Approximate age. Distinguishing marks. 'If they're still alive, this helps us find them.'", nextNode: "4-s2" },
    "4-s1-raid": {
      id: "4-s1-raid",
      type: "choice",
      text: "'Every day we wait, people suffer.' Agent Chen sighs. 'We need to build an airtight case. These people have the best lawyers money can buy.' 'Then hit them before they can prepare,' you argue. She considers.",
      question: "You're pushing for immediate action. How do you convince her?",
      timerSeconds: 20,
      choices: [
        { id: 'a', text: "Appeal to saving current victims", nextNode: "4-s1-raid-victims", consequence: "Lives at stake..." },
        { id: 'b', text: "Warn that evidence might be destroyed", nextNode: "4-s1-raid-evidence", consequence: "They're covering tracks..." },
        { id: 'c', text: "Offer to testify immediately", nextNode: "4-s1-raid-testify", consequence: "Whatever it takes..." },
        { id: 'd', text: "Threaten to go to the media", nextNode: "4-s1-raid-death", consequence: "Force their hand..." },
      ],
    },
    "4-s1-raid-death": { id: "4-s1-raid-death", type: "death", text: "'If you won't act, I'll find a journalist who will.' Agent Chen's face hardens. 'That would compromise the entire investigation. Obstruction of justice.' She nods to another agent. 'For your protection, we're moving you to a more secure facility.' The 'secure facility' has bars on the windows. You've made yourself a prisoner.", deathMessage: "Threatening the FBI was a critical mistake." },
    "4-s1-raid-victims": { id: "4-s1-raid-victims", type: "narrative", text: "'There are girls there right now. Tonight. Being hurt.' Your voice breaks. Agent Chen looks away. When she looks back, her jaw is set. 'I'll push the timeline. 72 hours.' It's not immediate, but it's something.", nextNode: "4-s2" },
    "4-s1-raid-evidence": { id: "4-s1-raid-evidence", type: "narrative", text: "'They know I escaped. They're destroying evidence right now. Burning files. Moving victims.' Chen nods slowly. 'We've had the same concern. That's why we're planning a simultaneous raid - island and all known associate locations at once.'", nextNode: "4-s2", document: { title: "RAID_PLAN.pdf", preview: "Simultaneous operations planned. 6 locations...", pdfUrl: "/documents/raid.pdf" } },
    "4-s1-raid-testify": { id: "4-s1-raid-testify", type: "narrative", text: "'I'll do whatever you need. Grand jury. Depositions. Anything.' Chen looks at you with something like respect. 'Your testimony is already the cornerstone. But we need corroboration. Physical evidence. Other witnesses.' She pauses. 'We're getting there.'", nextNode: "4-s2" },
    "4-s1-plan": {
      id: "4-s1-plan",
      type: "choice",
      text: "'I need to know everything. Who's involved in the investigation. What the plan is. All of it.' Agent Chen raises an eyebrow. 'That's not how this works.' 'I'm the one who risked everything. I deserve to know.'",
      question: "You're demanding information. How do you justify it?",
      timerSeconds: 20,
      choices: [
        { id: 'a', text: "Point out you've already proven trustworthy", nextNode: "4-s1-plan-trust", consequence: "You've earned it..." },
        { id: 'b', text: "Explain you might remember more with context", nextNode: "4-s1-plan-context", consequence: "Help me help you..." },
        { id: 'c', text: "Say you're worried about leaks", nextNode: "4-s1-plan-leaks", consequence: "Who can we trust?" },
        { id: 'd', text: "Refuse to cooperate until they tell you", nextNode: "4-s1-plan-death", consequence: "No more until I know..." },
      ],
    },
    "4-s1-plan-death": { id: "4-s1-plan-death", type: "death", text: "'Then we're done here.' You cross your arms. Chen stares at you for a long moment, then stands. 'Your choice.' Days pass. No updates. No visitors. Then news: the island was tipped off. Everyone evacuated. Evidence destroyed. Your stubbornness gave them time.", deathMessage: "Your refusal to cooperate let the criminals escape." },
    "4-s1-plan-trust": { id: "4-s1-plan-trust", type: "narrative", text: "'I escaped. I brought evidence. I've told you everything.' Chen considers. 'Fair point.' She pulls out a tablet. 'Here's what we know. Here's who's involved. Here's the timeline.' Finally, you're a partner, not just a witness.", nextNode: "4-s2" },
    "4-s1-plan-context": { id: "4-s1-plan-context", type: "narrative", text: "'If I know what you're looking for, I might remember details I missed.' Chen nods slowly. 'That's... actually good logic.' She starts briefing you on the investigation structure. Names trigger memories. Connections form.", nextNode: "4-s2", document: { title: "INVESTIGATION_BRIEF.pdf", preview: "Full case structure. Targets. Timeline...", pdfUrl: "/documents/brief.pdf" } },
    "4-s1-plan-leaks": { id: "4-s1-plan-leaks", type: "narrative", text: "'These people have connections everywhere. How do I know someone in the FBI isn't on their payroll?' Chen's face flickers - you've touched a nerve. 'We've... had concerns. That's why this team is small. Vetted.' She's worried too. That's both reassuring and terrifying.", nextNode: "4-s2" },

    // ========== STAGE 2: THE LEAK ==========
    "4-s2": {
      id: "4-s2",
      type: "choice",
      text: "Three days later. You wake to shouting outside your door. Agent Chen bursts in. 'We have a problem. Someone leaked your location to the press.' She shows you her phone - a news van parked outside. 'We need to move you. Now.'",
      question: "STAGE 2/5 — Your location is compromised. What do you do?",
      timerSeconds: 20,
      choices: [
        { id: 'a', text: "Go with the FBI immediately", nextNode: "4-s2-fbi", consequence: "Trust them..." },
        { id: 'b', text: "Demand to know how this happened", nextNode: "4-s2-demand", consequence: "Someone talked..." },
        { id: 'c', text: "Ask to call someone you trust", nextNode: "4-s2-call", consequence: "Outside contact..." },
        { id: 'd', text: "Refuse to move until the leak is found", nextNode: "4-s2-death", consequence: "Not until I know..." },
      ],
    },
    "4-s2-death": { id: "4-s2-death", type: "death", text: "'I'm not going anywhere until you figure out who leaked.' Chen's phone buzzes. Her face goes white. 'They're not just press out there.' The window shatters. Flashbang. Armed men pour in. Not FBI. Private contractors. Someone paid very well to silence you.", deathMessage: "You stayed too long. They found you." },
    "4-s2-fbi": {
      id: "4-s2-fbi",
      type: "choice",
      text: "Two SUVs wait in the garage. Agents surround you. Chen leads you to the second vehicle. 'We're splitting up. Decoy in car one.' As you pull out, you see the news vans following the decoy. But in the side mirror - a black sedan that peels off toward you.",
      question: "You're being followed. What do you tell the driver?",
      timerSeconds: 20,
      choices: [
        { id: 'a', text: "Point out the tail", nextNode: "4-s2-fbi-tail", consequence: "We have company..." },
        { id: 'b', text: "Stay quiet and watch", nextNode: "4-s2-fbi-watch", consequence: "Gather info..." },
        { id: 'c', text: "Suggest a route change", nextNode: "4-s2-fbi-route", consequence: "Lose them..." },
        { id: 'd', text: "Grab for the agent's gun", nextNode: "4-s2-fbi-death", consequence: "Protect yourself..." },
      ],
    },
    "4-s2-fbi-death": { id: "4-s2-fbi-death", type: "death", text: "You lunge for the holster. The agent reacts on instinct - elbow to your face. You're unconscious before you hit the seat. When you wake, you're in handcuffs. 'Assaulting a federal agent. You just made our job much harder.' Your own paranoia has made you a criminal.", deathMessage: "Attacking your protectors was insane." },
    "4-s2-fbi-tail": { id: "4-s2-fbi-tail", type: "narrative", text: "'Black sedan, three cars back.' The driver checks the mirror. 'Good eye.' He radios ahead. At the next intersection, two unmarked cars box the sedan in. You watch in the mirror as agents swarm it. 'Professional surveillance team,' Chen reports later. 'We're running IDs now.'", nextNode: "4-s3", document: { title: "SURVEILLANCE_TEAM.pdf", preview: "Private contractors identified. Linked to offshore security firm...", pdfUrl: "/documents/surveillance.pdf" } },
    "4-s2-fbi-watch": { id: "4-s2-fbi-watch", type: "narrative", text: "You memorize the car. The license plate. The driver's silhouette. When you finally arrive at the new safehouse, you give Chen everything. 'You should've said something sooner,' she scolds. But she's impressed.", nextNode: "4-s3" },
    "4-s2-fbi-route": { id: "4-s2-fbi-route", type: "narrative", text: "'Turn left here. Then right.' The driver hesitates. 'Just do it.' You guide them through back streets you've studied on maps during sleepless nights. The tail loses you in a parking garage. 'How did you know this area?' Chen asks. 'I've been preparing,' you say.", nextNode: "4-s3" },
    "4-s2-demand": {
      id: "4-s2-demand",
      type: "choice",
      text: "'Someone on your team talked.' Chen's jaw tightens. 'We're looking into it.' 'Looking isn't good enough. Who knew this address?' She pulls out a list. Six names. All agents on the case.",
      question: "You're hunting for a mole. How do you narrow it down?",
      timerSeconds: 20,
      choices: [
        { id: 'a', text: "Ask about their backgrounds", nextNode: "4-s2-demand-backgrounds", consequence: "Who has connections..." },
        { id: 'b', text: "Look at who had access when", nextNode: "4-s2-demand-access", consequence: "Timeline matters..." },
        { id: 'c', text: "Suggest a fake information test", nextNode: "4-s2-demand-test", consequence: "Trap the mole..." },
        { id: 'd', text: "Accuse Chen directly", nextNode: "4-s2-demand-death", consequence: "It could be anyone..." },
      ],
    },
    "4-s2-demand-death": { id: "4-s2-demand-death", type: "death", text: "'How do I know it's not you?' Chen's face goes cold. 'I've given twenty years to this job.' She stands. 'If you can't trust me, this doesn't work.' She walks out. The investigation continues without you - and without your insights, they miss crucial connections. The case falls apart.", deathMessage: "Accusing your best ally destroyed everything." },
    "4-s2-demand-backgrounds": { id: "4-s2-demand-backgrounds", type: "narrative", text: "You review each file together. One name stands out - Agent Peters has a brother who works for a law firm. A firm that represents Senator Morrison. 'That's... concerning,' Chen admits. She quietly removes Peters from the team.", nextNode: "4-s3", document: { title: "PETERS_FILE.pdf", preview: "Agent Peters. Brother at Morrison's law firm. Conflict flagged...", pdfUrl: "/documents/peters.pdf" } },
    "4-s2-demand-access": { id: "4-s2-demand-access", type: "narrative", text: "You map out who knew what when. The safehouse address was only shared three days ago. Only four agents had it. One of them accessed the file at 2 AM - unusual hours. 'We'll watch that one,' Chen says.", nextNode: "4-s3" },
    "4-s2-demand-test": { id: "4-s2-demand-test", type: "narrative", text: "'Give each agent different fake information. See which version leaks.' Chen considers, then nods. 'Canary trap. Old school but effective.' Three days later, a news outlet reports a 'fake' location - the version given to Agent Reeves. Got him.", nextNode: "4-s3", document: { title: "MOLE_IDENTIFIED.pdf", preview: "Agent Reeves confirmed as leak. Under surveillance...", pdfUrl: "/documents/mole.pdf" } },
    "4-s2-call": {
      id: "4-s2-call",
      type: "choice",
      text: "'I need to call someone. A friend. Someone outside all this.' Chen frowns. 'That's against protocol.' 'Protocol got my location leaked.' She hesitates, then hands you a burner phone. 'Two minutes. Speaker on.'",
      question: "Who do you call?",
      timerSeconds: 20,
      choices: [
        { id: 'a', text: "A journalist you've researched", nextNode: "4-s2-call-journalist", consequence: "Media backup..." },
        { id: 'b', text: "A family member", nextNode: "4-s2-call-family", consequence: "Personal anchor..." },
        { id: 'c', text: "A lawyer friend", nextNode: "4-s2-call-lawyer", consequence: "Legal protection..." },
        { id: 'd', text: "Someone from your old life", nextNode: "4-s2-call-death", consequence: "Familiar voice..." },
      ],
    },
    "4-s2-call-death": { id: "4-s2-call-death", type: "death", text: "You call your old roommate. 'Oh my god, are you okay? Where are you?' In the background, you hear a man's voice: 'Keep her talking.' The line goes dead. Chen grabs the phone. 'They were tracing that call.' Your friend was compromised. Now they know where you are - again.", deathMessage: "Your old contacts are being watched. You led them right to you." },
    "4-s2-call-journalist": { id: "4-s2-call-journalist", type: "narrative", text: "You call Sarah Chen at the Times - no relation to the agent. 'I'm the island survivor. If anything happens to me, the story comes out.' She agrees to hold the documents you send. Insurance policy activated.", nextNode: "4-s3", document: { title: "MEDIA_CONTACT.pdf", preview: "Journalist backup established. Dead man's switch...", pdfUrl: "/documents/journalist.pdf" } },
    "4-s2-call-family": { id: "4-s2-call-family", type: "narrative", text: "Your sister answers on the first ring. 'I'm alive. I'm safe. Don't believe anything you hear unless it comes from FBI Agent Chen.' She cries. You cry. Two minutes isn't enough, but it's something. You have a reason to survive this.", nextNode: "4-s3" },
    "4-s2-call-lawyer": { id: "4-s2-call-lawyer", type: "narrative", text: "Your law school friend picks up. 'I need representation. Not for crimes - for protection.' She agrees immediately. Within hours, you have legal documentation ensuring your testimony is preserved even if something happens to you.", nextNode: "4-s3" },

    // ========== STAGE 3: THE RAID ==========
    "4-s3": {
      id: "4-s3",
      type: "choice",
      text: "Raid day. You watch on monitors as teams hit the island, the mansion, Senator Morrison's office, six locations simultaneously. Chen narrates: 'Team Alpha breaching now.' Gunfire crackles through the speakers. Shouting. Then: 'Structure secure. Multiple individuals in custody.'",
      question: "STAGE 3/5 — The raid is happening. What's your focus?",
      timerSeconds: 20,
      choices: [
        { id: 'a', text: "Watch for victim rescues", nextNode: "4-s3-victims", consequence: "The survivors..." },
        { id: 'b', text: "Track who's being arrested", nextNode: "4-s3-arrests", consequence: "The perpetrators..." },
        { id: 'c', text: "Monitor for evidence collection", nextNode: "4-s3-evidence", consequence: "The proof..." },
        { id: 'd', text: "Look for anyone escaping", nextNode: "4-s3-escape", consequence: "Don't let them run..." },
      ],
    },
    "4-s3-victims": {
      id: "4-s3-victims",
      type: "choice",
      text: "The feed switches to the cottage building. Agents lead girls out - some walking, some carried. You count. Eight. Nine. Twelve. Some faces you recognize from the footage. They're alive.",
      question: "You see them being rescued. What do you do?",
      timerSeconds: 20,
      choices: [
        { id: 'a', text: "Ask to speak to them later", nextNode: "4-s3-victims-speak", consequence: "Connect with survivors..." },
        { id: 'b', text: "Help identify them from footage", nextNode: "4-s3-victims-identify", consequence: "Name them..." },
        { id: 'c', text: "Focus on medical attention for them", nextNode: "4-s3-victims-medical", consequence: "Their health first..." },
        { id: 'd', text: "Demand to go to the scene", nextNode: "4-s3-victims-death", consequence: "Be there..." },
      ],
    },
    "4-s3-victims-death": { id: "4-s3-victims-death", type: "death", text: "'I need to be there. They need to see someone who escaped.' Chen shakes her head but you're already moving. You commandeer a vehicle. Race to the scene. In the chaos, no one notices you until a figure emerges from the smoke - Victor Marsh, the money man, with a gun. 'You.' He fires.", deathMessage: "You went to the wrong place at the wrong time." },
    "4-s3-victims-speak": { id: "4-s3-victims-speak", type: "narrative", text: "'When they're ready. Only if they want to.' Chen nods. 'That can be arranged. Survivor-to-survivor support.' Weeks later, you meet Sofia again. She hugs you without words. Some things don't need words.", nextNode: "4-s4" },
    "4-s3-victims-identify": { id: "4-s3-victims-identify", type: "narrative", text: "You match faces to footage. 'That's Maria - she was there at least six months. That's Yuki - newer, maybe two weeks.' Your identification helps them find families, build timelines, piece together who did what to whom.", nextNode: "4-s4", document: { title: "VICTIM_IDS.pdf", preview: "14 victims identified. Families being contacted...", pdfUrl: "/documents/victims.pdf" } },
    "4-s3-victims-medical": { id: "4-s3-victims-medical", type: "narrative", text: "'Make sure they have trauma counselors. People who specialize in this.' Chen relays your recommendations. The FBI brings in experts. You help design the support protocol - you know what survivors need because you are one.", nextNode: "4-s4" },
    "4-s3-arrests": {
      id: "4-s3-arrests",
      type: "choice",
      text: "Names scroll across the screen. Guards. Staff. Then bigger fish: CEO Chen (no relation to the agent) in handcuffs. Ambassador Volkov. Senator Morrison's aide. But the Senator himself - his office is empty.",
      question: "The Senator escaped. What do you suggest?",
      timerSeconds: 20,
      choices: [
        { id: 'a', text: "Check his usual locations", nextNode: "4-s3-arrests-locations", consequence: "Where would he go..." },
        { id: 'b', text: "Monitor his communications", nextNode: "4-s3-arrests-comms", consequence: "He'll reach out..." },
        { id: 'c', text: "Freeze his assets immediately", nextNode: "4-s3-arrests-assets", consequence: "Cut off resources..." },
        { id: 'd', text: "Go public with his name now", nextNode: "4-s3-arrests-death", consequence: "Expose him..." },
      ],
    },
    "4-s3-arrests-death": { id: "4-s3-arrests-death", type: "death", text: "You grab a phone, call the journalist. 'Senator Morrison. Trafficking ring. Release everything.' The story breaks within hours. But Morrison has lawyers. He sues for defamation. Without proper procedure, the evidence becomes inadmissible. He walks free. And you've just committed a federal crime.", deathMessage: "Jumping the gun destroyed the case against Morrison." },
    "4-s3-arrests-locations": { id: "4-s3-arrests-locations", type: "narrative", text: "'His lake house. His mistress's apartment. The yacht.' You've studied this man. Teams scramble. Two hours later - found him on the yacht, trying to reach international waters. Arrested at gunpoint.", nextNode: "4-s4", document: { title: "MORRISON_ARREST.pdf", preview: "Senator Morrison apprehended. Flight attempt documented...", pdfUrl: "/documents/morrison.pdf" } },
    "4-s3-arrests-comms": { id: "4-s3-arrests-comms", type: "narrative", text: "NSA assets monitor his phone. He calls his lawyer. Then a private airfield. 'He's running.' A team intercepts him on the tarmac, bags packed, passport in hand. He looks resigned when the cuffs click.", nextNode: "4-s4" },
    "4-s3-arrests-assets": { id: "4-s3-arrests-assets", type: "narrative", text: "'Freeze everything. Every account.' Chen makes calls. Within an hour, Morrison's cards decline at the airfield. He can't buy fuel, can't charter a flight. He's trapped by his own wealth disappearing. He surrenders quietly.", nextNode: "4-s4" },
    "4-s3-evidence": {
      id: "4-s3-evidence",
      type: "choice",
      text: "Evidence techs sweep the island. Hard drives. Paper records. The underground level you identified yields a server room - decades of records. 'This is everything,' Chen breathes. 'Financial transactions. Client lists. Everything.'",
      question: "The evidence is massive. What do you prioritize?",
      timerSeconds: 20,
      choices: [
        { id: 'a', text: "Financial records to trace the network", nextNode: "4-s3-evidence-financial", consequence: "Follow the money..." },
        { id: 'b', text: "Client lists for prosecution", nextNode: "4-s3-evidence-clients", consequence: "Name them all..." },
        { id: 'c', text: "Communication records for connections", nextNode: "4-s3-evidence-comms", consequence: "Who knew who..." },
        { id: 'd', text: "Victim records for identification", nextNode: "4-s3-evidence-victims", consequence: "Help the survivors..." },
      ],
    },
    "4-s3-evidence-financial": { id: "4-s3-evidence-financial", type: "narrative", text: "You help analysts trace the money. Shell companies in Cyprus, banks in Switzerland, crypto wallets everywhere. The network is vast - but now it's visible. Asset seizures begin worldwide. Hundreds of millions frozen.", nextNode: "4-s4", document: { title: "FINANCIAL_WEB.pdf", preview: "International money trail mapped. $400M in assets identified...", pdfUrl: "/documents/financial.pdf" } },
    "4-s3-evidence-clients": { id: "4-s3-evidence-clients", type: "narrative", text: "The client list is worse than you imagined. Politicians. CEOs. A Supreme Court candidate. A children's TV host. 'This goes everywhere,' Chen says quietly. She's right. The dominoes will fall for years.", nextNode: "4-s4" },
    "4-s3-evidence-comms": { id: "4-s3-evidence-comms", type: "narrative", text: "Emails. Texts. Voice memos. The communications show how they recruited victims, paid off officials, silenced witnesses. The obstruction case alone will put people away for decades.", nextNode: "4-s4" },
    "4-s3-evidence-victims": { id: "4-s3-evidence-victims", type: "narrative", text: "Detailed records of every victim. Where they came from. How they were taken. What was done to them. It's horrific reading - but it helps identify 47 victims, many presumed dead. Families finally get answers.", nextNode: "4-s4", document: { title: "VICTIM_RECORDS.pdf", preview: "47 victims identified from records. Notifications beginning...", pdfUrl: "/documents/records.pdf" } },
    "4-s3-escape": {
      id: "4-s3-escape",
      type: "choice",
      text: "On a side monitor, you notice movement. A speedboat leaving the island's far dock. 'Someone's running!' You point. Chen radios the Coast Guard, but the boat is fast, heading for international waters.",
      question: "Someone's escaping. How do you help?",
      timerSeconds: 20,
      choices: [
        { id: 'a', text: "Identify the boat from your memory", nextNode: "4-s3-escape-boat", consequence: "You know their vessels..." },
        { id: 'b', text: "Guess their destination", nextNode: "4-s3-escape-destination", consequence: "Where would they go..." },
        { id: 'c', text: "Look for tracking devices", nextNode: "4-s3-escape-tracking", consequence: "Technical solution..." },
        { id: 'd', text: "Commandeer a helicopter to follow", nextNode: "4-s3-escape-death", consequence: "Chase them..." },
      ],
    },
    "4-s3-escape-death": { id: "4-s3-escape-death", type: "death", text: "You convince a pilot to pursue. The helicopter catches up to the boat - which has armed guards. Bullets punch through the cockpit. The pilot is hit. You're going down into the ocean. No one survives the crash.", deathMessage: "You're not an action hero. Some chases end badly." },
    "4-s3-escape-boat": { id: "4-s3-escape-boat", type: "narrative", text: "'That's the Meridian. Registered to Victor Marsh.' Coast Guard now has a name. Maritime law kicks in. International alerts go out. The Meridian is intercepted by the Mexican Navy three days later. Marsh is aboard.", nextNode: "4-s4", document: { title: "MARSH_CAPTURE.pdf", preview: "Victor Marsh captured at sea. Extradition pending...", pdfUrl: "/documents/marsh-capture.pdf" } },
    "4-s3-escape-destination": { id: "4-s3-escape-destination", type: "narrative", text: "'They have a property in the Caymans. A lawyer there. That's where they'd run.' Chen alerts international partners. Cayman authorities intercept the boat at their dock. Two high-value targets arrested.", nextNode: "4-s4" },
    "4-s3-escape-tracking": { id: "4-s3-escape-tracking", type: "narrative", text: "'The USB drives - check if any have GPS data for boats.' A tech analyst finds it. All vessels had trackers for security. You watch on satellite as the boat is intercepted by Coast Guard cutters an hour later.", nextNode: "4-s4" },

    // ========== STAGE 4: THE PRESSURE ==========
    "4-s4": {
      id: "4-s4",
      type: "choice",
      text: "The raids made headlines worldwide. Arrests continue. But now the pressure starts. Defense lawyers demand your identity. Threats arrive at the FBI office. Someone leaked your sister's address. This is what fighting powerful people looks like.",
      question: "STAGE 4/5 — The pushback begins. How do you handle the pressure?",
      timerSeconds: 20,
      choices: [
        { id: 'a', text: "Focus on protecting your family", nextNode: "4-s4-family", consequence: "Their safety first..." },
        { id: 'b', text: "Prepare for the legal battles", nextNode: "4-s4-legal", consequence: "Be ready to testify..." },
        { id: 'c', text: "Work with media strategically", nextNode: "4-s4-media", consequence: "Control the narrative..." },
        { id: 'd', text: "Confront the defense lawyers directly", nextNode: "4-s4-death", consequence: "Face them down..." },
      ],
    },
    "4-s4-death": { id: "4-s4-death", type: "death", text: "You agree to a deposition with Morrison's legal team. They're sharks. They twist your words, exploit your trauma, make you relive every moment. You break down on record. The footage leaks. Your credibility is destroyed before trial even begins.", deathMessage: "Never face hostile lawyers without preparation." },
    "4-s4-family": {
      id: "4-s4-family",
      type: "choice",
      text: "Your sister, your parents, your friends - they're all potential targets now. 'We can protect them,' Chen says, 'but they have to cooperate.' Your sister is stubborn. Your parents don't understand the danger.",
      question: "How do you convince your family to accept protection?",
      timerSeconds: 20,
      choices: [
        { id: 'a', text: "Tell them everything you witnessed", nextNode: "4-s4-family-truth", consequence: "The full horror..." },
        { id: 'b', text: "Show them the threats", nextNode: "4-s4-family-threats", consequence: "Make it real..." },
        { id: 'c', text: "Have Agent Chen explain", nextNode: "4-s4-family-chen", consequence: "Professional voice..." },
        { id: 'd', text: "Give them an ultimatum", nextNode: "4-s4-family-ultimatum", consequence: "Cooperate or else..." },
      ],
    },
    "4-s4-family-truth": { id: "4-s4-family-truth", type: "narrative", text: "You tell them. Not everything - some things can never be said - but enough. Your mother cries. Your father's hands shake. Your sister hugs you and doesn't let go. They accept protection immediately. Family stays together.", nextNode: "4-s5" },
    "4-s4-family-threats": { id: "4-s4-family-threats", type: "narrative", text: "You show them the letters. The photos of their houses. The surveillance reports. 'These people kill witnesses. They kill families.' The evidence is undeniable. They pack that night.", nextNode: "4-s5", document: { title: "THREAT_FILE.pdf", preview: "Documented threats against family. Protection authorized...", pdfUrl: "/documents/threats.pdf" } },
    "4-s4-family-chen": { id: "4-s4-family-chen", type: "narrative", text: "Agent Chen visits them personally. Professional, calm, terrifying in her certainty. 'These are dangerous people. Your daughter helped stop them. Now we help you.' Her badge and her sincerity convince them.", nextNode: "4-s5" },
    "4-s4-family-ultimatum": { id: "4-s4-family-ultimatum", type: "narrative", text: "'Accept protection or I disappear completely. You'll never hear from me again. That's what it takes to keep you safe.' It's harsh, but it works. They're in protective custody by morning.", nextNode: "4-s5" },
    "4-s4-legal": {
      id: "4-s4-legal",
      type: "choice",
      text: "Depositions, grand jury testimony, trial preparation - the legal process is brutal. Defense lawyers will try to destroy you. Prosecutors coach you for hours. Every detail of your testimony matters.",
      question: "How do you prepare for the legal onslaught?",
      timerSeconds: 20,
      choices: [
        { id: 'a', text: "Practice with mock cross-examinations", nextNode: "4-s4-legal-mock", consequence: "Be ready for anything..." },
        { id: 'b', text: "Work with a trauma-informed therapist", nextNode: "4-s4-legal-therapy", consequence: "Stay stable..." },
        { id: 'c', text: "Review every piece of evidence again", nextNode: "4-s4-legal-evidence", consequence: "Know everything..." },
        { id: 'd', text: "Write your full statement yourself", nextNode: "4-s4-legal-statement", consequence: "Your words..." },
      ],
    },
    "4-s4-legal-mock": { id: "4-s4-legal-mock", type: "narrative", text: "Prosecutors play defense lawyers. They attack your timeline, your memory, your motives. They call you a liar, a criminal, a manipulator. It's brutal - but when the real trial comes, nothing surprises you. You're ready.", nextNode: "4-s5" },
    "4-s4-legal-therapy": { id: "4-s4-legal-therapy", type: "narrative", text: "A specialist in witness trauma helps you process everything before trial. You learn techniques to stay calm, to separate testimony from reliving. When defense lawyers try to trigger you in court, you stay centered.", nextNode: "4-s5", document: { title: "THERAPY_PREP.pdf", preview: "Witness support protocol. Stabilization techniques...", pdfUrl: "/documents/therapy.pdf" } },
    "4-s4-legal-evidence": { id: "4-s4-legal-evidence", type: "narrative", text: "You study every file, every photo, every timestamp. When lawyers try to confuse you with details, you correct them. 'Actually, that was Tuesday, March 15th, at 9:47 PM. The surveillance log confirms it.' Precision destroys their tactics.", nextNode: "4-s5" },
    "4-s4-legal-statement": { id: "4-s4-legal-statement", type: "narrative", text: "You write it all down. In your words. Your experience. Your truth. It takes weeks. When you read it in court, no one can call it coached or manipulated. It's unmistakably your voice, your story.", nextNode: "4-s5" },
    "4-s4-media": {
      id: "4-s4-media",
      type: "choice",
      text: "The media circus is overwhelming. Defense lawyers use press conferences to attack your credibility. Tabloids speculate about your identity. Social media is a nightmare. But media can also be a weapon.",
      question: "How do you handle the media strategically?",
      timerSeconds: 20,
      choices: [
        { id: 'a', text: "Stay completely silent", nextNode: "4-s4-media-silent", consequence: "Let others talk..." },
        { id: 'b', text: "Give one exclusive interview", nextNode: "4-s4-media-exclusive", consequence: "Control the story..." },
        { id: 'c', text: "Write an anonymous op-ed", nextNode: "4-s4-media-oped", consequence: "Your perspective..." },
        { id: 'd', text: "Work with victim advocacy groups", nextNode: "4-s4-media-advocacy", consequence: "Bigger movement..." },
      ],
    },
    "4-s4-media-silent": { id: "4-s4-media-silent", type: "narrative", text: "You say nothing. Let the evidence speak. The defense lawyers' attacks seem more desperate without a target. Silence becomes a form of power - they can't twist words you never said.", nextNode: "4-s5" },
    "4-s4-media-exclusive": { id: "4-s4-media-exclusive", type: "narrative", text: "One interview. One trusted journalist. No sensationalism, just truth. It airs the week before trial. The public sees a survivor, not a abstract witness. Sympathy shifts. Jury pools are affected.", nextNode: "4-s5", document: { title: "INTERVIEW_TRANSCRIPT.pdf", preview: "Survivor interview. Massive public impact...", pdfUrl: "/documents/interview.pdf" } },
    "4-s4-media-oped": { id: "4-s4-media-oped", type: "narrative", text: "'What I Survived' runs in the Washington Post under a pseudonym. It doesn't name anyone - just describes what trafficking looks like from inside. It's shared millions of times. The conversation changes.", nextNode: "4-s5" },
    "4-s4-media-advocacy": { id: "4-s4-media-advocacy", type: "narrative", text: "Organizations like RAINN and Polaris amplify your story while protecting your identity. You become a symbol - anonymous but powerful. Legislation starts moving through Congress. Your suffering might prevent others'.", nextNode: "4-s5" },

    // ========== STAGE 5: THE TRIAL BEGINS ==========
    "4-s5": {
      id: "4-s5",
      type: "choice",
      text: "Trial day. Senator Morrison, CEO Chen, a dozen others at the defense table. Camera flashes. Protesters outside. You're led through a back entrance, heart pounding. The courtroom falls silent as you take the witness stand.",
      question: "STAGE 5/5 — You're on the stand. How do you begin your testimony?",
      timerSeconds: 20,
      choices: [
        { id: 'a', text: "Start from the charity gala", nextNode: "4-s5-gala", consequence: "The beginning..." },
        { id: 'b', text: "Start from waking up in the cell", nextNode: "4-s5-cell", consequence: "The horror..." },
        { id: 'c', text: "Start from the escape", nextNode: "4-s5-escape", consequence: "The courage..." },
        { id: 'd', text: "Start from seeing the victims", nextNode: "4-s5-victims", consequence: "The others..." },
      ],
    },
    "4-s5-gala": { id: "4-s5-gala", type: "narrative", text: "'I was at a charity gala. A man offered me champagne.' The courtroom hangs on every word. You take them through every moment - the trust, the drugging, the awakening in hell. By the time you finish, jurors are crying. Senator Morrison can't meet your eyes.", nextNode: "4-complete", document: { title: "TESTIMONY_RECORD.pdf", preview: "Complete testimony delivered. Devastating impact...", pdfUrl: "/documents/testimony.pdf" } },
    "4-s5-cell": { id: "4-s5-cell", type: "narrative", text: "'I woke up in a concrete room. No windows. Zip ties on my wrists.' Your voice is steady. You describe the fear, the planning, the escape. Defense lawyers try to interrupt - overruled, every time. Your truth cannot be silenced.", nextNode: "4-complete" },
    "4-s5-escape": { id: "4-s5-escape", type: "narrative", text: "'I escaped because I refused to die there.' You describe every choice, every danger, every moment you almost didn't make it. The jury sees not a victim but a survivor. Someone who fought back. Someone believable.", nextNode: "4-complete" },
    "4-s5-victims": { id: "4-s5-victims", type: "narrative", text: "'I saw them. The other girls. Chained. Drugged. Sold.' You give voice to those who can't speak. Every victim you remember, you name. Every horror you witnessed, you describe. The courtroom understands: this wasn't just your nightmare. It was an industry of human suffering.", nextNode: "4-complete" },

    // ========== CHAPTER 4 COMPLETE ==========
    "4-complete": {
      id: "4-complete",
      type: "chapter-end",
      text: "Your testimony takes three days. Cross-examination is brutal but you hold firm. The evidence is overwhelming. As you step down from the witness stand, you know: whatever happens next, you spoke your truth. The world heard. Senator Morrison stares at the table, a broken man. The trial continues - but the outcome feels inevitable. You survived. You testified. And now the justice system will do its work.",
      chapterComplete: {
        chapter: 4,
        nextChapter: 5,
        summary: "You helped build the case, survived the pressure, and delivered devastating testimony. The trial is underway. Now comes the verdict."
      },
    },
  },
};